### ISSUE TITLE
Support for numpy.round/round_/around

### ISSUE THREAD

**Issue by seibert** [numba/numba#1027]
In Numpy, `round`/`round_`/`around` are all aliases to the same ufunc, which does element-wise rounding in the same fashion as the Python standard `round()` function:

http://docs.scipy.org/doc/numpy/reference/generated/numpy.round_.html

Now that we have support for `round()` in Numba, it would be nice to support the Numpy-equivalent as well.

**Comment by pitrou** [comment]
Interesting. `round()` is actually not a ufunc but redirects to the array object's `.round()` method.

**Comment by ovillellas** [comment]
Actually, I recall adding plenty of support for ufuncs, and a way to find out which ufuncs (there is a list somewhere in the docs) was looking for symbols in the numpy namespace that were ufunc objects. So it is very likely that it is not implemented because of that. I wonder how many of those "ufunc-like" functions  are missing that would be quite easy to support.

Also of note, some of the support for ufuncs *rely* on the ufunc objects themselves, as their type inference is based on some information ufuncs have with them, but adding support for other "ufunc-like" functions wouldn't be difficult if that data is defined somewhere else.
