### ISSUE TITLE
Missing dependencies in setup.py

### ISSUE THREAD

**Issue by zopyx** [numba/numba#1141]
We are in 2015 and you have not heard about specifying dependencies like

numpy
enum34
llvmlite

in your setup.py and to ensure that numba can be easily installed using pip/easy_install? So hard?

**Comment by pitrou** [comment]
Yeah, our packaging story may be a bit imperfect. We welcome patches, though :)

**Comment by seibert** [comment]
The bigger question for me is whether llvmlite is installable with pip.  No point in specifying the dependencies until the dependencies can also be pip-installed.

**Comment by zopyx** [comment]
LOL..i can only laugh about such a huge amount of ignorance...do what u must

**Comment by abitrolly** [comment]
@zopyx `numba` is sponsored by `conda`. I don't know if it extracts dependencies from `setup.py`, but for people who use `conda`, `pip` often does not exists.

**Comment by zopyx** [comment]
Don't respond to closed issues, in particular when they are 6 yrs old...this is odd 🤡

**Comment by abitrolly** [comment]
It is never too late to educate people ignorant of the different way of doing things.

**Comment by seibert** [comment]
Numba and llvmlite wheels have been made available as part of our release process in the years since this PR was closed, and both projects have been installable with pip for some time.

**Comment by abitrolly** [comment]
@seibert and there is still a problem with missing dependencies, like with [`numba 0.50.1`](https://github.com/numba/numba/releases/tag/0.50.1) with was released just a year ago.

```bash
$ podman run --rm -it python:3 pip3 install numba==0.50.1
Collecting numba==0.51.1
  Downloading numba-0.51.1.tar.gz (2.1 MB)
...
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/local/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i1mbdsa6/llvmlite_fee5f074037944858876cc920ccbf924/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i1mbdsa6/llvmlite_fee5f074037944858876cc920ccbf924/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t_7t9u68/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/llvmlite Check the logs for full command output.
```

**Comment by seibert** [comment]
This error is caused by pip being unable to locate a wheel for your platform.  Unless you have a very unusual platform, likely the issue is that your pip is too old to know about manylinux2014 wheels.  When pip can't find the wheel, it tries to build from source code and we don't vendor all of LLVM into llvmlite, so it goes to find LLVM on your system and fails.  LLVM is not a Python package, so pip can't install it either.   (This is a limitation of language-specific package managers like pip.)

If you use pip 19.3 or later (I have no idea which python version the `python:3` container is using) you should be able to install everything without compilation.

**Comment by abitrolly** [comment]
`python:3` image is Python 3.9 on Debian 11 https://hub.docker.com/_/python

**Comment by seibert** [comment]
Ah, Numba didn't get Python 3.9 support until version 0.53.0, so we didn't post any python 3.9 wheels before that.  This will work:
```
docker run --rm -it python:3 pip3 install numba==0.53.0
```
Anyway, this is going well beyond the scope of this issue.  :)

**Comment by esc** [comment]
@abitrolly if you are having installation issues, please do feel free to open a new issue or open a thread on our dicsourse. We will be happy to diagnose and fix any `pip` related installation issues you may have. We are committed to providing `pip` installable packages via PyPi.

**Comment by abitrolly** [comment]
@seibert it doesn't work for the app I am trying, because the app uses both `nopython` and `forceobj` params https://github.com/lambdaloop/aniposelib/issues/5 and it is not clear how to see if Numba compiles anything and test performance, to ensure that removing `forceobj` would not cause any regressions.

**Comment by esc** [comment]
@abitrolly Thank you for adding to this issue. The options `nopython` and `forceobj` are incompatible and it is a bug in the application if these are use at the same time. This was allowed due to a bug in Numba but was closed with: https://github.com/numba/numba/pull/5808 -- I would strongly suggest to fix the application code if possible to comply with this restriction so that it remains compatible with future versions of Numba.

**Comment by abitrolly** [comment]
@esc if there is a bug in [the application](https://github.com/lambdaloop/aniposelib/blob/master/aniposelib/cameras.py) I can not modify it without ensuring that the behavior and performance will be the same. I opened #7341 about that.

Ufortunately, the behavior after removed `forceobj` is not specified, and I do not understand what Numba does to ensure there will be no performance penalty. To me `forceobj` looked like some fallback mechanism, which would still optimize Numba code, and if I remove it, there will be no optimization on this old version of Numba if `nopython` compilation fails.

Understanding why `nopython` compilation may fail would also make me more confident to make a change, if I can validate that there would be no breaks.

**Comment by esc** [comment]
@abitrolly thank you for commenting on this and thank you for opening #7341 - Please be advised however that this conversation is happening on a closed issue and that we do discourage such behaviour within the Numba ecosystem. If you believe there to be further issues related to `forecobj` andf `nopython please do open a new issue about that, or better yet, please start a thread on our discourse at: https://numba.discourse.group/ --- thank you for your understanding!

**Comment by abitrolly** [comment]
Asked here https://numba.discourse.group/t/how-do-i-know-if-numba-compiled-anything/858

**Comment by esc** [comment]
> Asked here https://numba.discourse.group/t/how-do-i-know-if-numba-compiled-anything/858

Thank you! It is appreciated!
