### ISSUE TITLE
Allow indexing ndarray.flat, e.g., x.flat[i]

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1203]
For example, we could loop over all elements of an N-dimensional array (in C order) as follows:
```python
total = 0
for i in range(a.size):
    total += a.flat[i]
```

This is another possible solution for fast indexing over multiple, N-dimensional arrays (e.g., https://github.com/numba/numba/issues/1111, https://github.com/numba/numba/issues/1183).

Does this seem like the sort of operation that Numba could do a nice job of accelerating?

**Comment by pitrou** [comment]
Yes, it does. I hadn't noticed that ndarray.flat could be indexed. That looks a bit weird for an iterator.

**Comment by seibert** [comment]
If not super slow, this idiom of indexing ndarray.flat could actually be useful in CUDA, where you want to step through the iterator with a large stride in order to achieve a certain memory access pattern between threads.

**Comment by pitrou** [comment]
Ok, after testing a bit, there will be a caveat: it will be super-fast on C-contiguous arrays, but probably slow on non-C-contiguous ones, where you have to reconvert the integer index into a tuple index in order to multiply with the corresponding strides... Unless anyone can think of something better?

**Comment by seibert** [comment]
C-contiguous is probably the most important case.  If needed, we can put a performance warning in the manual.

**Comment by pitrou** [comment]
If we expose ``ndarray.flags.c_contiguous``, by the way, we can allow people to use different iteration methods depending on the array layout.

**Comment by seibert** [comment]
That is a good idea.

**Comment by seibert** [comment]
Can we identify the attribute as a constant in such a way that LLVM can actually eliminate the dead code in the branch corresponding to the other layout?  Since the continguousness (continguity?) of the array is part of the Numba type, any given lowering of a function that branches on c_contiguous only needs one side of the branch, right?

**Comment by pitrou** [comment]
Yes, it will be a runtime constant.
