### ISSUE TITLE
Minimal not working example (MNWE) using `nopython` causes console to crash

### ISSUE THREAD

**Issue by bmer** [numba/numba#1411]
Hi all,

(back again after a hiatus!)

Here's the MNWE: https://gist.github.com/bmer/a9eb9454723d0905ce13

Does running the MNWE script cause your console to crash as well?

I am using the latest version of numba available for win64 through the development channel.

**Comment by synapticarbors** [comment]
Works for me using Numba 0.20.0 on OSX installed via Anaconda, but fails with the following message using `0.21.0-np19py27_34` from the dev channel:

```
python(23557,0x7fff7c73b310) malloc: *** error for object 0x10c74b3e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by bmer** [comment]
@sklam Are you able to reproduce the error too?

**Comment by pitrou** [comment]
I can reproduce the crash under Linux 64-bit.

**Comment by synapticarbors** [comment]
It would be great to get this regression fix into a minor release since I've now come across this in real production code that I was attempting to test with 0.21.0 that previously worked in 0.20.0. I can confirm that in the latest dev release, 0.21.0-np19py27_111, my code works as it did under 0.20.0.

**Comment by seibert** [comment]
Our next release should be coming much faster than the last one, as we'll want to get Python 3.5 support officially released as well.
