### ISSUE TITLE
Minimal not working example (MNWE) using `nopython` causes `Invalid usage of getitem` error

### ISSUE THREAD

**Issue by bmer** [numba/numba#1446]
Here's the MNWE: https://gist.github.com/bmer/800286e0d972e68cb9ad

Here's the error that's created:

```python
    infer.propagate()
  File "a:\anaconda\lib\site-packages\numba-0.21.0+161.ga854ae8-py2.7-win-amd64.egg\numba\typeinfer.py", line 510, in propagate
    raise errors[0]
TypingError: Invalid usage of getitem with parameters (float64, int64)
 * parameterized
File "possible_numba_error_8.py", line 13

Failed at nopython (nopython frontend)
Invalid usage of getitem with parameters (float64, int64)
 * parameterized
File "possible_numba_error_8.py", line 13
```

Are you able to reproduce it as well?

**Comment by bmer** [comment]
@pitrou @seibert @sklam I would be very interested in knowing if this is an issue you can reproduce as well, and if it can be fixed, since my research code is sort of dependent on it. I am already extremely in your guys' debt, so I am very sorry for bugging you about this! Please just see it as a sign of "mini-desperation" :p

**Comment by pitrou** [comment]
Well, is it supposed to work? The `g(arr2)` call passes a 1d float array to g(), which then indexes it with an integer, giving a float, and passes the float to f(), which expects an array. You can't index a float, hence the error message.

**Comment by bmer** [comment]
Hi Antoine,

Yes, it is supposed to work because there is an if statement specifically
in g that is supposed to prevent execution of the for loop. Indeed, if we
remove the no python requirement, the code works fine.

So, why does the if statement in g fail in no python mode?

**Comment by pitrou** [comment]
> So, why does the if statement in g fail in no python mode?

Numba fails compiling the function because it finds it has the wrong types. The `if` statement is not evaluated at compile-time but at run-time, so the compiler does not have enough information to know that it can omit typing and compiling the call to the f() function.

Numba is less dynamic than pure Python so you can't ask Numba to compile operations which look nonsensical at compile-time (such as indexing a scalar). Unless you do rather weird things, it shouldn't be a problem in general.

**Comment by bmer** [comment]
>
> Numba fails compiling the function because it finds it has the wrong
> types. The if statement is not evaluated at compile-time but at run-time,
> so the compiler does not have enough information to know that it can omit
> typing and compiling the call to the f() function.


I think I understand.

I am passing in a numpy array every time (but of possibly different
dimensions), so that qualifies as different types? I was hoping that the
fact that they are numpy arrays would mean that the `shape` attribute would
be available for testing.

I suppose the work around for this would be to to either use C++, where an
array is an array, regardless of its dimension, and thus one can still pass
around arrays and test their shape, without the compiler complaining that
*it* doesn't know the shape of the array?

Or, if I continue to use numba, I have to make sure that I do shape testing
at the level of Python code, since using the shape attribute in nopython
code is nonsensical?

**Comment by pitrou** [comment]
Le 29/09/2015 17:35, Brian Merchant a écrit :
> 
> I am passing in a numpy array every time (but of possibly different
> dimensions), so that qualifies as different types?

Numpy arrays of different dimensionalities or different dtypes have
different Numba types, so a separate specialization will be compiled for
each of those.

> I suppose the work around for this would be to to either use C++, where an
> array is an array, regardless of its dimension, and thus one can still pass
> around arrays and test their shape, without the compiler complaining that
> *it* doesn't know the shape of the array?

I don't know what your actual requirement is, since it's not obvious why
you wrote the posted code that way (the function doesn't seem to do much
after all!).

You can certainly test array shapes in Numba, you can just not expect
the comparison to happen at compile-time. Numba will happily run the
comparison at run-time.

If you want a function to be generic enough to work with different array
dimensionalities, this is certainly possible at least for some problems,
so you could post on the mailing-list describing roughly what you are
trying to do.
(also, the next Numba version should support more Numpy indexing
schemes, allowing you to be more flexible - for example using the
ellipsis `...`).

**Comment by bmer** [comment]
Hi Antoine,

I am not sure what the run time vs. compile time issue is here, but this is
due to my lack of experience with programming. So, I really appreciate your
patience, and I promise to stop bugging you soon :)

Doesn't the if statement get evaluated every time the function is run (and
not just at compile time)? If yes, then why would the for loop even be
executed (since it is under the if statement, and the if condition is
"array does not have zero elements in the first dimension...")? In
psuedocode, my understanding is:

(each time g is called with input arr...i.e., at run time, not compile time)

if array does not have zero elements in first dimension (if arr.shape[0] >
0)
    then do this for loop which assumes that the array does not have zero
elements in the first dimension
otherwise
    do nothing

In nopython mode, the if statement seems to be completely ignored, so we
have this happening:


(each time g is called with input arr...i.e., at run time, not compile time)

if whatever, doesn't matter, just execute the commands below the if
statement anyway
    then do this for loop which assumes that the array does not have zero
elements in the first dimension (oops! error, we can't assume that because
our if statement doesn't test for anything)
otherwise
    do nothing

How is this change in the interpretation of the if-statement itself
expected?

**Comment by pitrou** [comment]
Hi Brian,

Le 29/09/2015 21:57, Brian Merchant a écrit :
> 
> Doesn't the if statement get evaluated every time the function is run (and
> not just at compile time)? If yes, then why would the for loop even be
> executed (since it is under the if statement, and the if condition is
> "array does not have zero elements in the first dimension...")?

The for loop is not executed, but it gets compiled. And the compilation
fails, since the types are not appropriate in f(). I hope that makes
sense :-)

(if you have done a language like C or Java, this is like a piece of
code that would not get called in practice but would contain a syntax
error; actually, Python does that too for syntax errors)

**Comment by pitrou** [comment]
I'm closing the issue, since this behaviour won't probably change in Numba.

**Comment by bmer** [comment]
Hi Antoine,

Thanks for helping to clarify! I think I am all good with what happens now
:)
