### ISSUE TITLE
Polly: LLVM Framework for High-Level Loop and Data-Locality Optimizations

### ISSUE THREAD

**Issue by datnamer** [numba/numba#1447]
http://polly.llvm.org/

Leaving this here in case it is useful for numba.

**Comment by seibert** [comment]
While interesting, we are unlikely to get to this any time soon.  Closing.

**Comment by JamesAllingham** [comment]
@seibert this is something that I am actually considering investigating. However, I am still very much a beginner when it comes to Numba and LLVM!

For the sake of full disclosure: I am currently a Com Sci masters student taking a course in LLVM and I was thinking about trying to integrate Polly into LLVM for a school project. I would be more than happy to contribute any results from my investigation, whether they are good or bad. 

That said, since I am not particularly knowledgeable about Numba or LLVM, I will probably need some advice along the way. Like some tips for getting started on contributing to the Numba code base. 

My first question would be regarding Numba bounds checks - I read [here](http://numba.pydata.org/numba-doc/0.12/tutorial_numpy_and_numba.html) that Numba does not have range checks on array indices - I assume that this means that the LLVM IR does not have range checks? As discussed [here](https://docs.google.com/document/d/1s5mmSW965qmOEbHiM3O4XFz-Vd7cy9TxX9RQaTK_SQo/edit) this was a challenge when integrating Polly with Julia. 

My second question is regarding an issue with integrating Polly with Tensorflow's XLA . I read [here](https://github.com/tensorflow/tensorflow/issues/8100) that "convolution and gemm are implemented though LLVM calls into pre-compiled Eigen code, which is to say LLVM at this level has no visibility into the low level loops". In other words, much of the key functionality of Tensorflow would not be visible to Polly since it was pre-compiled. Is this something that might be an issue for Numba? 

Are there any other challenges that stand out for integrating Polly with Numba? Or is this likely to be a relatively straightforward undertaking (which is something I actually don't want since I need something relatively complex for my school project :smile:)?

**Comment by seibert** [comment]
You are correct that Numba does not generate bounds checking code, so that won't be an obstacle for Polly.

Numba also is less likely to have the issue you describe from Tensorflow, as Numba-generated code tends to have explicit loops.  One exception is code that uses np.dot() or other np.linalg functions, which we will translate to calls to the optimized BLAS/LAPACK implementation that was used with scipy (usually this is MKL for Anaconda-built packages, but might also be ATLAS or OpenBLAS).  Those calls would not be optimizable by Polly, but there's plenty of explicit loops in other Numba use cases.  In particular, you might find code generated by the `@stencil` decorator (in an open PR to be merged very soon) to be of interest.

If you have questions about Numba, we're more than happy to answer them.  You might find the [numba-users mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/numba-users) a better venue for asking general development questions.

**Comment by ehsantn** [comment]
@JamesAllingham @seibert 
In case Polly didn't work out, one possibility is implementing more functionality/optimizations in the ParallelAccelerator subsystem of Numba if you are interested.
