### ISSUE TITLE
Compilation error does not halt install or return failure code.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#1510]
Running `python setup.py install` with an e.g. syntax error in the source correctly emits text stating there is an error but the process seems to reports success, also if there's a pre-existing built egg it will get installed.

**Comment by pitrou** [comment]
I don't know how much of this is a Numba-specific bug rather than e.g. a distutils or setuptools bug... Our setup.py doesn't seem to do anything terrific.

**Comment by pitrou** [comment]
I think it's a feature rather than a bug. Consider a code base with some Python 3-specific modules. You don't want `python setup.py install` to fail on Python 2 just because the syntax of those modules doesn't parse on Python 2.

Contrast with `conda-build`, which is too strict: https://github.com/conda/conda-build/issues/1001
