### ISSUE TITLE
CUDA device memory not being freed immediately

### ISSUE THREAD

**Issue by seibert** [numba/numba#1531]
Reported from [mailing list](https://groups.google.com/a/continuum.io/d/topic/numba-users/jDDl86mUdqA/discussion):

``` python
import numpy as np
from numba import cuda

gpus = cuda.gpus.lst
mem_list = []
for gpu in gpus:
    with gpu:
        meminfo = cuda.current_context().get_memory_info()
    mem_list.append(int(meminfo[0]))
sort_gpus = [x for (y, x) in sorted(zip(mem_list, gpus), reverse=True)]
sort_gmem = [y for (y, x) in sorted(zip(mem_list, gpus), reverse=True)]

print [mem/1e9 for mem in sort_gmem]

with sort_gpus[0]:
    a = np.zeros(9e8, dtype=np.float32)
    print a.nbytes/1e9
    b=cuda.to_device(a)
    print cuda.current_context().get_memory_info()[0]/1e9
    del b
    print cuda.current_context().get_memory_info()[0]/1e9
```

Produces following output:

```
[4.134227968, 2.646806528] 3.6 0.533983232 0.533983232
```

From reporter:

> The first two are as expected, since one of the GPUs is occupied with two monitors. However, as we can see after the deletion of the reference to the GPU array, get_memory_info() still seems to think that the memory is still allocated. Is this an issue with get_memory_info() or is the array still allocated?

**Comment by seibert** [comment]
@sklam Ideas?

**Comment by sklam** [comment]
There are some logic to prevent immediate deallocation because it causes a synchronization to the cuda stream.  Deallocation is triggered in batch and deferred.  Allocation will flush some pending deallocation.

**Comment by seibert** [comment]
Ah, I see.  Is this the best way to do this (from the above thread)?
```
cuda.current_context().trashing.clear()
```
Or is it possible to trigger cleanup automatically when the device or stream is synchronized?  (That would not require people to use an undocumented method to trigger immediate deallocation.)

**Comment by sklam** [comment]
We can add a user API to force memory deallocation instead of ``cuda.current_context().trashing.clear()``

**Comment by CJ-Wright** [comment]
Would it be possible to change the way that `cuda.current_context().get_memory_info()` reports memory so that it includes the fact that the arrays have been deleted and will be removed from memory before the next allocation?  I mean this is memory which will be free as soon as we want to allocate new arrays.

**Comment by CJ-Wright** [comment]
Out of curiosity, did the user API for trashing ever come about?

**Comment by georgedimitriadis** [comment]
Following the above advice I was using 
`cuda.current_context().trashing.clear()`
in order to clear up some pending arrays from previous iterations of an iterative call of my kernel.
This was working nicely while I was using an older version of numba.

Since I updated two days ago to version 0.30 trashing() isn't a function anymore and I can't seem to find anything else that will do the same job. cuda.synchronize() will still not do the job and I am kind of stuck because the code won't work any more (and it is too large and complex to change now, even if this was possible in the first place).

Some help would be really appreciated.

**Comment by sklam** [comment]
A PR was merged to improve the deallocation code.  There are user configurable options exposed as environment variables.  See https://github.com/numba/numba/pull/2046#issue-171708499 for details.  Hopefully, those options will solve most of the problems.  Otherwise, you can force a deallocation with `cuda.current_context().deallocations.clear()`.

Another reason that users should rarely need to force deallocation is that the gpu allocation function in numba will now force deallocation and retry if the first attempt resulted in out-of-memory error.

**Comment by seibert** [comment]
Closing.

**Comment by kmader** [comment]
In performing simple benchmarks, it seems you need to manually clear the cuda memory
- [without manual clearing](https://www.kaggle.com/kmader/cuda-with-numba?scriptVersionId=18414213)
```
CudaAPIError: [700] Call to cuMemcpyHtoD results in UNKNOWN_CUDA_ERROR
```
- [with manual clearing](https://www.kaggle.com/kmader/cuda-with-numba?scriptVersionId=18581793)

### Loop run

```
import pandas as pd
out_res = []
for c_dim in np.logspace(1.5, 4.5, 18).astype(int):
    
    A = np.random.uniform(-1, 1, size=(c_dim, c_dim)).astype('float32')
    B = np.random.uniform(-1, 1, size=(c_dim, c_dim)).astype('float32')
    C = np.zeros((c_dim, c_dim), dtype='float32')
    Ac = cuda.to_device(A)
    Bc = cuda.to_device(B)
    Cc = cuda.to_device(C)
    cuda_time = lambda times=100: timeit(lambda : cu_square_matrix_mul(Ac, Bc, Cc), number=times)*1000.0/times
    numpy_time = lambda times=100: timeit(lambda : np.matmul(A, B, out=C), number=times)*1000.0/times
    with cuda.defer_cleanup():
        out_res.append({'dim': c_dim, 
                        'cuda': cuda_time(), 
                        'numpy': numpy_time()})
```

**Comment by YoushanLiu** [comment]
I also found this problem. In OpenACC, the arrays are still presented on GPU after !$acc exit data. How to force memory deallocation? @kmader sklam

**Comment by Crear12** [comment]
I noticed some updates in numba, and used device.reset() to free the GPU memory, which caused new error: CudaAPIError: [701] Call to cuLaunchKernel results in CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES.

**Comment by stuartarchibald** [comment]
@Crear12 if this is a regression across Numba versions then please feel free to open a new issue with a reproducer for it and someone will take a look. Thanks.
