### ISSUE TITLE
Locking issue with gevent+multithreading

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1556]
Given this code:

```python
from gevent import monkey
monkey.patch_all()

import numpy as np
import numba as nb
from gevent.threadpool import ThreadPool
#from multiprocessing.dummy import Pool as ThreadPool

@nb.jit(nopython=True, nogil=True)
def nb_cpuburn_notypedef(n):
    res = 0.0
    for x in range(1, n):
        res += x * x
        res = np.log(res)
    return res

@nb.jit(nb.float64(nb.int64), nopython=True, nogil=True)
def nb_cpuburn(n):
    res = 0.0
    for x in range(1, n):
        res += x * x
        res = np.log(res)
    return res

if __name__ == '__main__':
    p = ThreadPool(4)
    print p.map(nb_cpuburn, [1e6]*4)
    print p.map(nb_cpuburn_notypedef, [1e6]*4)
```

The first version of nb_cpuburn works great, but the second version without explicit typedef throws this crash:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/threadpool.py", line 193, in _worker
    value = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 172, in _compile_for_args
    return self.compile(sig)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 327, in compile
    with self._compile_lock:
  File "/usr/local/lib/python2.7/dist-packages/numba/utils.py", line 221, in acquire
    self._lock.acquire()
  File "gevent/_semaphore.pyx", line 112, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3386)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
(<ThreadPool at 0x7fd2378e1710 1/4/4>,
 CPUOverloaded(<function nb_cpuburn_notypedef at 0x7fd2378ac0c8>)) failed with LoopExit
```

The monkeypatching itself doesn't seem to be the problem, as using the ordinary dummy threadpool shows no errors. Also, the gevent ThreadPool is not doing any fuzzy black magic. Using the typedef is not a big deal in this example, though I'm still a bit puzzled, what actually causes this bug.

**Comment by pitrou** [comment]
Ok, I understand what's going on. You're asking gevent to create a pool of native threads. However, gevent also monkey-patches standard library locks (from the `threading` module) to behave as greenlet locks rather than native locks. Then, when taking a lock from a native thread, gevent doesn't "see" the other greenlet owning the lock and running in *another* native thread (since it seems to have a distinct "hub" of greenlets for each native thread), so it concludes that taking the lock would wait forever - since there's no visible greenlet that could release it.

This is actually the same issue as https://stackoverflow.com/questions/22108576/share-gevent-locks-semaphores-between-threadpool-threads . I suggest asking the question to the gevent communit.

**Comment by pitrou** [comment]
Or you can simply use a normal thread pool without bothering with gevent...

**Comment by ml31415** [comment]
Thanks for this hint! The setup is indeed quite like the one on stackoverflow, though probably not a too common constellation. Strange nevertheless for me, that using the threaded Pool from multiprocessing.dummy, together with gevent monkeypatching works fine for both functions. I thought, it should raise the same issues as above, but it didn't. For now, I'll probably just live with the restriction, to always add the function definition decorator by hand. Dropping gevent is no option, as the main part of the application runs on it, which just spawns some real threads for math heavylifting and longer running external library calls.
