### ISSUE TITLE
NBEP 2 (Extension API) Discussion

### ISSUE THREAD

**Issue by seibert** [numba/numba#1567]
This issue is for tracking discussion of the NBEP 2 draft (from PR #1307) here:

http://numba.pydata.org/numba-doc/dev/proposals/extension-points.html

**Comment by seibert** [comment]
It might be helpful to develop an example outside the Numba source tree that uses the new extension along with the NBEP.  I would vote for something a little tricky, like partial support for passing Pandas DataFrames into Numba functions.

(Not with complete coverage of DataFrames, obviously, but just enough to exercise all the important parts of the NBEP.)

**Comment by sklam** [comment]
I just noticed that it did not mention the magic attribute `_numba_type_` that is used in `typeof` (https://github.com/numba/numba/blob/b23166255d97b5164a217d569d1cf8622b2a522e/numba/typing/typeof.py#L49) so that value can specify their numba type.

In the JIT classes PoC, I added a fastpath to the compute_fingerprint that looks at _numba_type_ and uses it to generate the fingerprint.

**Comment by pitrou** [comment]
I think this can be closed now.
