### ISSUE TITLE
problem of specifying variable types in numba function

### ISSUE THREAD

**Issue by wwtian** [numba/numba#1836]
Hi,

My code is:

```python
import numpy as np
import numba
from numba import jit

#return two zero vectors with length n
@jit(numba.typeof((np.array([1.0]),np.array([1.0])))(numba.int_),nopython=True)
def test_func(n):
    x=np.zeros((n,),dtype=np.float64)
    y=np.zeros((n,),dtype=np.float64)
    return x,y
```

This code is OK for numba 23.0. But after updating, I get the following error message:
```
Failed at nopython (nopython mode backend)
Internal error:
ValueError: Operands must be the same type, got (i64, i32)
File "<ipython-input-6-597ea3ed4e48>", line 8
```

I found that the code is fine if I replace "numba.int_" with "numba.int64" or "numba.typeof(1)", but failed with "numba.int32".

So what's the problem? And what is the best way if I want to specify the variable type of n.

Thanks!

**Comment by seibert** [comment]
The best approach is to not specify types, so that the automatic JIT will select the correct ones.  However, if you need to specify all the types, then using `typeof()` is probably the safest approach.

Also, are you using a 32-bit OS or Windows?  According to the NumPy docs, `int_` should be the same as the C `long` type, but not necessarily the same as the Python `int` type.  The only place these should differ is on a 32-bit system, or on Windows, which uses `int32` for C `long`, but Python ints are still 64-bit.

**Comment by wwtian** [comment]
I see. Thanks.

In addition, is there any difference between efficiency of the JIT function with specifying types and that without specifying?

**Comment by pitrou** [comment]
> In addition, is there any difference between efficiency of the JIT function with specifying types and that without specifying?

At best, none. At worse, your specification will be suboptimal and the JIT function without specification will be faster.

**Comment by wwtian** [comment]
Surprising! Thanks.

**Comment by seibert** [comment]
The major difference between specifying types and not is when compilation happens.  If you give explicit types, compilation happens when the `@jit` decorator is executed (import time for functions at global scope), whereas without types, the compilation happens when the function is first called.

Also worth noting that when you don't give the type signature, Numba will automatically create a specialized version of the function for each set of types the function is called with.  So if you have a function you use with float32 and float64 arrays, Numba will generate separate code for both options and dispatch to the correct one at call time.

**Comment by seibert** [comment]
Closing, as I think this has been resolved.
