### ISSUE TITLE
A serious performance pitfall with set in nopython mode 

### ISSUE THREAD

**Issue by leomcc** [numba/numba#1913]
The following code takes a rather long time (does not finish in a few minutes). I am using 0.26

```
@jit(nopython=True)
def test():
     x=set([1])  
     for i in range(1000):  
        x.add(5)  
        x.discard(5)  
test()


```

In contrast,
```
@jit(nopython=True)
def test():
    x=set([1])
    for i in range(1000):
        x.add(5)
test()

```

takes  12.6 µs per loop in ipython.
```
@jit(nopython=True)
def test():
    x=set([1])
    for i in range(1000):
        x.discard(5)
test()


```
takes 10.7 µs per loop in ipython.

Finally,
```
def test():
    x=set([1])
    for i in range(1000):
        x.add(5)
        x.discard(5)
test()


```

takes 144 µs per loop in ipython.

So what is going on here?

**Comment by seibert** [comment]
@pitrou: Can you take a look at this?

**Comment by pitrou** [comment]
Ok, it's not a performance issue, it's a bug in the key insertion logic in the face of deleted entries. Thank you for reporting this, we will be submitting a fix soon.

**Comment by leomcc** [comment]
Hmm, thanks for your prompt response. Numba is a great package. Btw, Is there any technical reason that strings are currently not supported in nopython mode? Does the development team have plans to support strings and dictionaries (in nopython mode) in the future?

**Comment by seibert** [comment]
For strings, the only limitation is effort to implement the required operations.  We've been focusing on other use cases, but strings are eventually on the todo list.

Dictionaries in nopython mode are more challenging because passing a dictionary into a nopython mode function requires us to unwrap it, but then also ensure changes to the dictionary are visible when the function returns.  Our recent additions of support for lists and sets were an attempt to see how feasible this was with simpler mutable data structures.  It seems to have gone well, and I agree that dictionaries are hugely useful data structures, so you will probably see support in the future, but I don't know when.
