### ISSUE TITLE
NumPy array "order" cannot be specified in nopython mode

### ISSUE THREAD

**Issue by jzwinck** [numba/numba#1971]
I tried this in a `nopython` function:

    np.empty((10,3), order='F')

It failed:

```
Traceback (most recent call last):
  File "numba/typeinfer.py", line 114, in propagate
    constraint(typeinfer)
  File "numba/typeinfer.py", line 317, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "numba/typeinfer.py", line 344, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "numba/typing/context.py", line 125, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "numba/types/functions.py", line 49, in get_call_type
    sig = temp.apply(args, kws)
  File "numba/typing/templates.py", line 216, in apply
    sig = typer(*args, **kws)
TypeError: typer() got an unexpected keyword argument 'order'
```

I expected it to work.

**Comment by pitrou** [comment]
Indeed, the `order` argument to various Numpy functions isn't supported. I realize we haven't documented this limitation everywhere.

**Comment by jzwinck** [comment]
Quite.  In 2.7.2 of the docs (http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#array-types) it says:

> Numpy arrays of any of the scalar types above are supported, regardless of the shape or layout.

So...maybe any layout is supported if you pass it in, but not if you want to create one.

And `empty()`, `ones()`, etc. are documented (http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#other-functions) with links to the NumPy docs, which of course say they support `order`.

Being able to support order is important for performance in some use cases.  If the only reason not to support it is the fact that it's a string argument (and Numba doesn't do strings), perhaps an interim alternative can be devised.

**Comment by pitrou** [comment]
Yes. There's a workaround, admittedly silly-looking but functional, though:
```
np.empty((3, 10)).T
```

**Comment by seibert** [comment]
The limitation unfortunately not just about strings.  This category of problem arises because the type of the return value from the `np.empty` function depends on the *value* of the `order` argument, and not just the type of the `order` argument.  Numba treats C and FORTRAN layout arrays as different types for code-generation purposes, so our type inference needs to know the difference at compile time if possible.

We have worked around this kind of issue for specific situations (like usage of string constants to index fields in a structured dtype), but don't have a general solution to all versions of this problem yet.
