### ISSUE TITLE
Write NBEP on current type inference algorithm and proposed enhancements

### ISSUE THREAD

**Issue by seibert** [numba/numba#2080]

**Comment by datnamer** [comment]
Is this still planned? Will it help with things like closures and inlining more complex data types??

**Comment by sklam** [comment]
@datnamer

This is happening.  The NBEP to describe the current type inference algorithm is merged.   I have  in-progress proposed enhancements for functions that have untype-able branches (due to, e.g. `if isinstance(...)`).  

Things like closures are more complicated and we haven't come up with a good solution for them.

**Comment by datnamer** [comment]
It sounds like closures are planned at some point, which is very helpful. Can the same be said for inlining methods and functions taking complex composite datastructures? How about generic and immutable classes ? This is less a feature request and more eliciting roadmap that is helpful for some planning.

**Comment by stuartarchibald** [comment]
Closing, for reference https://numba.readthedocs.io/en/stable/proposals/type-inference.html is the NBEP.
