### ISSUE TITLE
All non-typing exceptions should direct user to file a Github issue

### ISSUE THREAD

**Issue by seibert** [numba/numba#2113]
Exceptions, aside from TypingErrors, almost certainly indicate a bug in Numba.  These exception should include a message telling the user to report a bug to the Numba issue tracker.

**Comment by stuartarchibald** [comment]
Thanks for raising this. Numerous error handling enhancements have been made since this ticket was opened. They are here: https://github.com/numba/numba/blob/b8cb1a8515310054062cdb5d39f110d386eed817/numba/core/errors.py#L333-L416 and categorised through this dict https://github.com/numba/numba/blob/b8cb1a8515310054062cdb5d39f110d386eed817/numba/core/errors.py#L411-L416 for ease of use throughout the code base. Closing as resolved.
