### ISSUE TITLE
Advanced Indexing in 2nd dimension

### ISSUE THREAD

**Issue by chris-b1** [numba/numba#2157]
This raises a decent error message, but presumably could/should be implemented and I didn't see an open issue.

``` python
numba.__version__
Out[153]: '0.29.0'

from numba import njit
@njit
def f(arr, indexer):
    return arr[0, indexer].sum()

f(np.array([[1., 2., 3.], [4., 5., 6.]]), np.array([0, 1]))
<snip>
    raise NotImplementedError("only one advanced index supported")
numba.errors.InternalError: only one advanced index supported
[1] During: typing of intrinsic-call at <ipython-input-147-44d09cdea241> (3)
--%<-----------------------------------------------------------------
```

In my case I wanted a contigous slice, so a workound is:

``` python
In [154]: f(np.array([[1., 2., 3.], [4., 5., 6.]]), slice(0,2))
Out[154]: 3.0
```

**Comment by pitrou** [comment]
For the record, slicing should also be faster than advanced indexing (slicing creates a view while advanced indexing creates a copy).

**Comment by SumNeuron** [comment]
Can we get some traction on this?

Honestly, having tried to do simple things in nopython mode at this point if feels more like a gamble of whether or not the code will work due to non-implementation errors.  I understand the limits of a small team, funding, time constraints, etc. However, if a main feature of `numba` is numpy arrays, then core features of numpy arrays should be prioritized higher (e.g. `axis` optional argument in all np functions) especially as on your website it is stated that `numba` is supposedly simpler than `cython`

**Comment by seibert** [comment]
We need to do some refactoring across a number of our older NumPy function implementations, and one of our requirements should be making it easier to have axis support across functions.  Thanks for adding your feedback on this issue.

**Comment by Nathan-Furnal** [comment]
Same as @SumNeuron, I'd like to be able to slice arrays in my function in ``nopython`` mode !

Thanks for the good work!

**Comment by kc611** [comment]
Support for indices with more than one dimension for arrays is now being tracked at https://github.com/numba/numba/issues/8616.

Hence we can close this particular issue as a duplicate.
