### ISSUE TITLE
basic nested function support

### ISSUE THREAD

**Issue by sklam** [numba/numba#2168]
related to #2095 

Restrict to cases where the inner function never leaves the outer one.  The inner function may read variables in the outer function.

Example:

``` python
def foo(a, b):
    def bar(c):
        ... # may read b
    dosomething(bar, a)  # which calls bar(a)
```

This also requires the ability to pass function object as argument.

**Comment by ninegua** [comment]
Here are two use cases:

``` .python
from numpy import *

def test1(A, threshold):
  def f(x):
    if x < threshold:
        return x * x
    else:
        return x * 2
  return vectorize(f)(A)

def test2(A, threshold):
  return array([ x * x if x < threshold else x * 2 for x in A ])

A = arange(-3,3)
print(A)
print(test1(A, 0))
print(test2(A, 0))
```
In `test1`, the inner function is used together with Numpy's `vectorize` call. Doing the same with Numba's `@vectorize` would require pulling out the function `f` to top-level and passing environment variables (`threshold` in this case) as parameters, which is extra hassle.

In `test2`, instead of naming an inner function, a comprehension is used instead. Believe it is equivalent to creating an inner function. It'll be great if Numba can support this common usage pattern: `array([... for ... ])` and produce a ufunc directly.

Both examples satisfy the following conditions, which I think can be a reasonable starting point to adding inner function support to Numba:

1. The inner function is not being returned (or called) outside its lexical scope.
2. The inner function accesses environment variables as read-only.

A welcome first step would be to let inner functions/comprehensions simply pass through as part of Numba IR, and throw an exception if by code generation stage they still remain in the IR. The hope is that somewhere in the pipeline they will be either processed (and turned into ufunc), or inlined away. What do you think? @sklam @DrTodd13

**Comment by seibert** [comment]
I think we can close this now, @sklam?
