### ISSUE TITLE
JIT Target='paralell'

### ISSUE THREAD

**Issue by arita37** [numba/numba#2183]
Hello,

Just wondering why @jit()  decorator does not have target='paralell', but only target='cpu'
It sounds that only @vectorize has this property.
Thanks

**Comment by seibert** [comment]
This is because Numba cannot do the function analysis required to infer thread-based parallelism from a generic `@jit` function.  Since `@vectorize` creates a ufunc, the parallelism is explicit (every element of the output array can be computed independently), so we can assign threads to compute different chunks of the output array.

For multithreading within a `@jit` function, we've had requests for OpenMP-like directives, either something like the old prange functionality (#2087) or something more like what [GT-Py](https://software.intel.com/en-us/blogs/2016/03/22/gt-py-accelerating-numpy-programs-with-minimal-programming-effort) does.  We are interested in both of these approaches, but haven't had time to pursue them.

**Comment by arita37** [comment]
Hello,

Understood,this is the embarrassing paralell problem for loop.

**Comment by seibert** [comment]
Closing now that ParallelAccelerator exists.
