### ISSUE TITLE
bug with uint32s and ranges

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#2194]
I found a weird bug that prevents the following code from running:
```
import numba
import numpy

@numba.jit(nopython=True)
def broken():
    V = numpy.empty(1)
    s = numpy.uint32(1)

    for i in range(s):
        V[i] = 1
    for i in range(s, 1):
        pass

>> broken()

numba.errors.InternalError: unsupported array index type float64 in [float64]
```
Things that will make the bug disappear:
- remove either loop
- replace the ``V[i] = 1`` with a ``pass``
- set s to a int64 instead of a uint32
- replace ``range(s, 1)`` with just ``range(s)``

**Comment by seibert** [comment]
Ah, I suspect this is a bad interaction with our type casting rules, which is causing the `uint32` to be cast up to a `float64`, which Numba doesn't support for array indexing.

@sklam: Any ideas what is going wrong in typing?  Is it the `range(s, 1)` doing arithmetic between a signed and unsigned int?

**Comment by sklam** [comment]
There is an interesting interaction with variable scoping and the coercion of mix-signedness.  

The cause is that the current scoping logic thinks that both ``i`` from the two loops are in the same scope.  The 1st loop sets type of ``i`` to uint64.  The 2nd loop sets type of ``i`` to int64.  As a result, ``i`` is coerce(uint64, int64)->float64 (due to numpy).   The real fix is to improve the scoping so that the two ``i`` create different scopes.

The simplest workaround is to use a different variable name in the 2nd loop.

**Comment by sklam** [comment]
This makes me wonder if we need the unsigned integer version of ``range()``.  Dropping the unsigned overloads would suppress the issue here and it doesn't affect any tests.

**Comment by xgdgsc** [comment]
I' m getting an error `numba.errors.InternalError: unsupported array index type ?int64 in [?int64]` with one array from some dataframe.values. I don' t know what this means.

**Comment by xgdgsc** [comment]
My error is because I declared the index as `None`, switching to an int solves this. Document here in case someone get same issue through search.

**Comment by vickorian** [comment]
@xgdgsc I'm having the same error when pulling from a numpy array. How did you fix it again? Did you pull the value and then cast as int? For example ind = int(arr[i])? This is not working for me with nopython=True.
