### ISSUE TITLE
Update to LLVM 3.9

### ISSUE THREAD

**Issue by seibert** [numba/numba#2231]
This mainly depends on llvmlite.

**Comment by msyriac** [comment]
Hi, I'm including Numba 0.30.1 as a dependency in a package I'm putting together. Currently Numba will not compile if llvm is >3.8 (pip fails). Does this mean that my package installation is guaranteed to fail on a system where numba is not installed and llvm is >3.8? Is there a workaround?

**Comment by mabl** [comment]
numba is tied to llvmlite which in turn is specific to the llvm version. Typically, it is easier for users to just use a Python distribution like Anaconda, which takes care of matching the libraries.

However, your are in luck, since recently the code emerged to run on llvm 3.9. llvmlite support is in master and there is a pull request for numba merged 30minutes ago. This should work:

```
pip install git+https://github.com/numba/llvmlite.git
pip install git+https://github.com/numba/numba.git
```

**Comment by seibert** [comment]
As a general note, LLVM makes incompatible API changes with every release, so it is generally a bad idea to rely on the system provided LLVM anyway.  Conda really is the best option at the moment, though we are also looking into making wheels for llvmlite (which statically links to LLVM when it is built).

**Comment by seibert** [comment]
Support for LLVM 3.9 is now on master.
