### ISSUE TITLE
llvm4.0 and SVML

### ISSUE THREAD

**Issue by sklam** [numba/numba#2264]
llvmlite PR for llvm4: https://github.com/numba/llvmlite/pull/238 (no changes required in numba)
LLVM PR for SVML: https://reviews.llvm.org/D19544
Interesting lines in llvm to enable SVML:
* https://github.com/llvm-mirror/llvm/blob/release_40/include/llvm/Analysis/TargetLibraryInfo.h#L91
* https://github.com/llvm-mirror/llvm/blob/release_40/lib/Analysis/TargetLibraryInfo.cpp#L26

**Comment by RoyiAvital** [comment]
Just a question.
If I have Anaconda Distribution (Directly from Anaconda) does my Numba use Intel SVML by default?
Namely are all required dependencies for Numba to utilize SVML are built in in the Anaconda Distribution?
Is it ON by default?
Does it hold for Windows, macOS and Linux?

Thank You.

**Comment by seibert** [comment]
SVML requires the presence of the ICC runtime, which Numba autodetects.  (I believe the `numba -s` command now has a block indicating whether SVML is detected.)

On Windows, Anaconda ships the ICC runtime by default because we use Intel's Fortran compiler, on Linux and Mac, it is not present by default.  The documentation here tells you how to install it and which flags do what:

http://numba.pydata.org/numba-doc/dev/user/performance-tips.html

At some point in the future, we will probably make SVML a default dependency in Anaconda once LLVM accepts the related patches.

**Comment by RoyiAvital** [comment]
When I do `numba -s` on my system (Linux Mint 18.3 + Anaconda 5.2) I don't see it looks for SVML.

Why can't be `iic_rt` be on the official Anaconda Channel and it is only on the Numba channel?
It would be great to have option to install Numba + ICC Run Time from the official channel.

By the way, does the ICC RT assists with anything more other than SVML?

Thank You.

**Comment by seibert** [comment]
We haven't made the SVML support default because it relies on Intel patches to LLVM which have not been accepted upstream by LLVM, and because we want more time to confirm that the SVML support doesn't cause problems for end users.  We have to be fairly conservative and slow moving to ensure we don't break people's applications.

Regarding your update: Can you open a new issue about failing to detect SVML and paste the output of `numba -s` into that issue?

**Comment by RoyiAvital** [comment]
I can see the logic in being conservative and taking things slowly.
Hopefully soon SVML will be out of the box on all systems when one installs Numba.

Do you mean you use special build of LLVM with those Intel Patches in order to use SVML?
I have Numba `0.38`, Is that a bug in 0.38 or the SVML display in `numba -s` is only `0.39` feature?

**Comment by seibert** [comment]
If you are using the llvmlite wheels or the conda packages of llvmlite from the numba channel or Anaconda, LLVM has already been patched for you.  You only need to patch LLVM if you build llvmlite yourself from source.

SVML support was added in in 0.38, but I would strongly suggest 0.39 because there were some bugs discovered that were fixed in 0.39.  And now that I look, SVML diagnostics  in `numba -s` was also added in Numba 0.39.

**Comment by stuartarchibald** [comment]
Can we close this as Numba has SVML support since 0.38?

**Comment by RoyiAvital** [comment]
@seibert , I updated to `0.3.9` and it seems all is working.
I hope you'll get the needed patches in LLVM accepted and we all will have SVML out of the box.

**Comment by stuartarchibald** [comment]
Closing as SVML has been successfully supported for 6 releases.
