### ISSUE TITLE
@jit decorator should support PEP 3107 function annotations, if present

### ISSUE THREAD

**Issue by kernc** [numba/numba#229]
An idea. Since [PEP 3107](http://www.python.org/dev/peps/pep-3107/) in Python3+ is intended to "encourage experimentation through metaclasses, decorators or frameworks," perhaps this is the way to go, function-annotation-wise?

**Comment by datnamer** [comment]
Any new thoughts on this? @seibert

**Comment by pitrou** [comment]
[PEP 484](https://www.python.org/dev/peps/pep-0484/) is not compatible with Numba's type granularity. We could of course allow our own annotations, but I'm also not sure what that would bring. Generally it is recommended to let Numba infer the types of function arguments, rather than annotate them yourself.

**Comment by datnamer** [comment]
Gotcha.

**Comment by datnamer** [comment]
I was doing some thinking and thought that type hints would be useful to add some type safety and perhaps even expose a normal user facing overload/multi methods interface.

Even in normal python we have this: https://github.com/mrocklin/multipledispatch
