### ISSUE TITLE
Support np.trace at nopython mode

### ISSUE THREAD

**Issue by romeric** [numba/numba#2314]
The following snippet fails at `nopython` mode:

```python
@jit(nopython=True)
def test():
    c = np.linalg.matrix_power(np.random.rand(10,10), 4)
    return np.trace(c)
```

with the error message:

```shell
Failed at nopython (nopython frontend)
np.trace() only supported for array types
[1] During: resolving callee type: Function(<unbound method OverloadTemplate_trace.trace>)
[2] During: typing of call at <ipython-input-37-ebf534a41ae3> (4)
```
I believe `np.trace` was added recently in #2175.

**Comment by stuartarchibald** [comment]
@sklam did you open a PR for this? I think that patch in https://github.com/sklam/numba/commit/ff16fa08a0e100a8e30f5b495e4de9101ac5a3f2 is valid. Wondering if we should add a test or two for `np.linalg` functions where the return type ends up as `Optional`?

**Comment by stuartarchibald** [comment]
@romeric thanks for the report, the problem is that `np.linalg.matrix_power` is returning an `Optional` type due to some changes in internal implementations elsewhere in Numba. The type checking code in the `np.linalg` replacement code is quite strict and hasn't been adjusted to accommodate `Optional` (it's what @sklam's patch fixes), when this is in it will work as expected.
