### ISSUE TITLE
Create special LLVM builds for testing with various sanitizers enabled

### ISSUE THREAD

**Issue by seibert** [numba/numba#2462]
A number of projects that use LLVM also run their tests suites with ThreadSanitizer or MemorySanitizer enabled.  This significantly slows down the performance of LLVM, so it can't be our default build, but it would be very helpful to be alerted to hard-to-detect problems during automatic testing.

As a spin-off, we might see if these tools could be enabled optionally in jitted code as a testing tool for users.

**Comment by seibert** [comment]
ping @sklam @ovillellas @stuartarchibald

**Comment by stuartarchibald** [comment]
I've done the background research into this. As a quick summary...

There's 3 things:

1. Build llvmlite/Numba internal DSOs with some sanitizer flags enabled in GCC.
2. As 1. but also build LLVM itself with some sanitizer enabled, this would then be linked into llvmlite.
3. As 2. but also add santizer passes to the compilation process performed when jit-ing code with Numba.

There's four main sanitization options of note, address, thread, memory, and leak.

I tested out address and thread as these worked ok from the tool chain I had available (didn't want to deviate too much from Centos 6, with which Numba currently builds).

Taking these in turn.
1. Works. Tests in llvmlite and Numba all pass with the exception of tests which call out to GCC (e.g. AOT compilation tests), these segfault, probably due to e.g. `LD_PRELOAD`ed `libasan.so` supplanting unexpected variants/symbols. Other tests that fail are those with the thread sanitizer enabled, something suspicious happens with `mp.queue.fork`, it seems it is not an actual problem, just something that can't be tracked at present.
2. As 1. Works with same caveats.
3. The tool chain of a custom LLVM as an llvmdev build, plus llvmlite and Numba built with additional options is quite complicated already, which makes adding in additional (and conditionally compiled) code quite hard. There's no C API exposed for the sanitizer passes in the compiler-rt or LLVM (as far as I could see, with the exception of in the Go-lang bindings). Using the Go-lang bindings C API, the passes can be added into llvmlite in the C and Python layers, the DSO compiles ok but fails to link. There may be a better way of doing this.

Suggested future work.
1. Build llvmdev/llvmlite/Numba package variations with the various sanitizers enabled.
2. Once the packages are made revisit 3 with this more stable base.

Perhaps it's best move this out of the 0.35 Milestone and to 1.0 instead?

**Comment by stuartarchibald** [comment]
Moving this out of 0.35.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
