### ISSUE TITLE
add np.take (and corresponding index array) support

### ISSUE THREAD

**Issue by seibert** [numba/numba#2466]
This should not be too hard to add in the 1D case, and higher dimensional cases may not be too much worse.

**Comment by seibert** [comment]
(Request from librosa developer)

**Comment by bmcfee** [comment]
A bit more context on this one:

I did a quick-skim audit of librosa, and one of the major hurdles to adopting numba is read-only access to subsets of an array when applying pooling operators.  (Think of replacing a column of a matrix by the element-wise average of its neighboring columns.)  This doesn't require full fancy indexing, since we can get a read-only temporary array from `np.take`.

Similarly, this might help unblock some of the issues with implementing sparse matrix ops, since `np.take` can be used to access the underlying data buffer of a compressed sparse matrix.

**Comment by seibert** [comment]
Do you need the `axis` or `mode` arguments to `np.take`?

**Comment by bmcfee** [comment]
I don't personally, no.  I can usually get around the `axis` dependency by wrapping `swapaxes(0, axis)` around the input and output of the function in question.

`mode` hasn't come up for me, largely because my `take` arguments tend to be valid indices (no negatives), so I never need to wrap or clip.  But YMMV.
