### ISSUE TITLE
"dynamic" Numba type

### ISSUE THREAD

**Issue by seibert** [numba/numba#2472]
(Capturing a discussion I had with @sklam:)
## General Idea

We have been trying to find a good solution to the general problem of combining compiled and interpreted code in a "nopython" mode function.  We obviously can't make that kind of mixed usage fast, but there are lots of use cases for working with Python objects (including other python functions) where the speed of the Python interpreter calls would not matter.  Example: Calling a Python function callback to update a plot every N iterations of an optimization algorithm.

We've talked about a few different approaches, such as introducing a context manager:
``` python
def do_stuff(x, y, callback):
    ...
    with numba.python_mode:
        callback(intermediate_results)
    ...
```
or perhaps allowing a nopython mode function to specifically call a python mode function with some special syntax.

However, the approach we discussed today was to create a special `dynamic` type.  All operations on a `dynamic` type are sent to the Python interpreter and result in a value of type `dynamic`.  For each operation on a dynamic type:
  1. Acquire the GIL (if `nogil=True`)
  2. All values in the operation must have the dynamic type.  If a user wants to use a statically-typed value (like an int, or a float64 ndarray), they must explicitly cast it to dynamic type with `to_dynamic()`.
  3. Perform the operation (call a function, get attribute, etc)
  4. The return value is treated as a dynamic type (*and not unboxed*).
  5. Release the GIL (if `nogil=True`)

If a return value of dynamic type needs to be used in nopython mode, it will need to be explicitly cast back to another static type.  This will result in a runtime check (which can raise an exception) and a call to the unboxing function at that point in the code.

## Example

``` python
@numba.jit(nopython=True, allow_dynamic=True)
def update_state(state, n_iter, plot_callback):
    for i in range(n_iter):
        # update state
        ...
        # update plot
        if i % 1000 == 0:
            plot_callback(numba.types.to_dynamic(state))
```

``` python
@numba.jit(nopython=True, allow_dynamic=True)
def update_state(data_table, observations, mapping_dict):
    for o in observations:
        python_index = mapping_dict[numba.types.to_dynamic(o)]
        data_table[int(python_index)] += 1
```

## Possible issues

* Because of the possible adverse performance effects of someone using dynamic objects, this should be an opt-in feature. We should not automatically allow it in `nopython` mode.  This motivates the addition of an `allow_dynamic` flag.
* As a convenience, we can automatically make incoming arguments and global values of unknown types into a `dynamic` type.
* A sequence of operations on dynamic types should only acquire and release the GIL once.  This could be treated as an optimization handled in a rewrite pass.

**Comment by seibert** [comment]
Edit: Renamed "bypass" => "dynamic", which sounds better.

**Comment by seibert** [comment]
Edit: Renamed `to_python()` => `to_dynamic`

**Comment by ehsantn** [comment]
This feature is great to have! Can we have both of the approaches available?

**Comment by seibert** [comment]
When you say both approaches, do you also mean having a context manager that automatically casts values to `dyanmic` type inside so you don't have to explictly cast with`to_dynamic()`?

**Comment by ehsantn** [comment]
Yes, context manager would be a little more convenient sometimes I think.

**Comment by complyue** [comment]
I'm in real needs of such functionalities, to have logic run mostly in nopython mode but occasionally switch to interpreter to access machine learning, statistics, etc. those not available in nopython mode yet, then resume nopython context for performance.

Currently I've figured out a design pattern I call it `HYPER INVOKE` like below, but the purposed facility in this issue is much more superior and flexible than mine, so I hope the idea goes mature and get into numba sooner!

```python
import asyncio

import numba as nb
import numpy as np


async def online_process(sprint_func, survey_func, chunk_pumper, clt_shared):
    """
    Generalized nopython/python mode mixed processing

    Parameters
    ----------
    sprint_func: nopython mode function
    survey_func: python mode function
    chunk_pumper: streaming data provider
    clt_shared: shared computation lifetime data

    Returns
    -------
    None

    """

    while True:

        # get data chunk from streams
        chunk = await chunk_pumper()
        if chunk is None:
            break

        for hyper_fact in sprint_func(chunk, clt_shared):
            survey_func(hyper_fact, chunk, clt_shared)


@nb.jit(nopython=True, nogil=True)
def sprint_compute(chunk, clt_shared):
    state, n_iter, kk, mm = clt_shared
    for i in range(n_iter):
        # update state wrt current params in kk/mm
        pass
        if i % 1000 == 0:
            # I call this yielding `HYPER INVOKE` ;-)
            # to have kk/mm updated by interpreted code
            yield i


def survey_params(iter_i, chunk, clt_shared):
    state, n_iter, kk, mm = clt_shared
    # update kk/mm wrt state for iter_i-th iteration
    print('param calibration @', iter_i, '/', n_iter)
    # here to update plot as well
    pass


async def read_stream():
    # end of stream check
    eos = (1 == 0)
    if eos:
        return None

    # simulate stream flowing
    await asyncio.sleep(1)
    return np.random.random((50,))


state = np.random.random(10)
kk = np.zeros(5, np.intp)
mm = np.ones(7, np.float64)

asyncio.get_event_loop().run_until_complete(
    online_process(sprint_compute, survey_params, read_stream, (state, 5000, kk, mm))
)
```

**Comment by complyue** [comment]
I've read the numba call for examples, and sort of think the `hyper invoke` design pattern worth to be an example there, as it does work on current numba release out-of-the-box, while I see no other doable equivalent. But I have limited time/energy to dive into number-examples project right now, so that's not happening too soon.

**Comment by complyue** [comment]
I recently came across some R stuff, and surprisingly found that Rcpp is already fluent at the equivalent for R: [Calling R Functions from C++](http://gallery.rcpp.org/articles/r-function-from-c++/). Though at the first glance Cython may seem more comparable to Rcpp in this sense, when [Rcpp Sugar](http://adv-r.had.co.nz/Rcpp.html#rcpp-sugar) as the Numpy rival is considered, Cython just fades out and Numba comes up as only eligible way at serious *Number Crunching* . Rcpp has even encapsulated some heavy lifting C++ libs like [RcppArmadillo](http://dirk.eddelbuettel.com/code/rcpp.armadillo.html) and [RcppEigen](https://github.com/RcppCore/RcppEigen), as well [A thin wrapper of Intel TBB](https://github.com/RcppCore/RcppParallel), with dual interface meant to be called either from R or C++.

I'd confess that I'm tempted to re-implement my massive backtesting framework to be based on Rcpp + bigmemory, as R lacks a GIL to release (GIL just protects python objects from threading in a simple but sufficient way), threaded R can't be trivial to implement, but with the help of bigmemory, mem sharing across multi-processes is solution fits my needs better (I'd rather constrain a single task to single cpu since there're massive tasks with equal priority). I currently running those tasks with multi-threaded (nogil) Numba NPM generators those occasionally yield to trigger some interpreted python code, and with NPM generator mem leak issue unsolved, I'm quite limited at scale and throughput.

I would say that after seeing Rcpp's philosophy regarding performance calling back to R:

> But before we proceed, a warning. Calling a function is simple and tempting. It is also slow as there are overheads involved. And calling it repeatedly from inside your C++ code, possibly buried within several loops, is outright silly. This has to be slower than equivalent C++ code, and even slower than just the R code (because of the marshalling of data). *Do it when it makes sense*, and not simply because it is available.

the "dynamic type" might not add much regarded value compared to the (imho) simpler boxing/unboxing implementation (I assume context manager syntax just do that), because interpreter is already slow, for a scenario in which performant code calling slow interpreter code makes sense, it should still make sense for it to be a little more slower.

**Comment by complyue** [comment]
I guess `object` can be added as allowable type in auto/manual signature spec, then those corresponding args can and only can be called/accessed via Python C api, within scope of the context manager ?

**Comment by datnamer** [comment]
what about incremental compilation ?

**Comment by complyue** [comment]
I just realized that facility here once implemented, Numba enabled Python will be par to Julia in sense of **multiple dispatch**. To my understanding, Numba and Julia are both **dynamic multiple dispatch**, but currently Numba is **switch-time** (i.e. from interpreter to NPM) multi-dispatch, while Julia is **per-call** multi-dispatch, since Numba settles all machine code to run at the switch from OM to NPM, once in NPM, no func signature based dispatch will occur.

**Comment by seibert** [comment]
OK, now that @sklam is starting to work on this, we have more specific ideas on the syntax and limitations of the first version of the feature.

Initially, this will behave a lot like loop-lifting, but for code inside a context-manager block.  (@sklam is using the short-hand term "with-lifting.)  The main constrain on this feature (at least in Numba 1.0) is that type inference still needs to be able to fully type all statements in the nopython mode sections of the function at compile time, regardless of what happens inside the python mode blocks.

Here are some examples of what we're proposing, with commentary:

### Example 1: Objects become allowed if you don't use them in nopython mode
``` python
# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
  return x

# Not allowed:
@numba.jit(nopython=True)
def foo(x, obj):
  return obj.method(x)
```
Unlike the original proposal in this issue, users do not have to opt-in to this behavior with a special `@jit` argument.

### Example 2: Entering object mode
``` python
# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    with numba.object_mode():
        obj.method(x)
    return x

# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    with numba.object_mode():
        temp = obj.method(x)
    # temp is never used again in the method
    return x
```
Before executing the code inside the object mode block, the Python GIL will be reacquired, and any nopython mode values (like `x`) in the above example will be boxed in the appropriate Python object type (as if they were returned from nopython mode).

### Example 3: Changing the values of function local variables in object_mode
``` python
# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    y = 5
    with numba.object_mode():
        y = obj.method(x)
    # y will continue to have int64 type
    return y

# Not allowed Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    y = 5
    with numba.object_mode():
        y = [obj.method(x)]
    # Exception will be raised when leaving the object mode block,
    # since y has changed from an int64 type to a list type
    return y
```
Values that leave an object mode block will be unboxed, but with the runtime constraint that they cannot change types (except as shown below).

### Example 4: Indicating the types of new identifiers or type changes
``` python
# Not allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    with numba.object_mode():
        y = obj.method(x)
    # Numba does not know the type of y at compile time
    return y

# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    with numba.object_mode(y='int32'):
        y = obj.method(x)
    return y

# Allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    y = 5
    with numba.object_mode(y='float32'):
        y = obj.method(x)
    # After this block, y has switched from int64 to float32 data type
    return y
```
Keyword arguments to `object_mode` will give the types of variables that cannot be inferred at compile time.  This is only necessary for new identifiers or in cases where the type is different from what it was before the block.

### Example 5: Code inside `object_mode()` really is Numba's object mode
``` python
# Not allowed:  foo is called with x->numpy array, obj->untyped Python object
@numba.jit(nopython=True)
def foo(x, obj):
    y = 5
    with numba.object_mode():
        try:
            y = obj.method(x)
        except:
            y = 0
    # This will not compile because we do not support try/except blocks in object mode
    return y

# Allowed:  foo is called with x->numpy array, obj->untyped Python object
COUNTER = 0
@numba.jit(nopython=True)
def foo(x, obj):
    with numba.object_mode(y='int32'):
        COUNTER += 1
        # global counter will update

    return COUNTER  # !!! THIS WILL RETURN ZERO
    # Numba captures global values at compile time in nopython mode
```

Other notes:

*  Although Numba can `yield` from object mode functions, yielding from an object mode block will not be allowed.  This is not intrinsically impossible, but hard and not worth the effort initially.
* An object mode block can call a nopython mode function (just like any Python function) which can release the GIL again.
* Object mode blocks can be nested inside control flow structures.
* In the Python interpreter (if NUMBA_DEBUG_JIT is set, for example), `numba.object_mode()` will return a do-nothing context manager that simply executes the block.

**Comment by ehsantn** [comment]
Can a compiler pass (either before or after type inference), add an object_mode block to the function?

**Comment by fschlimb** [comment]
Assuming I have my own numba type with lowering, model, unboxing etc., say ```myType```, would I be able to do something like
```
with numba.object_mode(y='myType'):
    y=mysuperpythonfunction()
y += 2
return y
```

Why is the type provided as a string?

**Comment by seibert** [comment]
Yes, what you describe should be supported.  The string type was a shorthand I should have clarified.  In all the user-facing APIs in Numba (for convenience) you can pass types as a string (which is implicitly evaluated in the global namespace of the `numba.types` module) or the actual Numba type object.

**Comment by stuartarchibald** [comment]
This was implemented as described in https://github.com/numba/numba/issues/2472#issuecomment-386451576 in version 0.40.0 (#3166). Closing.
