### ISSUE TITLE
Thread-safe random generator on CPU

### ISSUE THREAD

**Issue by RemiLehe** [numba/numba#2486]
Numba provides a convenient thread-safe random generator **on GPU** through the [`xoroshiro128p` API](http://numba.pydata.org/numba-doc/0.34.0/cuda/random.html).

With the recent availability of `prange`, it would be nice to also have a thread-safe random generator **on CPU**. Does this feature exist in Numba? If not, would it be possible to add a CPU version of `xoroshiro128` ?

**Comment by seibert** [comment]
We certainly could make that code work on the CPU (in fact, it might be 80% of the way there).

However, the CPU RNG in Numba should already be "thread-safe", at least in the same way the RNG in NumPy and Python is thread-safe.  Each thread should have its own local state and unique seed automatically created for you, so different threads do not interfere with each other.

The drawback is that, unlike xoroshiro128p, the seeds for each thread are picked randomly, so they are not guaranteed to be non-overlapping.  (This is a problem for NumPy and Python as well.)  Since the CPU RNG is Mersenne Twister, which has a very large periodicity, it is likely (but not guaranteed) that different sequences are non-overlapping.  With xoroshiro128p, the periodicity is much smaller and the number of threads on the GPU is much bigger, so the seeding function is specifically designed to separate each thread by 2**64 steps in the sequence.

But to summarize: yes, we should look into making the xoroshiro128p RNG available to the CPU.

**Comment by RemiLehe** [comment]
Thanks for your quick answer!

Regarding your remark on the standard CPU RNG: if I consider the code below, does this mean that a separate, indepent seed (and RNG) will be created for each `i` in the `prange` loop? Or for each numba thread (assuming `NUMBA_NUM_THREAD`<10)
```python
from numba import njit, prange
import numpy as np
N = 100
x = np.zeros( 100 )

@njit( parallel=True )
def fill_random( x ):
    """Fills array x with random number"""
    for i in prange( 10 ):
        for j in range( i*(N//10), (i+1)*(N//10) ):
            x[j] = np.random.rand()
    return( x )

fill_random( x )
```

**Comment by seibert** [comment]
Correct, the RNG implementation used by `np.random.rand()` (and all the other functions, incl Python random module) will auto-initialize a different seed on each thread.

**Comment by RemiLehe** [comment]
Great, thanks for the answer! 
It seems that, for my use case, `xoroshiro` is not really needed on CPU. As far as I am concerned, the issue can be closed.

**Comment by wkerzendorf** [comment]
@seibert Is there a way to determine what seed is used during autoinitialization of each thread?

**Comment by mikecroucher** [comment]
@seibert I'm really interested in how to determine, and control, which seeds are used during autoinitialization too.  Important for reproduciblity and also for cases when you want to scale further.

Imagine that I take a monte carlo simulation using jit and prange and I want to run it on 100 nodes of a HPC cluster.  I need to understand how everything is seeded to ensure that I get independent streams across all simulations.
