### ISSUE TITLE
user defined exceptions don't work in python2

### ISSUE THREAD

**Issue by esheldon** [numba/numba#2559]
The following code works in python3 but not python2.  I'm using
numba `'0.35.0+0.g24edca2e0.dirty'` from a fresh install of miniconda
on Oct 9, 2017, on ubuntu

```python
from numba import jit

class MyError(Exception):
    """
    user-defined exception
    """
    def __init__(self, value):
         self.value = value
    def __str__(self):
        return repr(self.value)



@jit(cache=True)
def test_raise():
    """
    test raising an exceptioin
    """
    raise MyError("test an error")

test_raise()
```

In python3 this does as expected
``` bash
> python tnumba.py
Traceback (most recent call last):
  File "tnumba.py", line 21, in <module>
    test_raise()
__main__.MyError: 'test an error'
```

In python2 there is an error
```bash
> python tnumba.py
Traceback (most recent call last):
  File "tnumba.py", line 21, in <module>
    test_raise()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I think this is probably because your user defined exception is not pickleable (and it needs to be to work with Numba).
```python
import pickle as pk

class MyError(Exception):
    """
    user-defined exception
    """
    def __init__(self, value):
         self.value = value

    def __str__(self):
        return repr(self.value)

unpickled = pk.loads(pk.dumps(MyError('some string')))
```
gives:
```
TypeError: __init__() takes exactly 2 arguments (1 given)
```

If you make it such that your exception is pickleable (this is one way):
```python
from numba import jit

class MyError(Exception):
    """
    user-defined exception
    """
    def __init__(self, value):
         super(MyError, self).__init__(value)
         self.value = value

    def __str__(self):
        return repr(self.value)

@jit(cache=True)
def test_raise():
    """
    test raising an exceptioin
    """
    raise MyError("test an error")

test_raise()
```
this gives:
```
$ python issue2559.py 
Traceback (most recent call last):
  File "issue2559.py", line 21, in <module>
    test_raise()
__main__.MyError: 'test an error'
```
Hope this helps.

**Comment by esheldon** [comment]
Thanks, your version does work.

I still wonder why this works in python3.

Also note that the exception I defined is equivalent to the official example given in the python docs, so most people are going to run into the same mistake.

https://docs.python.org/2/tutorial/errors.html#user-defined-exceptions

**Comment by esheldon** [comment]
If you don't mind I'll open a different issue suggesting that the numba docs be updated to say the exception must be picklable

http://numba.pydata.org/numba-doc/dev/reference/pysupported.html

**Comment by stuartarchibald** [comment]
I think it works in Python 3 because the `BaseException_new` call sets the `.args` attr from the arguments to `__new__` https://hg.python.org/cpython/file/3.6/Objects/exceptions.c#l32 whereas in Python 2 it does not https://hg.python.org/cpython/file/2.7/Objects/exceptions.c#l30.

In the example, to quote the docs:

> In this example, the default __init__() of Exception has been overridden. The new behavior simply creates the value attribute. This replaces the default behavior of creating the args attribute.

this reinforces the notion that `.args` is not set.

Given pickle is calling `__reduce__()` https://hg.python.org/cpython/file/3.6/Objects/exceptions.c#l129 the lack of a `.args` in Python 2 leads to it returning `(<some module>.MyError, (), {'value': 'test an error'})` whereas in Python 3 the returned tuple is `(<some module>.MyError, ('test an error',), {'value': 'test an error'})`, by virtue of the difference in set up from `BaseException.__new__`. This means that when the exception is unpickled and its `__init__` is called, there are the correct number of arguments in Python 3 and an incorrect number in Python 2. This also explains why calling the `super(MyError, self).__init__(value)`  in Python 2 fixes it, `.args` will get set by the initialisation sequence of the super class (`Exception`).

**Comment by stuartarchibald** [comment]
Closing this as it was resolved. Thanks.
