### ISSUE TITLE
AOT compilation with numba and pybind11 in visual studio 2017

### ISSUE THREAD

**Issue by MisesEnForce** [numba/numba#2582]
I have this `c++` containing pybind11 binding code :

	#include <pybind11\pybind11.h>
	#include <functional>
	#include <pybind11\functional.h>
	#include <cmath>
	#include "MC.h"

	namespace py = pybind11;

	double MC(const double a, const double b, const std::function<double(double)> &f, const int N)
	{
		double sum = 0.0;
		for (int i = 0; i < N; ++i)
		{
			double x = (b - a) * ((double)rand() / (double)RAND_MAX) + a;
			sum += f(x);
		}
		sum /= (double)N;
		return sum;
	}

	PYBIND11_MODULE(Binder, m)
	{
		m.def("MC", &MC);
        }

and the corresponding `python` code using `numba` :

    import Binder #the name of the .pyd module compiled by the previous c++ code
    from numba import cfunc
    from numba.types import float32

    print("stupid line just to break at")

    @cfunc("float32(float32)")
    def Id(number):
        return number

    sum = Binder.MC(0.0,1.0,Id.ctypes, 100)
    print(sum)

All of this is taking place in visual studio 2017 (with python 3.6.3). `@cfunc` is a decorator telling that the decorated python function `Id` will be AOT (ahead of time) compiled into a `c` function that going to be used after via its address given by `Id.ctypes`. (See [here][1] for details.)

Now, if I put a breakpoint in the python on the line `print("stupid line just to break at") and a breakpoint in the `c++` on in the definition of `double MC(const double a, const double b, const std::function<double(double)> &f, const int N)` I expect, by the AOT compiling, to first break in the `c++` because the interpreter.

But this is not happening. Actually what's happing is the same as if I wouldn't have decorated `Id` with `@cfunc`. What am I not understanding ?

  [1]: http://numba.pydata.org/numba-doc/dev/user/cfunc.html

**Comment by seibert** [comment]
I might not be understanding the question, but the sequence I would expect as Python steps through your file:

* Python breakpoint at`print("stupid line just to break at")` triggers
* The  `Id` function is defined in the Python interpreter, and then passed to the `@cfunc` decorator which compiles it immediately and returns it, replacing the pure Python definition of `Id`.
* `Binder.MC` is invoked, and the breakpoint you put on the C++ function would then trigger.

Is this different than what you are seeing?

**Comment by MisesEnForce** [comment]
Nope. I guess that I just did not understand the concept of ahead of time compilation.

**Comment by seibert** [comment]
I think it helps to distinguish different compilation times a bit more:
* **Function-call time**:  This is the normal mode of `@numba.jit`.  When the Python interpreter calls a Numba-decorated function, the argument types are inspected and if a version of the function for those types does not exist, Numba invokes the compiler at that moment.  (If Numba already has a compiled version of the function in memory for the correct types from a previous call, it dispatches to that instead.)  The benefit of this is that the user does not need to specific types for the function (which are easy to get wrong) when they define it.  The draw back is the first call to the function is much slower, but later calls are much faster.
* **Function-definition time**: This is required for `@cfunc` and is optional for `@numba.jit`.  In this case, the type signature is provided in the decorator and the Numba compiler is invoked at the point where the function is defined.  For the common case where functions are defined globally, importing the module or loading the script takes longer, but the first call to the function is fast.  Because we cannot introspect the argument types when called from C, Numba requires `@cfunc` to  declare the types up front.  We still consider this a "JIT" mode for Numba, however.
* **Ahead-of-time**: We think of AOT as being compilation prior to the current process starting.  Numba has a disk cache of compiled functions that can be used (but is not on by default currently) and also supports creating shared libraries of Numba compiled functions that can be imported as Python extension modules.  (See http://numba.pydata.org/numba-doc/latest/user/pycc.html)  However, this feature currently only works for functions that are going to be called from Python, not from C.  We can certainly improve that, but it's not on our short term roadmap.  For compatibility, AOT shared library compilation often requires compiling for a more generic architecture, which can hurt performance if you happen to be using a CPU with more advanced features (AVX, etc) than the library was compiled for.

So, given all of that, you really only have one choice for `@cfunc`, but you'll be getting the highest performance code that LLVM can generate.

**Comment by MisesEnForce** [comment]
Thank you very much for this thorough explanation, now it is crystal clear to me.
