### ISSUE TITLE
-(0 == 0) returns 65535 in numba (0.35.0)

### ISSUE THREAD

**Issue by yaoyuki** [numba/numba#2624]
I use Python 3.6.0 or 3.6.2 and numba (0.35.0). I checked this example at multiple environments.
The test code shows that -(0 == 0) returns 65535.

I believe this behavior is not consistent with the original python implementation and the fact that  numba returns -1 for -True (see test_use_true() )

```

In [1]: import numba as nb
In [2]: def test():
   ...:     return -(0 == 0)
   ...: 
In [3]: test()
Out[3]: -1

In [4]: @nb.njit
   ...: def test_nb():
   ...:     return -(0 == 0)
   ...: 
In [5]: test_nb()
Out[5]: 65535

In [6]: @nb.njit
   ...: def test_use_true():
   ...:     return -True
   ...: 
In [7]: test_use_true()
Out[7]: -1

```

The code below is my quick-fix.

```
In [2]: @nb.njit
   ...: def test_nb_quickfix():
   ...:     return -1.*(0==0)
   ...: 
In [3]: test_nb_quickfix()
Out[3]: -1.0
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think there are two problems here:
1. That it produces the wrong answer.
2. That `test_nb()` produces an inconsistent wrong answer across repeated runs.

For 2. I think the unary minus call typing is returning a seemingly random inferred type. I'm fairly sure this is because it relies on the definition of `numba.typing.builtins.UnaryNegate` which has signatures assembled from a `frozenset` of types inherited from `UnaryOp`. I think the types need sorting from low to high or at least an iteration order guaranteed. @sklam as this impacts type inference do you have a view?

Once 2. is fixed this would yield a consistent wrong answer.

To fix 1. I think the type signature for booleans needs adding to the `UnaryOp` signature specification and then lowering for `unary negate(bool)`.
