### ISSUE TITLE
An unfinished sentence in types tutorial

### ISSUE THREAD

**Issue by krassowski** [numba/numba#2631]
[This commit](https://github.com/numba/numba/commit/1adf092d39778bf99c451737907aea5f94a99780#diff-5f5edc542696166375c0f18ff35b138bR530) introduced the following sentence to "[Numba types](http://numba.pydata.org/numba-doc/0.12.2/tutorial_types.html#importance-of-type-inference)" documentation:

> A function where type inference is unable to provide a specific type for a value (that is, any type other than the generic *pyobject*).

which clearly lacks a verb. Here is the full context:

> It must be emphasized how important it is type inference in *numba*. A function where type inference is unable to provide a specific type for a value (that is, any type other than the generic *pyobject*). Any function that has a value fallback to *pyobject* will force the numba compiler to use the object mode. Object mode is way less efficient thant the *nopython*.

Edit: Also, the markdown links in CONTRIBUTING.md have some unwanted spaces which makes them misrender on GitHub.

**Comment by stuartarchibald** [comment]
Thanks for the report. The "Numba types" document to which you are referring is a number of years old and refers to v0.12, we just released a RC for 0.36 (docs are [here for the latest released version, 0.35](http://numba.pydata.org/numba-doc/latest/index.html) and [here for the cutting edge, 0.36rc1](http://numba.pydata.org/numba-doc/dev/index.html))! I'm fairly sure that tutorial does not render as part of the current documentation, however, I note there's a notebook of the same at `numba/tutorials/Numba types.ipynb` which does need updating.

Thanks for the note about https://github.com/numba/numba/blob/master/CONTRIBUTING.md, fixed in https://github.com/numba/numba/pull/2633

**Comment by stuartarchibald** [comment]
It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
