### ISSUE TITLE
Default integer size on Windows is 4 byte.

### ISSUE THREAD

**Issue by godaygo** [numba/numba#2643]
From the documentation if no signature for `@jit` is given the decorated function implements lazy compilation. The problem arises from the fact that on Windows `np.int_ is np.int32`.
The minimal example:
``` python
import numpy as np

def range_(max):
    return np.arange(max)  

arr = range_(100)
arr.dtype     # will be dtype('int32')
```

but with jitted version it is int64:

```python
import numpy as np
from numba import njit

@njit
def range_(max):
    return np.arange(max)  

arr = range_(100)
arr.dtype     # will be dtype('int64')
```

Python 3.6.3
numpy 1.13.3
numba 0.35
Windows 10

**Comment by sklam** [comment]
This is an intended behavior.  The function dispatcher will use the largest machine int type instead of picking the minimal int type.  This leads to typing of `range_(intp) => np.arange(intp) -> array of intp`.  Using the minimal type will likely lead to compiling too many version (i.e. one for int8, one for int32, ...)

I noticed a real issue here when I wanted to suggest a workaround.  Numba should support the dtype keyword argument here for user to specify which the dtype to use.  However, our `arange` doesn't support keywords yet.   So, users must use the 4 argument form `np.arange(start, stop, step, dtype)` which isn't pretty.

**Comment by godaygo** [comment]
I apologize for having provided an inadequate example :-) in fact, I meant the following:

```python
import numpy as np
import numba as nb
arr = np.arange(10)
print("Initial: ", arr.dtype)

def npfun(arr):
    arr = arr + np.array([10])
    return arr

print("numpy  : ", npfun(arr).dtype)

@nb.njit
def jitfun(arr):
    arr = arr + np.array([10])
    return arr

print("njit   : ", jitfun(arr).dtype)

#----------------------------------

Initial:  int32
numpy  :  int32
njit   :  int64
```

So it is not typesafe. Yes it is easy to fix in the code by providing `dtype='i4'` but this behaviour is not compliant with `numpy`. FWIW, that in `numpy` the default size for `np.int_` was 8 bytes on a 64-bit system, and not compiler-dependent. But they defined it the same as `long` ... and in VS it is still 4 byte.

I understand that this will add additional costs for the maintenance. But it seems to me that this design choice (8 byte - default for `np.int_`) should be at least noted in the Docs.
