### ISSUE TITLE
cuda.syncthreads()  - most important primitive - not working in some cases

### ISSUE THREAD

**Issue by reneschaub** [numba/numba#2655]
Threads are not waiting as they are supposed to on syncthreads, resulting in reading global memory (also shared memory) before it has been written to.

The attached code snippet is abstracted from several code files to make it as short/simple to read as possible, while still retaining the broken behavior. The reduced/nonsensical statements are only there to reproduce the syncthreads problem, you can ignore everything but the reading and writing of the number 112211, the other statements shouldn't impact that.

Basically, threads 14-20 are skipping some logic, but are supposed to wait for the threat that does execute the logic and writes a marker into parameter global memory (originally shared memory, but the issue is the same).

The output should say
[112211 112211],
but it only gives
[112211 0],
because the thread that's writing the second entry is not waiting at the syncthread(), as he is supposed to, so the first entry is still zero when he accesses it to copy it into the second position.

It's easy to check two ways that that's what's happening: you can replace the line 'if t < 14 :' with 'if True :', so thread 17 executes the same block and can't run ahead whether or not syncthreads works (bad), then proper result gets output. Second, simply run the script using the cuda simulator, it will properly synch and therefore output the right result.

NUMBA_ENABLE_CUDASIM=1 gdb -q  python
run snippet.py

(I saw some further truly bizarre behavior on my actual code, where it always failed the first time the kernel was created and sent to cuda drivers, but if I ran it again from ipython prompt, it would work the second time)

I have tested this on p2 and g2 instances of Amazon/EC2, using various AMIs and anaconda/numba versions, python2.7 and 3.5, all with the same result. The latest I tested on is Ubuntu 16.04, fully updated numba cuda via conda update, on python 2.7, and with and without anaconda accelerate installed.

Test code with failing syncthreads:
https://github.com/reneschaub/opt_einsum/blob/master/snippet.py

cuda environment info:
In [3]: numba.cuda.cudadrv.libs.test()
Finding cublas
located at /home/ubuntu/anaconda2/lib/libcublas.so.8.0.88
trying to open library...	ok
Finding cusparse
located at /home/ubuntu/anaconda2/lib/libcusparse.so.8.0.61
trying to open library...	ok
Finding cufft
located at /home/ubuntu/anaconda2/lib/libcufft.so.8.0.61
trying to open library...	ok
Finding curand
located at /home/ubuntu/anaconda2/lib/libcurand.so.8.0.61
trying to open library...	ok
Finding nvvm
located at /home/ubuntu/anaconda2/lib/libnvvm.so.3.1.0
trying to open library...	ok
finding libdevice for compute_20...	ok
finding libdevice for compute_30...	ok
finding libdevice for compute_35...	ok
finding libdevice for compute_50...	ok
Out[3]: True
In [4]: numba.cuda.api.detect()
Found 1 CUDA devices
id 0 Tesla K80 [SUPPORTED]
compute capability: 3.7
pci device id: 30
pci bus id: 0
Summary:
1/1 devices are supported
Out[4]: True

**Comment by reneschaub** [comment]
Some indentation got lost in the pasting of code. The snippet is also at 
https://github.com/reneschaub/opt_einsum/blob/master/snippet.py

**Comment by reneschaub** [comment]
some more cuda environment info:

In [3]: numba.cuda.cudadrv.libs.test()
Finding cublas
	located at /home/ubuntu/anaconda2/lib/libcublas.so.8.0.88
	trying to open library...	ok
Finding cusparse
	located at /home/ubuntu/anaconda2/lib/libcusparse.so.8.0.61
	trying to open library...	ok
Finding cufft
	located at /home/ubuntu/anaconda2/lib/libcufft.so.8.0.61
	trying to open library...	ok
Finding curand
	located at /home/ubuntu/anaconda2/lib/libcurand.so.8.0.61
	trying to open library...	ok
Finding nvvm
	located at /home/ubuntu/anaconda2/lib/libnvvm.so.3.1.0
	trying to open library...	ok
	finding libdevice for compute_20...	ok
	finding libdevice for compute_30...	ok
	finding libdevice for compute_35...	ok
	finding libdevice for compute_50...	ok
Out[3]: True
In [4]: numba.cuda.api.detect() 
Found 1 CUDA devices
id 0               Tesla K80                              [SUPPORTED]
                      compute capability: 3.7
                           pci device id: 30
                              pci bus id: 0
Summary:
	1/1 devices are supported
Out[4]: True

**Comment by sklam** [comment]
Thanks for reporting this issue, I can replicate the problem locally and I'm looking into this.

**Comment by sklam** [comment]
Here's a minimal reproducer of the problem: https://gist.github.com/sklam/e6b1decd42dea67822bad8a65dff8967

At the moment, I believe the issue is caused by the division (or the modulo op in the original code) that has an implicit divide-by-zero check that looks like:

```python
if divisor == 0:
   return DIV_BY_ZERO_ERROR_SIGNAL
```

This causes the control-flow to have a non-unifying path after the division.  The warp can diverge.  In my experiment, the `pad[0] = 11211` storing thread always ends up  running after `pad[1] = pad[0]` thread.  By CUDA ISA, the syncthread barrier (`bar.sync 0`) is executed by a warp and not by individual threads.  This means that the barrier is satisfied as long as one thread in the warp (of 32-threads) has reached the barrier.  Given how we only have 1 warp and that the warp have diverged, the syncthread has no effect at all.

**Comment by sklam** [comment]
I have a CUDA-C reproducer:

```C
#include <stdio.h>


__global__
void perm(int pad[]) {
    int t = threadIdx.x;
    int dxN;

    if ( t >= 0 ) {
        dxN = pad[0];
    }

    if ( t < 14 ) {
        if ( t >= 0 ) {
            // The following branch is the reason
            // comment it out to get the correct behavior
            if (dxN + 1 == 0) goto ERROR;
            pad[2] = 5 / (dxN + 1);
        }
    }

    if ( t == 1 ) {
        pad[0] = 112211;
    }

    __syncthreads();

    if ( t == 17 ) {
        pad[1] = pad[0];
    }

ERROR:
    pad[2] = 321321321;
}


int main() {

    int h_pad[3];
    int *dev_pad = 0;
    cudaMalloc(&dev_pad, sizeof(h_pad));
    cudaMemset(dev_pad, 0, sizeof(h_pad));

    perm<<< 1, 20 >>>(dev_pad);

    cudaMemcpy(h_pad, dev_pad, sizeof(h_pad), cudaMemcpyDeviceToHost);


    printf("pad[0] = %d    pad[1] = %d\n", h_pad[0], h_pad[1]);
    return 0;

}
```

The above code will have the same issue.  Removing the `if (dxN + 1 == 0) goto ERROR;` line will "fix" it.

**Comment by sklam** [comment]
My full analysis of the issue:

The syncthreads barrier and warp-level synchronization have been problematic in CUDA for some time.  It's a problem in the CUDA programming model.  It is easy to trigger undefined behaviors with branching.  It gets complicated by that fact that syncthreads barrier is satisfied by any thread in the warp reaching it.  So as long as a thread from each warp reaches the barrier, execution can continue.

In the latest CUDA 9, a new concept is added to support cooperative group (http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#cooperative-groups) that is suppose to provide a better programming model for fine grained communication.  There is also a new `__syncwarp` to ensure the wraps are converged.  However for older architecture, the problem still exist:

> Executing __syncwarp() guarantees memory ordering among threads participating in the barrier. Thus, threads within a warp that wish to communicate via memory can store to memory, execute __syncwarp(), and then safely read values stored by other threads in the warp.
>
> Note: For .target sm_6x or below, all threads in mask must execute the same __syncwarp() in convergence, and the union of all values in mask must be equal to the active mask. Otherwise, the behavior is undefined.
>
> Read more at: http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ixzz51qSKSakk 
Follow us: @GPUComputing on Twitter | NVIDIA on Facebook

See the note about how warp must be in convergence.  The issue here is that the combination of the ` if t < 14:` and the divide-by-zero check split the warp and putting the convergence location to the end of function.  So after the division, the warp is split.  Since the division takes more clock cycles, threads 14-19 will run first and it will execute `pad[1] = pad[0]`.  And since pre-Volta arch will run the diverged warp serially until it reaches the convergence point (which is at the end of the function), it will always complete threads 14-19 before threads 0-13.

The quick fix I have in https://github.com/sklam/numba/commit/fd925e262df802b304a2d619e97656a88bb6641b remove the emission of the exception handling code when the kernel is not running in debug mode.  As a result, it stops the compiler from putting the convergence point at the end of function due to the divide-by-zero check.  That is okay because the exception handling is originally intended for debugging only.  However, this would mean that the debug mode will put the kernel running into undefined behavior.

The longer term fix is to change the exception handling logic a bit such that the "raise" logic is not unified at the end of function but inserted directly into the location that raises.

**Comment by reneschaub** [comment]
Interesting cause. I guess Edsger W. Dijkstra was right about the goto statement. The CUDA programming guide doesn't mention goto at this time. I guess there just is no device side exception handling in CUDA.
Thanks for being on the case so fast, you guys are great.

**Comment by reneschaub** [comment]
The quick fix works. It should be a positive improvement in any current use case, since you still have exception handling in debug mode; if there was a sync issue before, it will still be there in debug mode, but at least not in regular. I think the inconsistency between debug and regular mode is a small price to pay for now, it seems this might be a pretty common problem (and took me about a week to figure out that it was a sync issue). You have my vote for a pull request.

**Comment by sklam** [comment]
I think the latest cuda driver may have altered the scheduling behavior.  I can no longer reproduce the error on driver version 387.99.  The program will always run correctly.  Error can still be reproduced on  384.90.  It does not seem to be affected by CUDA toolkit (e.g. libnvvm, nvcc).  PTX and SASS are the same on both driver.

The driver version 387.99 is for CUDA 9.  I am suspecting the change in behavior is related to the new warp synchronization primitives and how CUDA 9 is dropping implicit warp sync model.

**Comment by reneschaub** [comment]
The simple test case works with CUDA 9 but my original code shows the same problem, I'm guessing it is still sync related. Will try to get another example.

**Comment by reneschaub** [comment]
It seems like you removed cudatoolkit 9.x from conda distributions so I can't really test this now.

**Comment by seibert** [comment]
We have the cudatoolkit 9 in the Numba channel:

```
conda install -c numba cudatoolkit=9.0
```

To my knowledge, it hasn't been released to the official Anaconda channel yet.

**Comment by reneschaub** [comment]
Thanks. With 9.0 and master numba build, I keep getting the sync error. 
Unfortunately this is not the only problem. Master numba with merged 2655 fix takes care of the sync problem in both 8.0 and 9.x, but on 9.x I now also have an unrelated memcopy device to host error. 9.x is too unstable to use for me. 
Tomorrow I'll install cuda 9 again and whittle down my code to another testcase to help you reproduce on 9. I won't try to get the smallest possible code this time as that takes a while and the issue has already been determined.

**Comment by reneschaub** [comment]
I have a more elaborate test case to reproduce the sync error. Run this script from within my repo
https://github.com/reneschaub/opt_einsum/blob/master/isolate.py
It will fail under cuda 9 as well, not only cuda 8. If you run it with CUDASIM instead, it completes successfully. Likewise if you apply fix above sklam/numba@fd925e2 it will also work. This shows that the sync bug is still present in cudatoolkit 9.

**Comment by sklam** [comment]
@reneschaub, Thanks for the new testcase.   I will check it out.

**Comment by sklam** [comment]
I can confirm that the new testcase is also due to the div-by-zero.
