### ISSUE TITLE
Support np.newaxis indexing

### ISSUE THREAD

**Issue by leezu** [numba/numba#2761]
`np.newaxis` can be used to add length 1 dimensions when indexing an array.

I.e. `a[np.newaxis, :]` it is a nicer way to express `a.reshape((1,-1))`.

It currently fails with `numba.errors.InternalError: unsupported array index type none in (none, slice<a:b>)`

**Comment by dangpzanco** [comment]
Both `np.newaxis` and `None` are still not supported for indexing...

**Comment by ziofil** [comment]
`np.expand_dims()` should be supported though

**Comment by gresm** [comment]
It seems like ``np.expand_dims()`` works...

**Comment by dangpzanco** [comment]
The solution here is not simply using `np.expand_dims()` as a substitute for `np.newaxis` (or `None`) indexing. The main issue is having to significantly modify working Numpy code in order to accomodate for Numba's shortcomings...

Offtopic: It's been more than 4 years, and this lack of support for basic Numpy features is one of the reasons I rarely recommend Numba to anyone. Nowadays, I find that Pytorch's JIT + their (nearly) full "Numpy" API support is much easier to write than Numba and often achieves better performance (for parallel code on CPU, at least).

**Comment by gmarkall** [comment]
> Offtopic: It's been more than 4 years, and this lack of support for basic Numpy features is one of the reasons I rarely recommend Numba to anyone. Nowadays, I find that Pytorch's JIT + their (nearly) full "Numpy" API support is much easier to write than Numba and often achieves better performance (for parallel code on CPU, at least).

I'm happy that there is a tool out there that meets your needs, and I think this is a nice example of how a diverse ecosystem of co-existing implementations can satisfy the needs of many users with differing requirements - thank you for sharing your experience.

**Comment by stuartarchibald** [comment]
PR #8513 implements this feature, with thanks to @kc611!
