### ISSUE TITLE
Memory System left uninitialized in several tests

### ISSUE THREAD

**Issue by obilaniu** [numba/numba#2848]
While investigating segfaults in #2451 on PPC64LE, I noticed that several tests, among them

    numba.tests.test_nrt.TestNrtMemInfo.test_buffer
    numba.tests.test_nrt.TestNrtMemInfo.test_meminfo_refct_1
    numba.tests.test_nrt.TestNrtMemInfo.test_meminfo_refct_2

do not manage to initialize the C global structure `TheMSys` before attempting to use `rtsys.meminfo_new(addr, d)`. Since that method eventually leads to an invocation of `TheMSys.atomic_inc(&TheMSys.stats_mi_alloc);` and `TheMSys.atomic_inc` remains a `NULL` function pointer until initialized, this causes a segfault.

This problem is highly likely to also occur on x86-64 or any other platform, and can be reproduced, for instance, with

```shell
./runtests.py numba.tests.test_nrt.TestNrtMemInfo.test_meminfo_refct_1
```

The problem disappears if the ugly hack

```python
import numba; numba.targets.cpu.CPUContext(numba.typing.Context())
```

is added before the beginning of the afore-mentioned tests, thus triggering the initialization of `TheMSys`. This solves the segfaults for all three tests and allows them to pass. It may well be the case that similar initialization problems also exists in other (sub)tests as well.

*A probable reason for this not having been noticed earlier is that tests are not run in isolation, but instead sequentially within the same process. Since previous tests will have triggered initialization of* `TheMSys`, *the failure to do the same here escaped notice.*

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce and agree with your assessment. It is a little strange that we've not hit his before as whenever there's a new target to support a standard approach is a 
```bash
for x in `./runtests.py -l 2>&1|grep ^numba`; do echo ${x}; ./runtests.py ${x}; done 2>&1|tee log`
```
however, the code base changes and so clearly must have changed since that was last done!

To fix I'm going to add in:
1. An initialization guard so that methods on the `_Runtime` class cannot be run without the runtime being initialised.
2. The init sequence above to the NRT test setup.

Thanks again.
