### ISSUE TITLE
Numba configuration methods

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2870]
Whilst writing https://github.com/numba/numba/pull/2859 it became very apparent that having no way to configure some Numba settings to be non-default on a permanent basis is an issue. A couple of trivial examples of this in relation to  https://github.com/numba/numba/pull/2859 are wanting to set `NUMBA_DEVEOPER=1` for developers and being able to configure a colour scheme for exception handling that is permanent. I propose the existence of a configuration file, `.numba_config.yaml` (`YAML` format), that works with the current system as follows:

* The current configuration is taken as "default" for backwards compatibility.
* The "defaults" are hardcoded as a dictionary into the Numba source.
* The defaults can be overridden in the following order.
  1. Setting from a  `numba_config.yaml` in `~/.numba/` will override "defaults".
  2. Setting in a `numba_config.yaml` in PWD will override i.
  3. Environment variables will override ii.

This allows users to set up a general configuration, then specialise them locally per project, and finally for developers, or people debugging, who just want to override something temporarily, environment variables can be used.

Thoughts? @sklam @seibert @drtodd13 @ehsantn

I think this could also be used to help set up the parfors `parallel=dict()` config?

**Comment by mbargull** [comment]
Instead of hard-coded `~/.numba/` paths, you could consider using https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.
I'm not sure if you'd really want to check for `./numba_config.yaml` all the time. For one example, imaging an `cwd`-ing application that loads `numba` at some arbitrary point but not necessarily on startup with the initial `PWD`.
I would suggest an environment variable, e.g., `NUMBA_CONFIG_FILE`, instead. If a user wants the `./numba_config.yaml` functionality, they could just set `NUMBA_CONFIG_FILE=./numba_config.yaml`.

**Comment by stuartarchibald** [comment]
Closing. Config file support was added here https://github.com/numba/numba/pull/2930. It is in the 0.39.0 release.
