### ISSUE TITLE
Rename NUMBAPRO cuda related environment variables + refactor.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2879]
As noted in https://github.com/numba/numba/issues/2849, there are a number of `NUMBAPRO` prefixed environment variables still in use that could do with a name change:
```
NUMBAPRO_VERBOSE_CU_JIT_LOG
NUMBAPRO_CUDA_LOG_SIZE
NUMBAPRO_CUDA_DRIVER
NUMBAPRO_LIBDEVICE
NUMBAPRO_CUDALIB
NUMBAPRO_NVVM
```
and as suggested a `NUMBA_CUDA_SDK` env var that lets you specify the top-level CUDA directory and infers the rest of the paths needed would be good.

**Comment by AndiH** [comment]
I'm starting new with Numba and just had a look into the source code to understand which environment variables I need to set (NVVM and libdevice weren't found on their own on our HPC systems).

I am especially wondering about `NUMBAPRO_CUDALIB`. Is that variable legacy?

* For `get_libdevice()` in [numba/cuda/cudadrv/libs.py](https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/libs.py#L17), `NUMBAPRO_CUDALIB` is taken if `NUMBAPRO_LIBDEVICE` is not set. So, in this case, one would use `NUMBAPRO_CUDALIB` to point to the libdevice directory.
* For `get_cudalib()` in [the same file](https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/libs.py#L37), `NUMBAPRO_CUDALIB` is taken if `lib` is not set to `nvvm` or `NUMBAPRO_NVVM` is not set. Since only the constructor of `NVVM()` in [numba/cuda/cudadrv/nvvm.py](https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/nvvm.py#L111) uses `get_cudalib()` (by proxy of `open_cudalib()`) and sets `lib` to `nvvm` it boils down to `NUMBAPRO_NVVM` being set. I.e.: If `NUMBAPRO_NVVM` is not set, `NUMBAPRO_CUDALIB` is used to find NVVM.

That means, `NUMBAPRO_CUDALIB` can be used to either point to libdevice or to NVVM, but (obviously) not to both. I find that a very strange behaviour!

If you decide to revamp the environment variables, you should consider deprecating `NUMBAPRO_CUDALIB` (or make it official legacy). I think setting `NUMBA_CUDA_SDK` (or querying `CUDA_PATH`/`CUDA_ROOT`, which are sometimes set) would be an elegant addition!

(Disclaimer: I'm new to Numba and might have missed something. I'm interested in learning (+helping out), though. So, please tell.)

**Comment by AndiH** [comment]
Hey @stuartarchibald, is there any news on this?

**Comment by stuartarchibald** [comment]
@AndiH Unfortunately, as far as I'm aware, no work has been done on this in the current release cycle (we've had to dedicate more time than expected to some R&D efforts). I'll move it to the next cycle (0.40 RC).

**Comment by AndiH** [comment]
@stuartarchibald Alright! Not a problem! Can you comment on my findings and assumptions from the previous question? And, if I would decide to work on that, I'd need some pointers and discussions on what strategy to implement exactly.

**Comment by stuartarchibald** [comment]
@AndiH 
 * Anything with `NUMBAPRO` is from a really long while back and needs looking at for deprecation/updating.
 * CUDA toolkit/runtime etc has changed a bit through time so some things that used to be useful/present now aren't and the code probably exhibits these artifacts (as noted!).

Agree that `NUMBA_CUDA_SDK` is the thing to set, and `CUDA_PATH/CUDA_ROOT` could also be queried as a place to look if the env var and the default locations are fruitless, good idea.

To do the work for this, anything `NUMBAPRO` + CUDA related would need deprecation marks/warnings applied, then the new behaviour implemented and documented, along with a plan for final removal of the old.

**Comment by stuartarchibald** [comment]
Just taking a quick look at where linux distros put stuff, a lot of places is the answer:
```
ubuntu ships:
https://ubuntu.pkgs.org/18.04/ubuntu-multiverse-amd64/nvidia-cuda-toolkit_9.1.85-3ubuntu1_amd64.deb.html
https://ubuntu.pkgs.org/18.04/ubuntu-multiverse-amd64/libnvvm3_9.1.85-3ubuntu1_amd64.deb.html
/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc
/usr/lib/nvidia-cuda-toolkit/bin/nvcc
/usr/lib/x86_64-linux-gnu/libnvvm.so.3
/usr/bin/nvcc


centos 7 nux ships:
https://centos.pkgs.org/7/nux-dextop-x86_64/cuda-7.5.18-3.el7.nux.x86_64.rpm.html
https://centos.pkgs.org/7/nux-dextop-x86_64/cuda-libs-7.5.18-3.el7.nux.x86_64.rpm.html
/usr/share/cuda/libdevice.compute_20.10.bc
/usr/lib64/libnvvm.so.3
/usr/bin/nvcc

arch
https://archlinux.pkgs.org/rolling/archlinux-community-x86_64/cuda-10.1.105-11-x86_64.pkg.tar.xz.html
/opt/cuda/nvvm/libdevice/libdevice.10.bc
/opt/cuda/nvvm/lib64/libnvvm.so
/opt/cuda/bin/nvcc

slack
https://slackware.pkgs.org/14.2/slackonly-x86_64/cudatoolkit-8.0.61-x86_64-1_slonly.txz.html
/usr/share/cuda/nvvm/lib64/libnvvm.so.3.1.0
/usr/share/cuda/nvvm/libdevice/libdevice.compute_20.10.bc
/usr/share/cuda/bin/nvcc
```

**Comment by stuartarchibald** [comment]
ubuntu ships:
/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc
/usr/lib/nvidia-cuda-toolkit/bin/nvcc
/usr/lib/x86_64-linux-gnu/libnvvm.so.3
/usr/bin/nvcc


centos 7 nux ships:
/usr/share/cuda/libdevice.compute_20.10.bc
/usr/lib64/libnvvm.so.3
/usr/bin/nvcc

arch
/opt/cuda/nvvm/libdevice/libdevice.10.bc
/opt/cuda/nvvm/lib64/libnvvm.so
/opt/cuda/bin/nvcc

slack
/usr/share/cuda/nvvm/lib64/libnvvm.so.3.1.0
/usr/share/cuda/nvvm/libdevice/libdevice.compute_20.10.bc
/usr/share/cuda/bin/nvcc

**Comment by stuartarchibald** [comment]
I think an approach that might work is to do the following in the order presented:

1. Check env var(s)
2. Check Anaconda locations
3. Check system locations:
    a. Check via ld-cache
    b. Check known paths?

Am also thinking that if `libnvvm` and `libdevice` don't come from the same meta-location (i.e. env vars, anaconda, system) then the loaders should not proceed.

**Comment by seibert** [comment]
Closing this issue as 0.44 contains a reworked CUDA environment detection heuristic.  (See #4096 for more details.)
