### ISSUE TITLE
guvectorize support for uint8, uint16, uint32

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#2934]
numba 0.37.0, Python 3.6, Anaconda 5 Linux x86-64
guvectorize won't respect the signatures for uint8, uint16, uint32 and will silently cast them to higher level signed integers. uint64 for some reason is unaffected:
```
import numba
import numpy

DTYPES = [
    'int8', 'int16', 'int32', 'int64',
    'uint8', 'uint16', 'uint32', 'uint64',
    'float32', 'float64',
    'complex64', 'complex128'
]

signatures = ['{T}[:], {T}[:]'.format(T=dtype) for dtype in DTYPES]
print(signatures)

@numba.guvectorize(signatures, '(i)->(i)')
def dumb_inc(x, y):
    for i in range(x.size):
        y[i] = x[i]


for dtype in DTYPES:
    x = numpy.array([1, 2, 3]).astype(dtype)
    y = dumb_inc(x)
    print(dtype, y.dtype)                                         
```
Output:
```
['int8[:], int8[:]', 'int16[:], int16[:]', 'int32[:], int32[:]', 'int64[:], int64[:]', 'uint8[:], uint8[:]', 'uint16[:], uint16[:]', 'uint32[:], uint32[:]', 'uint64[:], uint64[:]', 'float32[:], float32[:]', 'float64[:], float64[:]', 'complex64[:], complex64[:]', 'complex128[:], complex128[:]']
int8 int8
int16 int16
int32 int32
int64 int64
uint8 int16
uint16 int32
uint32 int64
uint64 uint64
float32 float32
float64 float64
complex64 complex64
complex128 complex128
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think what you are seeing is a result of type promotion (NumPy based) and dispatch selection. If you do this (note compiling unsigned int types first):
```python
import numba
import numpy

DTYPES = [
    'uint8', 'uint16', 'uint32', 'uint64',
    'int8', 'int16', 'int32', 'int64',
    'float32', 'float64',
    'complex64', 'complex128'
]
signatures = ['{T}[:], {T}[:]'.format(T=dtype) for dtype in DTYPES]
print(signatures)

@numba.guvectorize(signatures, '(i)->(i)')
def dumb_inc(x, y):
    for i in range(x.size):
        y[i] = x[i]

for dtype in DTYPES:
    x = numpy.array([1, 2, 3]).astype(dtype)
    y = dumb_inc(x)
    print(dtype, y.dtype)
```
you get:
```
['uint8[:], uint8[:]', 'uint16[:], uint16[:]', 'uint32[:], uint32[:]', 'uint64[:], uint64[:]', 'int8[:], int8[:]', 'int16[:], int16[:]', 'int32[:], int32[:]', 'int64[:], int64[:]', 'float32[:], float32[:]', 'float64[:], float64[:]', 'complex64[:], complex64[:]', 'complex128[:], complex128[:]']
uint8 uint8
uint16 uint16
uint32 uint32
uint64 uint64
int8 int8
int16 int16
int32 int32
int64 int64
float32 float32
float64 float64
complex64 complex64
complex128 complex128
```
This is because under NumPy type promotion ruling a `uint{2**N}` can be promoted to an `int{2**(N+1)`
```
In [29]: np.promote_types('u1', 'i2')
Out[29]: dtype('int16')
```
and as gufuncs follow NumPy behaviour it leads to what you are seeing. Essentially, as a signed int function variant exists (as it was compiled first), and it is safe to promote a `uint{2**N}` to an `int{2**(N+1)}` (apart from in the `uint64` case as noted), promotion on dispatch is used ahead of compiling a new function variant.

This also happens:
```
In [33]: np.promote_types('u8', 'i8')
Out[33]: dtype('float64')
```
Operations using a uint64 and an int8 will coerce to a float64 as that is the cheapest representation that can safely hold both.

**Comment by crusaderky** [comment]
Thanks @stuartarchibald , confirmed your solution and it works. I think the documentation (https://numba.pydata.org/numba-doc/dev/user/vectorize.html) could use a mentione of it?

**Comment by stuartarchibald** [comment]
RE https://github.com/numba/numba/issues/2934#issuecomment-388509929, this is to track https://github.com/numba/numba/issues/2964. Closing this ticket as I think it's resolved. Thanks for the feedback.
