### ISSUE TITLE
AssertionError for simple Jaccard distance on two sets

### ISSUE THREAD

**Issue by rookiepig** [numba/numba#2945]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, below is the code for calculate simple Jaccard distance on two sets:
```python
@jit
def iou_score_jit(set_a, set_b):
   score = 0.0                                                                                                                                                        
   if set_a and set_b:
     score = float(len(set_a.intersection(set_b))) / max(len(set_a), len(set_b))
   return score
```
then I created two random sets:
```python
import numpy as np
set_a = set(np.random.ranint(0, 100000, 1000).astype(str).tolist())
set_b = set(np.random.ranint(0, 100000, 1000).astype(str).tolist())
score = iou_score_jit(set_a, set_b)
```
the AssertionError were shown:
```python
/home/zhangkang-pd/.local/lib/python2.7/site-packages/numba/typing/typeof.pyc in _typeof_set(val, c)
    160     item = next(iter(val))
    161     ty = typeof_impl(item, c)
--> 162     return types.Set(ty, reflected=True)
    163 
    164 @typeof_impl.register(slice)

/home/zhangkang-pd/.local/lib/python2.7/site-packages/numba/types/abstract.pyc in __call__(cls, *args, **kwargs)
     58         the new instance is returned.
     59         """
---> 60         inst = type.__call__(cls, *args, **kwargs)
     61         return cls._intern(inst)
     62 

/home/zhangkang-pd/.local/lib/python2.7/site-packages/numba/types/containers.pyc in __init__(self, dtype, reflected)
    370 
    371     def __init__(self, dtype, reflected=False):
--> 372         assert isinstance(dtype, (Hashable, Undefined))
    373         self.dtype = dtype
    374         self.reflected = reflected

AssertionError: 
```
After searching online, I could not find any similar cases. So is this a bug or the usage of numba is wrong ?

**Comment by Rik-de-Kort** [comment]
Here's a minimal reproducer:
````python
@njit
def foo(bar):
    return

foo(set(["bar"]))
````

The error occurs because you're passing a set of strings. Since strings are not considered hashable, that's yields to an assertion error. I'm not sure whether this is intended (maybe @sklam knows?).

Additionally, I discovered an issue where branching on sets is simply not supported due to a missing `len` attribute in the Numba typing system. This is #2948.

If you can use numeric values (maybe you're already vectorizing texts earlier or later on), you can simply replace `if set_a and set_b` by `if len(set_a) and len(set_b)` in your code and it ought to work fine (as long as you're not passing sets of strings).

**Comment by sklam** [comment]
String support is just not there.

**Comment by rookiepig** [comment]
Thanks
