### ISSUE TITLE
PR breaking code cleanup

### ISSUE THREAD

**Issue by innovate-invent** [numba/numba#2980]
With the addition of flake8 it has been noted that there need to be some project wide code changes. Running an autoformatter will likely break some PR's and so we need to close out any pending ones and schedule a code freeze. I have noticed some other organisational issues in the repo that would also likely break PR's and think it would be good to get everything done at one time.

Here is a (growing) list of other issues that should be done at that time:

* I intend to implement a dynamic loader for library support which will optimally move much of the existing support for libraries into a different structure. Namely support for ctypes seems to be scattered across several files. It would also be good to treat NumPy and Python builtin supporting code equally to maintain consistency. It would also be good to have all library specific code encapsulated in one folder to maximize modularity. Ideally this shouldn't change the numba interface and we can keep placeholders that re-export anything that does move in the module interface.

I propose a directory structure along the lines of:
  - numba : project root
     - numba : package root
        - support : searched by dynamic loader
            - [library name] : folder containing all library specific code: numpy, ctypes, ffi, cmath, etc. including python built-ins
                - [target] : folder for target specific code (cpu, cuda, hsa)
                    - \__init__.py
                - \__init__.py
                - [non-target specific code].py
        - extending
        - targets : Target specific numba internal code
            - cpu
            - cuda
            - hsa
        - types
        - typing
        - etc...

\__init__.py in the library folders implement load(context, target) which is called by the loader. This function is responsible for registering everything within the context and calling load() on the intended target sub-module. extending should be the only necessary numba import in the library code providing a uniform interface. This avoids any awkward import loops.

* Another item that should be done during the freeze is stubbing docstrings for EVERYTHING. There needs to be better docstrings in this project. autodoc can generate some meaningful documentation rather than hunting through the source trying to infer functionality from function and variable names.

* The datamodel code seems it would benefit from being broken up. Keep all abstract and general implementations where they are and move any library specific datamodels to a library specific location like previously mentioned.

* Anything else?

**Comment by innovate-invent** [comment]
[Here](https://github.com/innovate-invent/numba/tree/dynamic_support) is a branch beginning to implement the dynamic loader changes.

**Comment by stuartarchibald** [comment]
Many thanks for writing this and putting thought into potential changes. What                                                   
you propose above is with merit but also needs to be measured. The level of                                                     
change proposed is large and unfortunately the various concerns in the code base                                                
are quite probably going to be challenging to separate in the manner described                                                  
(based on prior experience/knowledge of core devs).                                                                             
                                                                                                                                
Further we have to be very mindful of the following:                                                                            
 * The cost for core developers of having to do a "fork-lift" alteration to                                                     
   their mental model of the code base is going to be high. Building a mind-map                                                
   of the code base takes order of months, after all compilers are complicated,                                                 
   and as a result shuffling everything about, whilst ostensibly may clean                                                      
   things up, may also knock productivity (along with the noted PR breakage).                                                   
 * Numba has a huge build farm that tests some 88                                                                               
   (https://mobile.twitter.com/numba_jit/status/984983101435731968, it's                                                        
   actually more than that now) combination of `{OS, Python, NumPy, CUDA}`. This                                                
   exists in part because seemingly innocuous changes (such as a refactor) often                                                
   have unexpected effects. From experience, debugging large, sweeping changes                                                  
   is often hard!                                                                                                               
 * The Numba code base is large and complicated and has a number of people                                                      
   working on it at any one time.                                                                                               
                                                                                                                                
Considering the above points, it is going to be easier (and more accepted) to                                                   
integrate large numbers of progressive small changes than a single large change.                                                
Therefore for the original proposal to be considered, a plan to make these                                                      
changes in incremental stages would really help it gain traction!                                                               
                                                                                                                                
For the application of PEP8, this is something that we want to do, but to do                                                    
this effectively and minimise impact it needs to be done during during RC code                                                  
freeze/release time. A priori to such a change there also needs to be consensus                                                 
over tooling and what "formatting" is to be applied such that a standard is                                                     
known. Further, tool configuration needs writing, setting up, and testing both                                                  
for developers and for CI systems. This to make it so that it is easy to set up
development to meet that standard and easy to achieve such a standard. A PR to
start driving the application of this would be welcomed.

The addition of autodoc documentation generation and docstring stubs needs to be
investigated. Whether autodoc can produce something meaningful needs to be
considered, along with how much clean up and adjustment is required in the code
base to achieve this. It also needs to be compared to the use of tools such as
VSCode which do a good job already of permitting the code base to be navigated
and introspected.

**Comment by innovate-invent** [comment]
For the docstring standard I created a PR [here](https://github.com/numba/numba/pull/2977) to be discussed separately. Autodoc output allows for tighter coupling of the code interface and its documentation. It is the happy middle ground of documentation without the clutter of the actual code implementation. I have a [PR here](https://github.com/numba/numba/pull/2976) that has autodoc set up and I am going to go forward with documentation once the docstring standard is accepted. I don't think requiring individual developers to use a specific IDE or tool to understand the code would be appropriate.

For the autoloader, a incremental transition of the existing code it easy. My proposal works alongside the existing structure and we can migrate the builtin and numpy specific code with time. I just want more feedback on the implementation of the autoloader before I put any significant effort into it.
Most of the migration changes would not change the way anything functions but simply relocates the functions and classes into different files. I could go so far as to leave comment blocks redirecting a reader to the new location of the function if necessary. The major change would be breaking up the boxing, typing, models, and lowering code files. Currently if I want to add support for a library I need to shotgun code across a number of already monolithic files and it is only going to get worse as interest in expanding numbas support grows.

**Comment by stuartarchibald** [comment]
Numba has been refactored heavily in 0.49, hopefully resolving a number of the issues highlighted here. Further the documentation is much clearer too, though obviously there's always things that can be improved. Am going to close this issue, if there's specific fixed scope things that can be improved further please feel free to open additional tickets, thanks.
