### ISSUE TITLE
Strange behavior of flat/ravel when combined with nopython/parallel

### ISSUE THREAD

**Issue by ZeppLu** [numba/numba#3117]
sorry I don't know if it's a bug, but it does confuse me a lot. if not, I hope someone can explain it for me, thanks.

let's define the following function:
```python
@nb.jit()
def flat(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit(nopython=True)
def flat_n(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit(nopython=True, parallel=True)
def flat_np(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit()
def ravel(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d

@nb.jit(nopython=True)
def ravel_n(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d

@nb.jit(nopython=True, parallel=True)
def ravel_np(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d
```

these functions simply modify the diagonal of matrix `X` with value `d` (because `np.fill_diagonal` can't be used inside jitted function). test result on my machine is:
- `flat`, `ravel` and `ravel_n` modify the diagonal as expected
- `flat_n` raises `LoweringError` with message `No definition for lowering setitem(array.flat(array(uint8, 2d, C)), slice<a:b:c>, array.flat(array(uint8, 2d, C))) -> none`. is it because `np.ndarray.flat` returns a python object? should the error be triggered at compile time rather than runtime?
- `flat_np` runs smoothly, except that matrix's diagonal doesn't get modified. why?
- `ravel_np` behaves the same as `flat_np`

`np.__version__=='1.14.5'` and `nb.__version__=='0.38.1+1.gc42707d.dirty'` if it can help, they're both installed via `conda`

**Comment by stuartarchibald** [comment]
Thanks for the report. 

1. These functions probably won't do what you want unless you supply `X` as a 2D square matrix.
2. Using `numba.jit` without `nopython=True` will allow Numba to fall back to using object mode (basically just running the python interpreter and compiling loops if it can, see: http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#no-python-mode-vs-object-mode). The errors raised by `flat_n` will be the same in other places where similar assignment is attempted and if fall back is possible then it will happen, hence it works but for the wrong reasons.
3. What NumPy does for e.g. `flat`, or indeed anything else, often doesn't matter as Numba reimplements most things internally. I think in this case the Numba `flat` implementation has no `setitem` support for it, hence the error.

Augmenting your code as follows:
```python
import numba as nb
import numpy as np

@nb.jit()
def flat(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit(nopython=True)
def flat_n(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit(nopython=True, parallel=True)
def flat_np(X, d):
    N = X.shape[0]
    X.flat[:N**2:N+1] = d

@nb.jit()
def ravel(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d

@nb.jit(nopython=True)
def ravel_n(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d

@nb.jit(nopython=True, parallel=True)
def ravel_np(X, d):
    N = X.shape[0]
    X.ravel()[:N**2:N+1] = d

fns = [flat, flat_n, flat_np, ravel, ravel_n, ravel_np]

print(nb.__version__)

for fn in fns:
    d = 10
    X = np.ones((5, 5))
    print("Name: %s " % fn.__name__)
    try:
        fn(X, d)
    except BaseException as e:
        print(e)
    else:
        print(X)
    print('-' * 80)
```
gives me:
```
$ python issue3117.py 
0.40.0dev0+56.g25b6541
Name: flat 
[[10.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1. 10.  1.]
 [ 1.  1.  1.  1. 10.]]
--------------------------------------------------------------------------------
Name: flat_n 
Failed at nopython (nopython mode backend)
No definition for lowering setitem(array.flat(array(float64, 2d, C)), slice<a:b:c>, array.flat(array(float64, 2d, C))) -> none

File "issue3117.py", line 12:
def flat_n(X, d):
    <source elided>
    N = X.shape[0]
    X.flat[:N**2:N+1] = d
    ^
[1] During: lowering "$0.7[$0.16] = d" at issue3117.py (12)
--------------------------------------------------------------------------------
Name: flat_np 
Failed at nopython (nopython mode backend)
No definition for lowering setitem(array.flat(array(float64, 2d, C)), slice<a:b:c>, array.flat(array(float64, 2d, C))) -> none

File "issue3117.py", line 17:
def flat_np(X, d):
    <source elided>
    N = X.shape[0]
    X.flat[:N**2:N+1] = d
    ^
[1] During: lowering "$0.7[$0.16] = d" at issue3117.py (17)
--------------------------------------------------------------------------------
Name: ravel 
[[10.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1. 10.  1.]
 [ 1.  1.  1.  1. 10.]]
--------------------------------------------------------------------------------
Name: ravel_n 
[[10.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1. 10.  1.]
 [ 1.  1.  1.  1. 10.]]
--------------------------------------------------------------------------------
Name: ravel_np 
[[10.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1. 10.  1.]
 [ 1.  1.  1.  1. 10.]]
--------------------------------------------------------------------------------
```

 * `flat` works because of object mode fall back
 * `flat_n` fails because of assignment to `ndarray.flat`
 * `flat_np` fails because of assignment to `ndarray.flat`
 * `ravel` works
 * `ravel_n` works
 * `ravel_np` works

I note you are not on the latest version of Numba, which may explain the differences we are seeing?

I've opened https://github.com/numba/numba/issues/3120 to cover the lack of `setitem` on `flat`.
I've opened https://github.com/numba/numba/issues/3121 as a feature request for `np.fill_diagonal`.

**Comment by ZeppLu** [comment]
Thanks for you explanation! As for no-python mode, I don't know if my understanding is right:

- No matter what `nopython` parameter is, `numba` will always firstly try to compile function to using no-python mode. But if compilation failed, it will silently fallback to object mode unless `nopython=True` is specified (in which case an exception is raised)
- Function, `np.ndarray.flat` for example, has different implementations for two modes, the one for object mode is borrowed from `numpy` (?) while the one for no-python mode is written in `numba` (because `flat` in object mode has `setitem` support)


And seems that version does matter, just upgraded to 0.39, now `ravel_np` does a great job

**Comment by seibert** [comment]
Yes, that is correct.

**Comment by stuartarchibald** [comment]
Closing in favour of #3120 and #3121. Thanks.
