### ISSUE TITLE
[Question]List comprehension compile failed

### ISSUE THREAD

**Issue by hoangtocdo90** [numba/numba#3118]
Hi all please help me .
fast_chi2_distance function compile ok not using List comprehension. but fast_find_angle compile failed. Some one can tell me what i'm doing wrong ? I'm using python3 in windows
thanks !

[source](https://gist.github.com/hoangtocdo90/0a8a646d04ea8a223f36b80381c5e327)

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bit puzzling, though I've seen something similar before. This is a reproducer:
```python
from numba import jit

@jit
def foo():
    x1 = [i for i in range(0, 4)]
    dist_0 = sum([1,2,3])

foo()
```
either statement by itself works fine, but together they produce an error. I think this is something to do with the interaction between the closure inlining pass and object mode fallback. The closure inlining will work for the list comprehension, but `njit` compilation will fail due to the use of `sum` and cause a fallback to object mode. Object mode seems to not like closures (the inlining pass is not part of the pipeline). Reproducer:

```python
from numba import jit

@jit(forceobj=True)
def foo():
    x1 = [i for i in range(0, 4)]

foo()
```

adding the inling pass to object mode after the `stage_objectmode_frontend` fixes both. I'll try and put a fix in for this in the next release.

**Comment by hoangtocdo90** [comment]
Thanks for clearly explain !
