### ISSUE TITLE
Add doc for NUMBA_DEBUGINFO in Environment variables page

### ISSUE THREAD

**Issue by sklam** [numba/numba#3306]
We should mention NUMBA_DEBUGINFO in http://numba.pydata.org/numba-doc/latest/reference/envvars.html?highlight=environment%20variable .

Currently, it's only mentioned in http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html?highlight=numba_debuginfo#globally-override-debug-setting

**Comment by AaronCritchley** [comment]
It looks like this has since been fixed by https://github.com/numba/numba/pull/3307/files and is live [here](http://numba.pydata.org/numba-doc/latest/reference/envvars.html?highlight=environment%20variable#envvar-NUMBA_DEBUGINFO). Can this issue be closed or does it need further work (happy to do the work if more is needed)?

**Comment by seibert** [comment]
Yes, we can close this.  Thanks!
