### ISSUE TITLE
1.16.2.4. Does Numba automatically parallelize code? gufuncs with the target="parallel" example

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3312]
Can someone add an example for gufunc, based on docs 

> It can, in some cases:
> 
>     Ufuncs and gufuncs with the target="parallel" option will run on multiple threads.

**Comment by stuartarchibald** [comment]
Thanks for the query. I'm afraid I'm not quite sure what you are asking for as an example. If you add the `target="parallel"` kwarg to any `@guvectorize` or `@vectorize` decorated function it will automatically run in parallel using multiple threads. Take the example here: http://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-guvectorize-decorator, just adding the noted kwarg like:

```python
@guvectorize([(int64[:], int64, int64[:])], '(n),()->(n)', target="parallel")
def g(x, y, res):
    for i in range(x.shape[0]):
        res[i] = x[i] + y
```
makes it run on multiple threads.

Adding a `sqrt` and floating point input/output to that example so there's some reasonable work to do in the loop demonstrates:
```python
from numba import guvectorize, float64
import numpy as np
from time import time
from contextlib import contextmanager

@contextmanager
def timer(name=""):
    ts = time()
    yield
    te = time()
    print("Elapsed time for %s: %s" % (name, te - ts))

gu = guvectorize([(float64[:], float64, float64[:])], '(n),()->(n)')
gup = guvectorize([(float64[:], float64, float64[:])], '(n),()->(n)', target="parallel")

def g(x, y, res):
    for i in range(x.shape[0]):
        res[i] = np.sqrt(x[i] + y)

gvec = gu(g)
gvecp = gup(g)

a = np.arange(6).reshape(2, 3).astype(np.float64)
print(gvec(a, 10))
print(gvec(a, np.array([10, 20])))
print(gvecp(a, 10))
print(gvecp(a, np.array([10, 20])))


x = 20000
y = 10000
n = x * y
a = np.arange(n).reshape(x, y).astype(np.float64)

with timer("single-thread, scalar y"):
    gvec(a, 10)

with timer("multi-thread, scalar y"):
    gvecp(a, 10)

z = np.arange(x).astype(np.float64)
with timer("single-thread, vector y"):
    gvec(a, z)

with timer("multi-thread, vector y"):
    gvecp(a, z)
```
This gives me:
```
Elapsed time for single-thread, scalar y: 4.3097546100616455
Elapsed time for multi-thread, scalar y: 1.2879137992858887
Elapsed time for single-thread, vector y: 4.235764980316162
Elapsed time for multi-thread, vector y: 1.243720293045044
```

**Comment by cristipurdel** [comment]
>     Doc suggestion
>     Maybe need a good gufunc example

I would prefer to see the most complex gufunc example (which should be updated in case new features are added), which also works on 'cuda'. This should also show why is it better than 'vectorize'. Also a conversion to gflops would help. From my point of view, 'guvectorize' should be similar to OpenMP/OpenACC implementation, maybe using smth like 
i = numba.grid(1), and the gufunc should be applied to each element of the vector(i), adding also a fallback for 'cuda' to 'parallel'

I will test some examples (based on the OpenACC approach) for each numba version, and post results if I see an improvement on the current status

**Comment by stuartarchibald** [comment]
> I would prefer to see the most complex gufunc example (which should be updated in case new features are added), which also works on 'cuda'. 

I'm not quite sure what this is, defining an arbitrarily complex function is easy but not necessarily informative? Is it that you are trying to write gufuncs using solely a subset of what is available for all `@guvectorize` target architectures, and you aren't sure what is supported everywhere or how to measure the performance difference between CPU and GPU implementations of some code written in that subset? If this is the case, roughly, loops and `{c,}math` is the answer. Don't also forget that you get a load more flexibility on the CPU because of NumPy support, and that GPU kernels will have differing performance depending on whether the data is on the device at time of execution.

> I would prefer to see the most complex gufunc example (which should be updated in case new features are added), which also works on 'cuda'. This should also show why is it better than 'vectorize'. 

On CPU `guvectorize` and `vectorize` use the same dispatch mechanism, almost identical code generation paths and the same scheduling mechanism. This is because `vectorize` is essentially just a specialisation of `guvectorize`. When the `parallel` target is set, this just generates gufuncs over the outermost dimensions and then pushes them into a scheduler (of which there are now 3 variants http://numba.pydata.org/numba-doc/latest/user/threading-layer.html).

> I've modified the code to try to run on the 'cuda' :

I suspect the reason for no-matching-signature is for a couple of reasons:
1. That the dispatch mechanism on the GPU targets it not via NumPy (the GPU targets in general do not support NumPy etc) and as a result automatic broadcasting does not happen; the defined signature only makes sense for a scalar `y`.
2. That on the GPU targets broadcasting in general is not implemented as it doesn't match the programming model particularly well (many lightweight threads each with an explicitly defined code path operating on scalars, the vectorization comes from the use of warps/wavefronts opposed to vectorizing loops as on CPU). Hence the gufunc is not broadcast.

**Comment by cristipurdel** [comment]
I managed to get it running on 'cuda' and show some speed-up:

```
from numba import guvectorize, float32, cuda
import numba
import numpy as np
from time import time
from contextlib import contextmanager
from math import sin
import pkg_resources, os


try:
	print('NUMBA NUM THREADS = ' + str(os.environ['NUMBA_NUM_THREADS']))
except:
	print('NUMBA NUM THREADS = ' + str(numba.config.NUMBA_DEFAULT_NUM_THREADS))

print('numba version used: ' + str(pkg_resources.get_distribution("numba").version))
print('numpy version used: ' + str(pkg_resources.get_distribution("numpy").version))

#import platform
#print(platform.processor())

import cpuinfo
print(cpuinfo.get_cpu_info()['brand'])

count = 100

@contextmanager
def timer(name=""):
    ts = time()
    yield
    te = time()
    print("Elapsed time for %s: %s" % (name, te - ts))

gus = guvectorize([(float32[:], float32, float32[:])], '(n),()->(n)')
gup = guvectorize([(float32[:], float32, float32[:])], '(n),()->(n)', target="parallel")


def g(x, y, res):
    for i in range(x.shape[0]):
        for c in range(count):
            res[i] += float32(sin(x[i] + y))

gvecs = gus(g)
gvecp = gup(g)



a = np.arange(6).reshape(2, 3).astype(np.float32)

print(gvecs(a, 10.))
print(gvecs(a, np.array([10., 20.]).astype(np.float32)))
print(gvecp(a, 10.))
print(gvecp(a, np.array([10., 20.]).astype(np.float32)))

if numba.cuda.is_available():
    guc = guvectorize([(float32[:], float32, float32[:])], '(n),()->(n)', target="cuda")    
    gvecc = guc(g)
    print(gvecc(a, 10.))
    print(gvecc(a, np.array([10., 20.])))    

x = 4000
y = 1600

n = x * y
a = np.arange(n).reshape(x, y).astype(np.float32)
z = np.arange(x).astype(np.float32)

with timer("single-thread, scalar y"):
    s0d = gvecs(a, 10.)

with timer("multi-thread, scalar y"):
    p0d = gvecp(a, 10.)

with timer("single-thread, vector y"):
    s1d = gvecs(a, z)

with timer("multi-thread, vector y"):
    p1d = gvecp(a, z)
    
if numba.cuda.is_available():
    
    with timer("cuda-thread, scalar y"):
        c0d = gvecc(a, 10.)        
    
    with timer("cuda-thread, vector y"):
        c1d = gvecc(a, z)    
```

Output is:

```
NUMBA NUM THREADS = 4
numba version used: 0.40.0
numpy version used: 1.14.3
Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
[[-54.402153 -99.999054 -53.657257]
 [ 42.016712  99.06081   65.02877 ]]
[[-108.80431  -199.99774  -107.31471 ]
 [ -42.605343    8.502945   51.79365 ]]
[[-163.20647   -299.9969    -160.97224  ]
 [  -0.5886335  107.56376    116.82272  ]]
[[-217.60863  -399.9969   -214.62978 ]
 [ -85.210754   17.005898  103.58725 ]]
[[-54.402138 -99.999054 -53.657257]
 [ 42.016712  99.06081   65.02877 ]]
[[-54.402138 -99.999054 -53.657257]
 [-84.62212  -90.55785  -13.235186]]
Elapsed time for single-thread, scalar y: 38.53123641014099
Elapsed time for multi-thread, scalar y: 10.765610933303833
Elapsed time for single-thread, vector y: 39.43611192703247
Elapsed time for multi-thread, vector y: 11.671869039535522
Elapsed time for cuda-thread, scalar y: 4.156300067901611
Elapsed time for cuda-thread, vector y: 4.1717071533203125
```

> When the parallel target is set, this just generates gufuncs over the outermost dimensions and then pushes them into a scheduler (of which there are now 3 variants http://numba.pydata.org/numba-doc/latest/user/threading-layer.html).

Still I do not understand which is the outermost dimension ...
If I have `a = np.arange(n).reshape(x, y, z).astype(np.float32)`
gufunc / guvectorize will do its magic on x, while `parallel `on z (or y)?
and in case of warps/wavefronts they will do it onlly on x dimension?
