### ISSUE TITLE
scipy.linalg expm and solve_banded functions

### ISSUE THREAD

**Issue by sahaskn** [numba/numba#3351]
Dear developer and users,
If possible, I'll like to know an example to use scipy.linalg expm and solve_banded function inside numba nopython  jitted function. (https://numba.pydata.org/numba-doc/latest/extending/high-level.html).

**Comment by stuartarchibald** [comment]
Thanks for the query.
In general SciPy functions are not supported by Numba. Supported features are noted in the documentation:
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

__To end up with something with the highest performance__:
To obtain the functionality you require `scipy.linalg.expm` would need entirely reimplementing in a form Numba can compile (use the Padé approximation?). The banded solve is less effort as it just requires a call to LAPACK `{s,d,c,z}gbsv` which is available from the SciPy LAPACK cython exports:
```
In [12]: import scipy.linalg.cython_lapack as cla

In [13]: cla.__pyx_capi__['dgbsv']
Out[13]: <capsule object "void (int *, int *, int *, int *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, int *, int *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, int *, int *)" at 0x7fc8c54e9540>
```
from there the Numba extension module provides a method of getting the address:
```
In [17]: import numba.extending as nbe

In [18]: nbe.get_cython_function_address('scipy.linalg.cython_lapack', 'dgbsv')
Out[18]: 140499892185344
```
which can then just be used in an appropriately declared `ctypes.CFUNCTYPE`. An example is documented here: http://numba.pydata.org/numba-doc/latest/extending/high-level.html#importing-cython-functions

At this point, because Numba supports `ctypes`, this bound function can be used in a `nopython` jitted function (pass the pointers via the array `.ctypes` attribute).

__To end up with something that works well, with far less effort__:
Whilst reimplementing `expm` in Numba would probably result in a faster `expm`, the `expm` in SciPy is probably quite fast already. Further, the `solve_banded` function performance is likely to be dominated by the LAPACK routine, so there may be little benefit in running this from `nopython` mode. If you need these two functions as part of a more complicated algorithm, Numba 0.40.0 has a new feature, `numba.objmode`, a context manager that will allow `nopython` mode to jump back into object mode ([documentation is here](http://numba.pydata.org/numba-doc/latest/user/withobjmode.html#the-objmode-context-manager)). This would allow `nopython` mode to run before and after those unsupported SciPy calls. Conceptually:
```python

@njit
def func(matrix):
  # do manipulations on matrix, or whatever is needed here
  # then jump into object mode to run the SciPy functions
  with objmode(answer='float64[:]'):
    newmat1 = scipy.linalg.expm(matrix)
    answer = scipy.linalg.solve_banded(<e.g. stage newmat1 for the call, supply RHS etc>)
  # jump back into nopython mode
  # do something with answer etc
```

**Comment by sahaskn** [comment]
Dear @stuartarchibald, 
Thanks for explaining this to me. This feature objmode is really awesome and the snippet of code you posted is exactly what I want. One question: Does the modified code below works as well:
@njit
def func(args):
  # do manipulations on matrix, or whatever is needed here
  # then jump into object mode to run the SciPy functions
 ` for i in range(len1):
      for j in range(len2):
          mat1 = #matrix definition
          mat2 = #matrix definition
          val = #1D array
          with objmode(answer='float64[:]'):
            newmat1 = scipy.linalg.expm(mat1)
            answer = scipy.linalg.solve_banded((1,1), mat2, val)
          # jump back into nopython mode
          # do something with answer etc`

**Comment by stuartarchibald** [comment]
@sahaskn no problem, thanks for getting back to us, I'm glad this works for you.

**Comment by sahaskn** [comment]
@stuartarchibald,
I tried the code below but it gave error:

from numba import njit, objmode
import numpy as np
import scipy.linalg as slg
@njit
def func(matrix):
    y = np.zeros(matrix.shape, dtype=np.float64)
    with objmode(answer='float64[:]'):
        y += slg.expm(matrix)
    return y

a = np.asarray([[0.0, 1.0], [1.0, 0.0]])
func(a)

error is : 
 File "/temp/ana/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/temp/ana/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/lhome/yubarajm/linux/Desktop/untitled0.py", line 19, in <module>
    func(a)

  File "/temp/ana/lib/python3.6/site-packages/numba/dispatcher.py", line 348, in _compile_for_args
    error_rewrite(e, 'typing')

  File "/temp/ana/lib/python3.6/site-packages/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)

  File "/temp/ana/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)

TypingError: Invalid type annotation on non-outgoing variables: {'answer'}.Suggestion: remove annotation of the listed variables.

I also tried with  "with objmode(answer='float64[:,:]':" but it gave same error

**Comment by sahaskn** [comment]
@stuartarchibald, I apologize for previous comment, which I've deleted. It works. The snippet of code is : 

from numba import njit, objmode
import numpy as np
import scipy.linalg as slg
@njit
def func(matrix):    
    with objmode(y='float64[:,:]'):
        y = slg.expm(matrix)
    return y

a = np.asarray([[0.0, 1.0], [1.0, 0.0]])
func(a) == slg.expm(a)
