### ISSUE TITLE
vectorize cuda array creation feature request

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3408]
Based on https://numba.pydata.org/numba-doc/latest/cuda/cudapysupported.html it is not possible to create an array using 'cuda'
Are there really no workarounds for array creation with vectorize 'cuda'?
It is working with guvectorize only if the array is previosuly allocated, but I did not manage to assign an array with vectorize (since I guess only scalars are working?)

**Comment by stuartarchibald** [comment]
Thanks for the query.

> is it not possible to create an array using 'cuda'

I think this is covered in the documentation here: http://numba.pydata.org/numba-doc/latest/cuda/memory.html, you can allocate an on device array directly with `numba.cuda.device_array` or `numba.cuda.device_array_like`.


> Are there really no workarounds for array creation with vectorize 'cuda'?

By the [contract specified by NumPy `ufunc`s](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html#optional-keyword-arguments), `@vectorize` will always create new memory unless the otherwise instructed. The use of the `out` kwarg will permit the use of an already existing memory allocation for output. Augmenting the example from the docs to demonstrate http://numba.pydata.org/numba-doc/latest/cuda/ufunc.html#example-basic-example:

```python
import math
from numba import vectorize, cuda
import numpy as np

@vectorize(['float32(float32, float32, float32)',
            'float64(float64, float64, float64)'],
           target='cuda')
def cu_discriminant(a, b, c):
    return math.sqrt(b ** 2 - 4 * a * c)

N = 10000
dtype = np.float32

# prepare the input
A = np.array(np.random.sample(N), dtype=dtype)
B = np.array(np.random.sample(N) + 10, dtype=dtype)
C = np.array(np.random.sample(N), dtype=dtype)
out = cuda.device_array_like(A) # allocate on device memory

cu_discriminant(A, B, C, out=out) # put result in on device memory

print(out.copy_to_host()) # copy the device memory containing the result back to the host to print
```

> It is working with guvectorize only if the array is previosuly allocated, but I did not manage to assign an array with vectorize (since I guess only scalars are working?)

I think this is covered by the above?

**Comment by cristipurdel** [comment]
I am trying to run the following code:

```
import numpy as np
import numba

""" MIGHT NEED SMTH EXTRA DEPENDING ON CUDATOOLKIT"""
if numba.cuda.is_available() == True:
    booCUDA = True
    print (numba.cuda.detect())
    targetOpt = 'cuda'
#    targetOpt = 'parallel'  
#    targetOpt = 'cpu'
else:
    booCUDA = False
    print ("No CUDA detected, parallel will be used")
#    targetOpt = 'parallel'
    targetOpt = 'cpu'
    


def vec_14(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14):
    t2 = 2.
    
    if booCUDA == True:
        t2 += 2.
        temp = numba.cuda.device_array(6, dtype=np.float)
        for i in range(temp.size):
            t2 += temp[i]
    else:
        t2 += 12.
        temp = np.ones(6).astype(np.float32)
        for i in range(temp.size):
            t2 += temp[i]
        
    return a1 + a2 + t2
    
dec_vec_14 = numba.vectorize(['float32(float32, float32, float32, float32, float32, \
                   float32, float32, float32, float32, float32, \
                   float32, float32, float32, float32)'], target = targetOpt)(vec_14)    

t = 20
N =2**t

for configT in ['threadsafe', 'tbb', 'omp']:
    
    numba.config.THREADING_LAYER = configT
    a1 = np.ones(N).astype(np.float32)
    a2 = np.ones(N).astype(np.float32)
    a3 = np.ones(N).astype(np.float32)
    a4 = np.ones(N).astype(np.float32)
    a5 = np.ones(N).astype(np.float32)
    a6 = np.ones(N).astype(np.float32)
    a7 = np.ones(N).astype(np.float32)
    a8 = np.ones(N).astype(np.float32)
    a9 = np.ones(N).astype(np.float32)
    a10 = np.ones(N).astype(np.float32)
    a11 = np.ones(N).astype(np.float32)
    a12 = np.ones(N).astype(np.float32)
    a13 = np.ones(N).astype(np.float32)
    a14 = np.ones(N).astype(np.float32)
    
    v14 = dec_vec_14(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14)
    print('numba.threading_layer(): ' + numba.threading_layer())
    print('pass with N=' + str(N))
```

On windows with cuda I am getting the following error:

 ```

  File "*\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "*\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "//*/Python/GitHub/3408.py", line 37, in <module>
    float32, float32, float32, float32)'], target = targetOpt)(vec_14)

  File "*\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 120, in wrap
    vec.add(sig)

  File "*\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 397, in add
    corefn, return_type = self._compile_core(devfnsig)

  File "*\Anaconda3\lib\site-packages\numba\cuda\vectorizers.py", line 17, in _compile_core
    cudevfn = cuda.jit(sig, device=True, inline=True)(self.pyfunc)

  File "*\Anaconda3\lib\site-packages\numba\cuda\decorators.py", line 102, in device_jit
    debug=debug)

  File "*\Anaconda3\lib\site-packages\numba\cuda\compiler.py", line 147, in compile_device
    return DeviceFunction(pyfunc, return_type, args, inline=True, debug=False)

  File "*\Anaconda3\lib\site-packages\numba\cuda\compiler.py", line 178, in __init__
    debug=self.debug, inline=self.inline)

  File "*\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "*\Anaconda3\lib\site-packages\numba\cuda\compiler.py", line 50, in compile_cuda
    locals={})

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 835, in _compile_bytecode
    return self._compile_core()

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 822, in _compile_core
    res = pm.run(self.status)

  File "*\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 244, in run
    stage()

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 477, in stage_nopython_frontend
    self.locals)

  File "*\Anaconda3\lib\site-packages\numba\compiler.py", line 1006, in type_inference_stage
    infer.propagate()

  File "*\Anaconda3\lib\site-packages\numba\typeinfer.py", line 860, in propagate
    raise errors[0]

TypingError: Unknown attribute 'device_array' of type Module(<module 'numba.cuda' from 'C:\\Users\\*\\Anaconda3\\lib\\site-packages\\numba\\cuda\\__init__.py'>)

File "3408.py", line 24:
def vec_14(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14):
    <source elided>
        t2 += 2.
        temp = numba.cuda.device_array(6, dtype=np.float)
        ^
```

2nd issue: targetOpt = 'parallel' is also not working on windows without cuda

3rd issue: numba.config.THREADING_LAYER = configT is always set as 'tbb', since I installed it as advised before

**Comment by stuartarchibald** [comment]
Great to see you trying some things out. Responding in order...

1. [Dynamic memory allocation from inside CUDA kernels is not supported](http://numba.pydata.org/numba-doc/latest/cuda/cudapysupported.html?highlight=dynamic#numpy-support) (the performance
characteristics of such behaviour often isn't desirable anyway). This is why the first error
is appearing, what is present in the code simply isn't supported (error message could do with
being improved, I've opened https://github.com/numba/numba/issues/3430 to track). [Shared, local and constant memory regions](http://numba.pydata.org/numba-doc/latest/cuda/memory.html?highlight=dynamic#shared-memory-and-thread-synchronization) are supported but are allocated once per kernel invocation.

2. What the code is doing is effectively illegal but again the error message could be improved, https://github.com/numba/numba/issues/3431 tracks. The `@vectorize` function is declared as returning a `float32` type, but because Numba cannot determine that that is always the case (because of the `booCUDA` branches, which do something that a) is invalid (see 1.) and b) is not supported in `nopython` mode, the function appears to get compiled with object mode handling present and so there is a signature mismatch between what the parallelisation code thinks it's getting (a function returning `float32`) and what is compiled (a function returning `pyobject`).

3. The usage of `numba.config.THREADING_LAYER` in the code is invalid. From the [docs](http://numba.pydata.org/numba-doc/latest/user/threading-layer.html#setting-the-threading-layer) 

   >  If the programmatic approach to setting the threading layer is used it must occur logically before any Numba based compilation for a parallel target has occurred.

   In the code sample, due to the use of `@vectorize` (which when supplied with a signature compiles at the site of declaration) compilation has either already occurred, or will occur on the first iteration of the loop in `configT`, either of which will set the threading layer to that declared/some default. Further, using e.g. `threadsafe` and `tbb` is mixing selection paradigms, the former is based on choosing a threading layer to obtain a particular guarantee for safe concurrent execution ("safe under threading" and as a result 'tbb' would likely be selected) where as the latter is selecting a layer based on the implementation name 'tbb'.

    There is at present no way to have more than one threading layer safely loaded into a single process, hence this is prevented by design. It is fine to spawn processes and load a different threading layer into each new process:

    ```python
    import multiprocessing as mp
    import numpy as np
    from numba import vectorize
    import numba

    def kernel(a, b):
        return a + b

    def target(a, b, threading_layer):
        print("Requesting threading_layer: %s" % threading_layer)
        numba.config.THREADING_LAYER = threading_layer
        func = vectorize(['float64(float64, float64)'], target='parallel')(kernel)
        print(np.sum(func(a, b)))
        print("Threading layer used: %s" % numba.threading_layer())

    def main(ctx):
        a = np.arange(1000.)
        b = np.arange(1000., 0. , -1)
        for TL in ['tbb', 'omp', 'workqueue']: # All 3 layers specifically *named*
            p = ctx.Process(target=target, args=(a, b, TL,))
            p.start()
            p.join()

    if __name__ == '__main__':
        ctx = mp.get_context('spawn')
        main(ctx)
     ```

Hope this helps?

**Comment by cristipurdel** [comment]
Thank you for opening additional issues for 1 & 2
For 3 I am getting the following error:
Traceback (most recent call last):

```
  File "<ipython-input-138-b9d1e386ad98>", line 1, in <module>
    runfile('***/3408_4.py', wdir='***')

  File "C:\Users\***\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\***\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "***/3408_4.py", line 27, in <module>
    main(ctx)

  File "***/3408_4.py", line 22, in main
    p.start()

  File "C:\Users\***\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\***\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\***\Anaconda3\lib\site-packages\cpuinfo\cpuinfo.py", line 70, in __init__
    super(_Popen, self).__init__(*args, **kw)

  File "C:\Users\***\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)

  File "C:\Users\***\Anaconda3\lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)

AttributeError: module '__main__' has no attribute '__spec__'
```

**Comment by cristipurdel** [comment]
I will close this issue since I am not using the latest Spyder due to the white window bug
