### ISSUE TITLE
Generator comprehension use inside jitted function unsupported/mishandled.

### ISSUE THREAD

**Issue by HenryDayHall** [numba/numba#3420]
The error message said to report the problem here, so here is a report. 
Problem; using `@jit` on a function that involves summing over a generator causes a crash.
Minimal (not) working example; 
```python
from numba import jit
import numpy as np

@jit
def problem_sum(oneD_array):
    N = len(oneD_array)
    custom_sum = sum(oneD_array[n]*oneD_array[(n+1)%N]
                     for n in range(N))
    return custom_sum


def good_sum(oneD_array):
    N = len(oneD_array)
    custom_sum = sum(oneD_array[n]*oneD_array[(n+1)%N]
                     for n in range(N))
    return custom_sum

if __name__ == "__main__":
    oneD_array = np.arange(5)
    print("Input ", oneD_array)
    good_out = good_sum(oneD_array)
    print("Intended out ", good_out)
    problem_out = problem_sum(oneD_array)
```

Sorry for the ugly code.
There are trivial work-rounds, but perhaps the developers want to know anyway?

**Comment by stuartarchibald** [comment]
Thanks for the report. The error:
```python
  File "<path>/numba/numba/pylowering.py", line 217, in lower_yield
    yp = self.generator_info.yield_points[inst.index]
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'
```
 is because generator comprehensions are not supported/handled correctly when consumed inside a jitted function, this should really be picked up in the IR legalization pass and turned into a suitable error message, or the implementation just fixed. Marking as a bug.

>There are trivial work-rounds, but perhaps the developers want to know anyway?

We are always grateful to hear about issues no matter how trivial to work around. It is very useful for the core development team to have reports of anything that is broken as it helps us understand what is broken in practice, how users are writing code and the number of users a problem might impact. Thank you for reporting!

**Comment by stuartarchibald** [comment]
The error handling/reporting is fixed by https://github.com/numba/numba/pull/4282
