### ISSUE TITLE
Support wrapping an existing CUDA context

### ISSUE THREAD

**Issue by pitrou** [numba/numba#3436]
The doc suggests that the `numba.cuda.cudadrv.driver.Context` constructor should not be called directly from user code. But sometimes it is desirable to have Numba use an already-existing CUDA context created by another library.

For example, in PyArrow we have to use the (slightly hackish) code:
```python
        device = numba.cuda.gpus[self.device_number]
        handle = ctypes.c_void_p(self.handle)
        context = numba.cuda.cudadrv.driver.Context(device, handle)
        class DummyPendingDeallocs(object):
            # Context is managed by pyarrow
            def add_item(self, *args, **kwargs):
                pass
        context.deallocations = DummyPendingDeallocs()
```

It would be nice if Numba provided an official, supported way to do that.
(cc @pearu)

**Comment by pitrou** [comment]
I'll let @pearu answer those questions, as he knows the details better than I do :-)

**Comment by pearu** [comment]
Yes, numba and arrow now use the same approach for managing CUDA context (retain for init, push-pop for setting).

It would be nice if numba Context class had a class or static method `from_device_and_handle` (or similar). The current solution in arrow defines `DummyPendingDeallocs` instance for numba context `deallocations` which is a bit hackish..

As I understand, the external memory manager (EMM) would allow optimizing several small cuMemAlloc calls to one `cuMemAlloc` that would define a CUDA memory pool. So, I think, yes, the EMM would be helpful for interacting with a to-be-implemented CUDA memory pool in Arrow.
But this seems to be a separate issue from creating numba Context instances using context handles managed by external libraries.

**Comment by sklam** [comment]
@pearu,
Is the goal expose arrow allocated memory in numba?  If so, could the `__cuda_array_interface__` (see [doc](http://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html) and https://github.com/numba/numba/pull/2860) be sufficient?

The numba Context class is considered as internal API and there are a lot of assumption in the numba code relying on numba being the sole creator and manager of the Context instances.

**Comment by pearu** [comment]
CC: @pitrou @wesm

pyarrow.cuda does not currently define an array object with device storage. Hence, `__cuda_array_interface__` would not be used within pyarrow.cuda. However, `pyarrow.cuda` has a record batch reader for CUDA buffers and `__cuda_array_interface__` could be used for arrow arrays with device storage indeed.

Within the pyarrow.cuda, the goal would be
1. to wrap numba allocated memory with arrow buffers, 
2. and vice-versa, create numba MemoryPointer from arrow CUDA buffers (memory allocated by arrow)
both in a zero-copy manner.
This issue is about point 2 and that would require creating numba Context within pyarrow.cuda.

Just to be clear about the current state, both points are already implemented and working.

One use case of point 2 is to create numba DeviceNDArray from arrow CUDA buffers. Now thinking about it, using `__cuda_array_interface__` might be indeed a way to bypass the point 2. To be certain, I'll need to give it a try..

Since numba is array-oriented (users are expected to work with DeviceNDArray, not with MemoryPointer) then it is understandable that numba Context belongs to internal API. Arrow, on the other hand, is oriented to using buffers and pyarrow.cuda defines CudaContext for CUDA buffers. So, for arrow and numba CUDA interoperability, pyarrow.cuda has to use numba internal API atm. I guess this issue is also about requesting to expose some numba internal API to arrow in a way that arrow could support the arrow-numba interop also in future.

**Comment by pearu** [comment]
I have used `__cuda_array_interface__` to implement `CudaNDArray`. `CudaNDArray` implements the same API as `DeviceNDArray` with the difference that device memory is held in arrow `CudaBuffer`.

For the record, to be fully compatible with numba, `CudaNDArray` had to implement the following properties:
```
__cuda_memory__ = True
__cuda_array_interface__
 _numba_type_
device_ctypes_pointer
device_pointer
```
as a minimum. Btw, `__cuda_ndarray__` seems to be noop.

**Comment by sklam** [comment]
> This issue is about point 2 and that would require creating numba Context within pyarrow.cuda.

It is possible to get a device pointer from an arbitrary CUDA Context and have it be usable in the current active context.  You can do that by using the `cuPointerGetAttribute` with`CU_POINTER_ATTRIBUTE_DEVICE_POINTER`.  See [docs](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__UNIFIED.html#group__CUDA__UNIFIED_1g0c28ed0aff848042bc0533110e45820c).  The function is used by numba to support the `__cuda_array_interface__` at https://github.com/numba/numba/blob/c24195c89e200fc36354ef0dd50d762886c5947c/numba/cuda/cudadrv/driver.py#L1659-L1666.

That way numba can use pyarrow allocated buffers without both libraries needing the other's CUDA context.
