### ISSUE TITLE
`isinstance(None, numba.types.NoneType)` is False

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#3590]
While playing with `generated_jit` I stumbled upon this unexpected behavior:

```python
>>> isinstance(None, numba.types.NoneType)

False
```

Clearly, standard python disagrees with this:

```python
>>> isinstance(None, type(None))

True
```

Is there a rational for this behavior or is this simply a bug?

**Comment by stuartarchibald** [comment]
Thanks for raising this. I think this is because Numba's type system mimics that of Python/NumPy but does not inherit from it (kind of indicated by MRO)
```
In [8]: numba.types.NoneType.__mro__                                                                                            
Out[8]: 
(numba.types.misc.NoneType,
 numba.types.common.Opaque,
 numba.types.abstract.Dummy,
 numba.types.abstract.Type,
 object)
```
Equally `isinstance(int, numba.types.Integer)` is `False`.

Relating this to `@generated_jit`, type inference will first try and compile the function with anything that can be represented as a literal value represented as such (integers, strings, slices and `make_function` [note: `None` is not in this set of types]), if this fails it will try to compile the function with everything represented by the Numba type system types. The 0.41.0 Release demo notebook (`Numba_041_release_demo.ipynb`) at https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks has a demonstration under the `Literal value support` section.

Another user asked a similar/related question yesterday, an example is also available there https://github.com/numba/numba/issues/3585#issuecomment-446302215

Hope this helps?

**Comment by david-zwicker** [comment]
I don't quite get the analogy between `isinstance(int, numba.types.Integer)` and the original problem with `None`. I though `int` is a type itself and would therefore not be expected to be an instance of `Integer`. However, I interpret `None` as a (single) instance of `NoneType` and would thus expect the `isinstance` check to return `True`.

**Comment by stuartarchibald** [comment]
Apologies, that's an error, should read something like "`isinstance(1, numba.types.Integer)` also returns `False`", same reason as above applies.

**Comment by stuartarchibald** [comment]
@david-zwicker you may be interested in the `For Developers` second of this notebook relating to the 0.43 release https://github.com/numba/numba-examples/blob/master/notebooks/Numba_043_release_demo.ipynb
