### ISSUE TITLE
Add support for Numpy 1.16

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#3741]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Running the test suite 

`python -m numba.runtests -m 4`

shows 77 fails under Numpy 1.16, but none under 1.15.

Many of them are related to the following:
datetime behaviour up to 1.15 

```
np.datetime64('NaT', 'Y')==np.datetime64('NaT', 'Y')
__main__:1: FutureWarning: In the future, 'NAT == x' and 'x == NAT' will always be False.
True
```
datetime behaviour under 1.16

```
np.datetime64('NaT', 'Y') == np.datetime64('NaT', 'Y')
False
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is fundamentally because NumPy 1.16 is not yet supported. Once packages are widely available (i.e. via conda) the above will get fixed and NumPy 1.16 will be added to the public and private CI test matrix. Going to change the title to reflect that this is a support issue.
