### ISSUE TITLE
Numba vectorize take 2d array

### ISSUE THREAD

**Issue by julepe** [numba/numba#3787]
Hi, I'm tryng to use the vectorize decorator in this function like this

```python
@vectorize([float64(float64[:]])
def calcula(paras):
       
       r=sum(para)
       return r
```

where paras is 
```
para=float64([1,1,1,1,1,1,1])
```
and I'm getting the error 

```
NotImplementedError: array(float64, 1d, A) cannot be represented as a Numpy dtype
```

and if I do 
```python
@vectorize([float64(float64)])
def calcula(paras):
       
       r=sum(para)
       return r
```
the function doesn't understand that the input is ONE 7-size array

Someone knows what can I do?

**Comment by stuartarchibald** [comment]
NOTE: Updated issue with markdown syntax.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue you are experiencing is because `@vectorize` is creating a Universal function ([ufunc docs](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html)), which operates element-wise on the inputs. The function declared:
```python

@vectorize(['float64(float64[:])'])
def calcula(paras):
       r=sum(para)
       return r
```
specifies one of the inputs is an array type (`float64[:]`) hence the error message reported.

What is needed is a Generalized Universal Function (`@guvectorize` decorator), Numba documentation for them is here: http://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-guvectorize-decorator

It should be noted with `@guvectorize` that the functions return void and results must be written into one of the arguments. Here's an example of the function above as a `@guvectorize` function:
```python
from numba import guvectorize, float64
import numpy as np

@guvectorize([(float64[:], float64[:])], '(n), (m)')
def calcula(paras, result):
       result[0] = np.sum(paras)

dt = np.float64
x = np.array([1, 1, 1, 1, 1, 1, 1], dt)
res = np.empty((1,), dt)
tmp = np.empty_like(res)
calcula(x, res)
print(res)
```
