### ISSUE TITLE
is None branch incorrectly pruned in numba 0.43!

### ISSUE THREAD

**Issue by analog-cbarber** [numba/numba#3879]
The following code does not execute the is None branch in numba 0.43 on Mac OSX:

~~~python
import numpy as np
import numba

@numba.jit
def bug(a,b):
    if a.ndim == 1:
        if b is None:
            # FIXME Numba 0.43 - this branch is not executed when run using numba 0.43!
            print('should get here')
            return None
        print('************** BUG')

    return []

bug(np.arange(10),None)
~~~

Obviously, this is **VERY BAD**.

Here is my conda environment:

~~~sh
$ conda list
# packages in environment at /Users/cbarber/miniconda3/envs/numba-bug:
#
# Name                    Version                   Build  Channel
blas                      1.1                    openblas    
ca-certificates           2019.3.9             hecc5488_0    
certifi                   2019.3.9                 py36_0    
intel-openmp              2019.1                      144  
libblas                   3.8.0                     4_mkl    
libcblas                  3.8.0                     4_mkl    
libcxx                    7.0.0                h2d50403_1    
libffi                    3.2.1             h0a44026_1005    
libgfortran               3.0.1                         0    
liblapack                 3.8.0                     4_mkl    
llvm-meta                 7.0.0                         0    
llvmlite                  0.28.0           py36hf292337_0    
mkl                       2019.1                      144  
ncurses                   6.1               h0a44026_1002    
numba                     0.43.0           py36h0a44026_0    h
numpy                     1.15.4          py36hbb3c62a_1002    
openblas                  0.3.3             hdc02c5d_1001    
openssl                   1.1.1b               h1de35cc_1    
pip                       19.0.3                   py36_0    
python                    3.6.7             h8dc6b48_1004    
readline                  7.0               hcfe32e1_1001    
scipy                     1.2.1           py36_blas_openblash486cb9f_0    
setuptools                40.8.0                   py36_0    
sqlite                    3.26.0            h1765d9f_1001    
tk                        8.6.9             ha441bb4_1000    
wheel                     0.33.1                   py36_0    
xz                        5.2.4             h1de35cc_1001    
zlib                      1.2.11            h1de35cc_1004    
~~~

**Comment by stuartarchibald** [comment]
Thanks for the report. I think I've got to the bottom of what is going on... The code sample will correctly have the branches pruned during analysis, however, the `if b is None` conditional gets rewritten to a `const(0)` just as a place holder so that type inference can continue to work. The issue in this specific case is that because of the untyped list that is returned, the fall back object-mode compilation and slow execution path is used, but with the switched out conditional `const(0)` in the IR as the fall back pipeline IR is only backed up at the block and not node level. This means there's a branch operation on a `const(0)`, which inevitably takes the wrong branch.

The root cause of this problem is the same as that for a number of the inline closure pass bugs where an object mode fallback takes place, i.e. IR nodes being mutated here's one such of a number of duplicate cause bug reports: https://github.com/numba/numba/issues/3803

Will fix this for 0.44 which should be a short release cycle in part to catch things like this :)

**Comment by analog-cbarber** [comment]
Thanks! Look forward to trying out the fix...

**Comment by teoliphant** [comment]
It looks like this issue may also affect umap-learn which doesn't currently work with the 0.43 release (but does with the 0.42 release).

**Comment by stuartarchibald** [comment]
Thanks @teoliphant, there's some related discussion starting here https://github.com/lmcinnes/umap/issues/209#issuecomment-474282286, essentially, bug fix release on it's way shortly (there's a few other things that need fixing too!).

**Comment by seibert** [comment]
Yeah, our plan is to get a patch release candidate out by the end of the week.
