### ISSUE TITLE
Feature Request: unicode support in NumPy arrays.

### ISSUE THREAD

**Issue by werhoog** [numba/numba#4018]
Here is the code:

```
import numpy as np
import numba

x=np.array(['some','text','this','is'])

@numba.jit(nopython=True)
def numba_str(txt):
    x=0
    for i in xrange(txt.size):
        if txt[i]=='text':
            x += 1
    return x

print numba_str(x)
```

###-----------
#but return error, and if I remove nopython=True, everything went well. Why? What should I do if #I want to use nopython=True

**Comment by esc** [comment]
@werhoog thanks for using Numba and taking the time to submit this bug report.

**Comment by esc** [comment]
I have updated your comment to include syntax highlighting  so as to increase legibility.

**Comment by esc** [comment]
@werhoog here is a suggestion, maybe you could use plain python lists instead of NumPy arrays:

```
import numba

x = ['some','text','this','is', 'text', 'bla bla bla']


@numba.jit(nopython=True)
def numba_str(txt):
    x = 0
    for i in range(len(txt)):
        if txt[i] == 'text':
            x += 1
    return x


print(numba_str(x))
```

**Comment by seibert** [comment]
Just to add a bit: The reason the original example does not work is that it creates a NumPy array with `S4` (fixed width string of length 4) dtype, which we are not correctly casting to the internal Unicode type.  Elements of this NumPy array will have the Numba type of `CharSeq` or `UnicodeCharSeq`, so we need a casting rule from that to `UnicodeType`.

Casting the other way seems problematic, because a Unicode string longer than the fixed width dtype will be truncated, which NumPy appears to do without even warning:

``` python
In [35]: x = np.array(['some','text','this','is'])

In [36]: x[2]
Out[36]: 'this'

In [37]: x[2] = 'aaa'

In [38]: x[2]
Out[38]: 'aaa'

In [39]: x[2] = 'aaaaaaaaa'

In [40]: x[2]
Out[40]: 'aaaa'
```

**Comment by seibert** [comment]
Another implementation note: the cast from `CharSeq -> UnicodeType` will (unfortunately) need to copy the data, because the Numpy array storage for the character sequence is mutable, and the rest of the Unicode string implementation is assuming immutable storage, so views of substrings are always safe.

**Comment by werhoog** [comment]
Thanks!  So it is never recommended that use array to store string.
And I also tested nopython=True, since nopython=True runs faster than other module.
like this:
string_list = ['some','text','this','is', 'text', 'bla bla bla']
@nb.jit(nopython=True)
def func4(string_list):
    diff = 0
    for string in string_list:
        for j in string:
            if j != "A":
                diff += 1
    return diff
#test
%timeit func4(string_list)

#So I want to compare each char in each string in the string_list. But numba also failed.
And I also found:1) nopython=True run faster than other module; 2)If use string as input of the function, normal function runs faster than decoration with nopython=False.
So numba seems prefer array storing number?

**Comment by esc** [comment]
@werhoog indeed, Numba prefers numerical data over text.

**Comment by seibert** [comment]
Just to close the loop on this, we are looking address this use case in the near future by creating a "typed list", which will be the most efficient way to pass things like lists of strings into nopython mode.

Fixed width string dtypes are not something we plan to add anytime soon, unless someone has a compelling reason for them.

**Comment by hoangthienan95** [comment]
Hello, 
it took me (new to numba and loving it) a while to figure out that numba doesn't like string arrays, even though it was clearly stated [here](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html) under _Scalar Types_. I want to chime in and ask some questions regarding this.

One of the possible use case for fixed width string dtype can be in genomics, when researchers are handling genotype arrays. In this case, I want to permute the *outside_geno* column (500k rows) to do a permutation test and couldn't just use `np.random.permutation` with `nopython` mode so I worked around it . Below are my performance results. The vanilla numpy function outperforms both the numba-assisted function. Does this result surprise you? What can I do to make it faster? I'm doing around 10 million iteration so any performance boosts would be so sweet. TIA!

![image](https://user-images.githubusercontent.com/25307953/57540184-1af33080-731a-11e9-8bbe-285d04d8701b.png)
![image](https://user-images.githubusercontent.com/25307953/57540266-568dfa80-731a-11e9-8899-423f3248da49.png)

**Comment by luk-f-a** [comment]
just for future reference, I want to leave a quick example where lists won't do. any known workarounds for this case?

```python
import numpy as np
from numba import njit

array_len = 3
values = (20, 'square')
keys = np.dtype([('value', 'i8'), ('op', 'U12')], align=True)
my_array = np.array([values for _ in range(array_len)], dtype=keys)

@njit
def apply_op(data):
    out = 0.
    for i in range(len(data)):
        if data[i].op == 'square':
            out += data[i].value **2
        else:
            out += data[i].value 
    return out
```

**Comment by seibert** [comment]
Not any good workarounds, since your data has the strings packed into the array.  This is a case where we do need to be able to create string views on NumPy storage.  We might have to accept that while the view is immutable, the underlying storage is not and there may be inconsistencies if the string part of the array is modified during use.

Thanks for show your use case!  This is helpful to see.

**Comment by pearu** [comment]
Heads up: the example code, when adopted to Python 3, as well as the example in https://github.com/numba/numba/issues/4018#issuecomment-508947403 now work when using PR #4425 .

**Comment by cristipurdel** [comment]
will this work with 'cuda' @vectorize?
