### ISSUE TITLE
Performance with two parallel functions

### ISSUE THREAD

**Issue by cdeil** [numba/numba#4031]
@watsonjj tried to optimise a computation and was surprised that when splitting the computation into two functions with `jit(nopython=True, parallel=True)` gives much worse performance than when putting all code in a single function.

A minimal example showing the effect is here:
https://gist.github.com/cdeil/f39cf7fc659f16c04ecc34ecef7ee024

Is this expected behaviour for Numba, or something that can be improved?
(a guess: #2680 or #3750 might be relevant?)

Is there a way to debug and understand the performance differences in the different ways to write the same computation for the examples in https://gist.github.com/cdeil/f39cf7fc659f16c04ecc34ecef7ee024 ?

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect the reason for the performance difference is because the "two function" variants are exhibiting nested parallelism, i.e. a function compiled with `parallel=True` calls a function that is also compiled with `parallel=True`, this resulting in a lot of resource and scheduling contention (it's an N^2 thread problem, but in practice the Numba threading backends should prevent over subscription and just schedule all the work in the same thread pool, with all the contention that creates).

If you make `sum_1d_array` simply a `@njit` compiled function, i.e. `parallel=False`, the performance of the `sum_two_functions*` versions match/are similar to their `sum_single_function*` counterparts. The reason for this is fundamentally that the parallelisation passes do not traverse function calls when `prange` is used, the loop body is scheduled as explicitly parallel.

Related issue: https://github.com/numba/numba/issues/3551.

I'm beginning to wonder if we could/should issue a warning when this is detected.
