### ISSUE TITLE
Question: Efficiently shuffle array of fixed-width strings

### ISSUE THREAD

**Issue by hoangthienan95** [numba/numba#4086]
Hello,
Along the lines of #4018 , if I want to shuffle a big array of fixed-width strings, should I just use `np.random.permutation`? Using numba-assisted function to shuffle the index (~30% faster) and then apply mask kills any speed gains and is even slower than just using numpy directly on strings. If I need to do around 10 million permutations, is there any way to speed it up more than what I currently have?

```python

@numba.jit(nopython=True)
def permute_index_arr(index):
    return np.random.permutation(index)

repeat_times = [200_000,200_000,200_000]
arr = np.repeat(["AA", "BB", "CC"], repeat_times)

for i in range(1000):
    permuted = np.random.permutation(arr) # 67 iters/sec 


index = np.arange(arr.shape[0])

# permuting only the index
for i in range(1000):
    permute_index_arr(index) # 88 iters/sec

for i in range(1000):
    permuted = arr[permute_index_arr(index)] # 56 iters/sec
```

**Comment by seibert** [comment]
I don't see a way to speed this up.  The results also seem to be pretty dependent on hardware, it seems.  On my laptop, I get 63 iters/sec, 110 iters/sec, and 86 iters per sec (using %timeit), so permuting the index and then gathering the results is 30% faster than permuting the string array directly for me.  However, you should go with your benchmarks since they reflect the hardware you have.

Numba is generally unlikely to provide much benefit when compiling single NumPy functions as our implementations are very similar to NumPy's.
