### ISSUE TITLE
Error: "cannot import vectorize from numba" after "python numba_test.py"

### ISSUE THREAD

**Issue by sam02151015** [numba/numba#4101]
Hi there, 

I am running on Windows 10, using Python 3.7.3, numpy 1.16.3, numba 0.43.1, llvmlite 0.28.0.

I installed numba package using "vanilla" miniconda with the command "conda install numba".
After that I ran a python console, imported numba and vectorize from numba with no problem, as seen in the attached figure "first_work.png".

![first_work](https://user-images.githubusercontent.com/8906261/58030101-f5b9ab80-7aeb-11e9-9e0b-461f1a5376af.png)

However, when I wrote
"import numba" into "numba_test.py" 
and ran
"python numba_test.py" in the prompt, it generated the error "cannot import name 'vectorize' from 'numba'"; 
since then if I go to python console and run "import numba" command, it complains: "cannot import name 'vectorize' from 'numba'". 

![doesnt_work_after_python_numba_test py](https://user-images.githubusercontent.com/8906261/58030143-08cc7b80-7aec-11e9-9faa-223f3fda5e72.png)

I tried to uninstall miniconda and reinstall to avoid the error, but the same error still shows up.

I also tried to search on google, with no help... I also tried this on 2 other Linux machines, the error seems reproducible. 

Is any solution to this error?

Thanks,
Sc

**Comment by seibert** [comment]
I'm not 100% certain what the problem is here, but I suspect you have accidentally created a circular import based on the line at the end of the second screenshot:

```
File "C:\Users\ksrlab\numpy.py", line 1, in <module>
```

This looks like you have a file in your working directory called `numpy.py`, which will in some cases hide the system `numpy`.  This creates a situation that might go something like this:

1. Your script imports numba.
2. Numba attempts to import numpy.
3. Python resolves the numpy import by loading your local `numpy.py` instead of the site-packages numpy.
4. Your numpy.py file tries to import numba.

Rather than go into an infinite import loop, Python breaks the cycle, but this results in a partial import and `vectorize` cannot be found.

The fix is to rename your local script files so they do not match the names of system packages like `numpy`.

Hope that helps!

**Comment by sam02151015** [comment]
> 
> 
> I'm not 100% certain what the problem is here, but I suspect you have accidentally created a circular import based on the line at the end of the second screenshot:
> 
> ```
> File "C:\Users\ksrlab\numpy.py", line 1, in <module>
> ```
> 
> This looks like you have a file in your working directory called `numpy.py`, which will in some cases hide the system `numpy`. This creates a situation that might go something like this:
> 
>     1. Your script imports numba.
> 
>     2. Numba attempts to import numpy.
> 
>     3. Python resolves the numpy import by loading your local `numpy.py` instead of the site-packages numpy.
> 
>     4. Your numpy.py file tries to import numba.
> 
> 
> Rather than go into an infinite import loop, Python breaks the cycle, but this results in a partial import and `vectorize` cannot be found.
> 
> The fix is to rename your local script files so they do not match the names of system packages like `numpy`.
> 
> Hope that helps!

Thanks for pointing this to me, I do find a file named numpy.py in the current directory. After removal of this file and the corresponding pyc file, it works.
