### ISSUE TITLE
Please release wheels for 'cp27-cp27m-manylinux1-*'.

### ISSUE THREAD

**Issue by tseaver** [numba/numba#4139]
By default, python2.7 is configured without `--enable-unicode=ucs4`:  the default for that option is `ucs2`.  The currently-released set of [numba wheels](https://pypi.org/project/numba/0.44.0/#files) do not include Linux binaries which are compatible with this default build (the compatible suffix would be `-cp27-cp27m-manylinux1_i686.whl` or `-cp27-cp27m-manylinux1_x86_64.whl`).

Please consider releasing wheels which support the default Python 2.7 build configuration.

**Comment by stuartarchibald** [comment]
[Python 2.7 reached EOL on January 1st, 2020](https://github.com/python/devguide/pull/344) and [Numba 0.47 was the last release to support Python 2.7](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/g6wF8D-jV_o). Closing this issue as it is Python 2.7 specific, if this problem is reproducible on Python 3 with Numba >= 0.48 then please reopen it. Many thanks!
