### ISSUE TITLE
actually slow down the slicing the np.array

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4142]
```
def delay1(x,d):
	'''
	time-series value of x d days ago
	x: such as open/high/low/close ...
	d: the delay window 
	'''

	return x[:len(x)-d]
#466 ns ± 11.7 ns per loop
```

```
@jit(nopython=True)
def delay1_jit(x,d):
	'''
	time-series value of x d days ago
	x: such as open/high/low/close ...
	d: the delay window 
	'''

	return x[:len(x)-d]
#628 ns ± 9.98 ns per loop
```

not helping for slice the np.array, actually slow down,how can I fix this?

**Comment by synapticarbors** [comment]
I think what you might be seeing here is the perhaps the added overhead time to dispatch on the correct types on a function that does little work. When the jit'd version is called from another `nopython` function, you can see that the true cost is greatly reduced:

```python
def delay1(x,d):
    '''
    time-series value of x d days ago
    x: such as open/high/low/close ...
    d: the delay window 
    '''

    return x[:len(x)-d]

delay1_jit = nb.jit(nopython=True)(delay1)

def test(x, N):
    y = np.empty(N)
    for i in range(N):
        y[i] = delay1(x, i)[0]
        
    return y

@nb.jit(nopython=True)
def test_jit(x, N):
    y = np.empty(N)
    for i in range(N):
        y[i] = delay1_jit(x, i)[0]
        
    return y
```

and then:

```python
N = 500
x = np.random.normal(size=(N,))

%timeit delay1(x, 10)
# 340 ns ± 4.76 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit delay1_jit(x, 10)
# 476 ns ± 2.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit test(x, 100)
# 47.6 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit test_jit(x, 100)
# 710 ns ± 12.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

You can see that running the jitted version 100 times takes a little more than 2x calling it once, because presumably you are only paying the overhead a single time and not with each call.

In general the fewer times you cross the numba/python boundary, the more benefit you'll see from numba. It usually makes the most sense to try to do the bulk of your problem in numba and then return the results to python infrequently.

**Comment by isaac-you** [comment]
thank you so much

**Comment by esc** [comment]
@isaac-you thanks for asking and thanks for answering @synapticarbors .
