### ISSUE TITLE
ImportError: cannot import name '_typeconv', Jetson Nano

### ISSUE THREAD

**Issue by lesreaper** [numba/numba#4146]
I'm using a Jetson Nano, Ubuntu 18.04, ARM Processor. 

Installed LLVM 8.0 via source via these directions: 
https://gist.github.com/jed-frey/ba40ff83523296bc8355f05befb28da9

I didn't add the patches since those were for v7 of LLVM. The only other thing I noticed about this install is that it used Python2.7 for the executable, and it wouldn't accept a Python3 executable flag on the cmake. I don't know if that affects anything, or it just needs that or the build. Virtual envs are Python 3 only at this point.

Then LLVM lite installed into Python3 virtual env via
`pip install llvmlite`

Installed Numba in the Python3 virtual env via:
```
git clone git://github.com/numba/numba.git
python setup.py install
```

When I go to run`import numba`, this is what I get:
```
Traceback (most recent call last):
  File "/home/nvidia/numba/numba/typeconv/typeconv.py", line 6, in <module>
    from . import _typeconv
ImportError: cannot import name '_typeconv'

```

**Comment by seibert** [comment]
This looks like Numba has either not been built, or was not installed where it should have been.  Can you elaborate on this part of your description?  "The only other thing I noticed about this install is that it used Python2.7 for the executable, and it wouldn't accept a Python3 executable flag on the cmake."

What part was using Python 2?  Are you building llvmlite in your Python 3 virtualenv?

**Comment by lesreaper** [comment]
So, it has to be installed in the home directory `~/` was the problem it seems, at least to fix this error. That wasn't explicitly stated in the install docs, but easily fixed.

The LLVM install that I linked above (the gist), when you do the `Cmake build` on it, it uses Python2 as the executable, and I couldn't find a way to change that.

I installed llvmlite using the python3 virtual env.

**Comment by seibert** [comment]
OK, the Python used in the LLVM build doesn't impact its usage in llvmlite, so that should not be the issue.

I'm unclear why the location of the Numba source tree would impact the error you are seeing, unless there is something unusual about your environment.  Where was it located before you moved it?

**Comment by stuartarchibald** [comment]
That there was an import error relating to `_typeconv` suggests that this is not a recent numba build in use. Version 0.43 got this patch https://github.com/numba/numba/pull/3693, as `_typeconv` is the first C extension that gets loaded by Numba, the patch catches a failed import and prints out an message explaining what the actual problem is (broken Numba build). I think this all points to some sort of environment related mix up?

> The LLVM install that I linked above (the gist), when you do the Cmake build on it, it uses Python2 as the executable, and I couldn't find a way to change that.

LLVM CMake should detect the first `python` on the path.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
