### ISSUE TITLE
can not assign Dict value to a variable

### ISSUE THREAD

**Issue by ccl-private** [numba/numba#4168]
![Screenshot from 2019-06-12 15-10-37](https://user-images.githubusercontent.com/36214675/59330529-4eafe480-8d24-11e9-9813-0f275c87621a.png)
![Screenshot from 2019-06-12 15-11-27](https://user-images.githubusercontent.com/36214675/59330562-68e9c280-8d24-11e9-8112-56d3ff7cd5ed.png)
I am new to numba, who can tell me how to assign a Dict value to a variable?

**Comment by stuartarchibald** [comment]
Thanks for the report. Which version of Numba are you using? I think if you update to version 0.44 you'll see an error message when Numba tries to compile your code that looks like:
```
Writing to a DictType[unicode_type,int32] defined in globals is not supported as globals are considered compile-time constants.
```
essentially, what you have written is correct, it's just that accessing some types of globals from compiled functions not supported, `typed.Dict` being one of these. If you alter your code so that `test()` takes the dictionary as an argument your code will work fine, for example:
```python
from numba.typed import Dict
from numba import types, njit

pic_map = Dict.empty(types.unicode_type,  types.int32)

for i in range(256):
    s = hex(i)
    s = s[2:len(s)]
    if len(s) == 1:
        s = "0" + s
    pic_map[s] = i

@njit
def test(pmap):
    t1 = pmap['aa']
    print(t1)

test(pic_map)
```
hope this helps.

**Comment by ccl-private** [comment]
It worked, thanks~

**Comment by stuartarchibald** [comment]
Thanks for confirming, closing.
