### ISSUE TITLE
__cuda_array_interface__ is not compliant with the standard

### ISSUE THREAD

**Issue by leofang** [numba/numba#4175]
**UPDATE: reporting two issues on `__cuda_array_interface__`**

First, currently it's impossible for `'strides'` to be `None`, and it is always there instead of being optional:

https://github.com/numba/numba/blob/a97dc18f3e5d69429949e557bc98ec513f81b04c/numba/cuda/cudadrv/devicearray.py#L120

If the array is C contiguous, as in most cases, this is not complying with the standard:
> The following are optional entries:
> - strides: None or (integer, ...)
>  A tuple of int (or long) representing the number of bytes to skip to access the next element at each dimension. If it is None, the array is assumed to be in C-contiguous layout.

Second, if the input is a 0-size array, the device pointer given by Numba's `__cuda_array_interface__['data'][0]` is `None`. But this leads to an error when accessing the pointer on the C/Cython side. For example, `PyLong_AsVoidPtr(None)` fails, and so it requires extra logic to handle this special case. In fact, this again breaks the spec, which requires an `int` or `long`:
> - data: (integer, boolean)
> The data is a 2-tuple. The first element data pointer as a Python int (or long). The data must be device-accessible. The second element is the read-only flag as a Python bool.

I suggest to revise the standard, as currently this edge case is not clearly defined. Relevant to #4140. By the way, CuPy uses `0` for this case (cupy/cupy#2104), which makes perfect sense at the C level.

**Comment by leofang** [comment]
I guess my ultimate question is how to tell whether a GPU array with `__cuda_array_interface__` is C-/F- contiguous or not, and having a non-default `'strides'` made it harder to tell. For example, it's impossible to do this:
```python
if 'strides' not in __cuda_array_interface__.keys() or __cuda_array_interface__['strides'] is None:
    # C contiguous, do something
else:
    # either F contiguous or not contiguous at all, do other thing
```
but maybe I am missing something obvious?

**Comment by leofang** [comment]
Added a second issue on `__cuda_array_interface__['data'][0]`, see the updated post.

**Comment by leofang** [comment]
Linking my comment in Numba's Gitter channel: https://gitter.im/numba/numba?at=5d7ba9db5d40aa0d7d2d3bd9

**Comment by leofang** [comment]
Linking to my comment in Numba's Gitter channel: https://gitter.im/numba/numba?at=5d7baca65d40aa0d7d2d4e83, copied and pasted below for reference:

> On the pointer to zero-size array, Numba is not compliant, so a code fix is sufficient. Spec is good here.

Sorry, I was wrong. Spec should be modified for this corner case, and as I mentioned in the issue, following CuPy's approach and set the pointer to 0 would be nice.

**Comment by leofang** [comment]
@pentschev @stuartarchibald Let me know if this patch below looks good to you. If it's acceptable I'll write a few tests and create a PR. Thanks
```diff
diff --git a/numba/cuda/api.py b/numba/cuda/api.py
index 7644d6c..d503099 100644
--- a/numba/cuda/api.py
+++ b/numba/cuda/api.py
@@ -38,7 +38,7 @@ def from_cuda_array_interface(desc, owner=None):
             raise NotImplementedError('Masked arrays are not supported')
 
     shape = desc['shape']
-    strides = desc.get('strides')
+    strides = desc.get('strides', None)
     dtype = np.dtype(desc['typestr'])
 
     shape, strides, dtype = _prepare_shape_strides_dtype(
diff --git a/numba/cuda/cudadrv/devicearray.py b/numba/cuda/cudadrv/devicearray.py
index cd1a027..3235387 100644
--- a/numba/cuda/cudadrv/devicearray.py
+++ b/numba/cuda/cudadrv/devicearray.py
@@ -45,7 +45,7 @@ def verify_cuda_ndarray_interface(obj):
             raise AttributeError('%s must be of type %s' % (attr, typ))
 
     requires_attr('shape', tuple)
-    requires_attr('strides', tuple)
+    #requires_attr('strides', tuple)
     requires_attr('dtype', np.dtype)
     requires_attr('size', six.integer_types)
 
@@ -116,10 +116,20 @@ class DeviceNDArrayBase(object):
 
     @property
     def __cuda_array_interface__(self):
+        if self.device_ctypes_pointer.value is not None:
+            ptr = self.device_ctypes_pointer.value
+        else:
+            ptr = 0
+
+        if array_core(self).flags['C_CONTIGUOUS']:
+            strides = None
+        else:
+            strides = tuple(self.strides)
+
         return {
             'shape': tuple(self.shape),
-            'strides': tuple(self.strides),
-            'data': (self.device_ctypes_pointer.value, False),
+            'strides': strides,
+            'data': (ptr, False),
             'typestr': self.dtype.str,
             'version': 1,
         }
```

**Comment by stuartarchibald** [comment]
The proposed patch seems reasonable to me, @sklam @seibert any view ?

**Comment by pentschev** [comment]
Sorry for not replying earlier. Yes, I agree the patch looks good, I think this addresses our previous discussion.

@leofang thanks a lot for working on that!

**Comment by stuartarchibald** [comment]
> @leofang thanks a lot for working on that!

Yes indeed @leofang, thanks for your efforts on this, much appreciated.

**Comment by leofang** [comment]
@stuartarchibald could you reopen #4140 for now? The PR #4609 should fix it. Thanks.

**Comment by gchanan** [comment]
I'm confused about the new standard, but maybe I'm missing something obvious.

@leofang seems to suggest above, and in the PyTorch PR (https://github.com/pytorch/pytorch/pull/24947) that passing the strides for a C-contiguous array is non-conforming with the standard.

The current wording is not clear:
```
If strides is not given, or it is None, the array is in C-contiguous layout. Otherwise, a tuple of int (or long) is explicitly given for representing the number of bytes to skip to access the next element at each dimension.
```

It depends on how you interpret the word "Otherwise" (otherwise the strides are given or otherwise the array is not C-contiguous).

I'm also confused about the discussion around C-vs-Fortran contiguous on this thread.  Can't you tell if strides are C-vs-F (or not) contiguous just by looking at them and the itemsize?  Related to that, I don't understand why you would enforce this as part of the standard vs just treating it as an optimization.  It's strange to me that PyTorch needs to be careful to check that the strides are contiguous and branch rather than just always pass the strides.

**Comment by gchanan** [comment]
Another ambiguity:
> For zero-size arrays, use `0` here.

The term "zero-size arrays" is never defined.  I assume it means something like "for arrays with no elements (i.e. product of shapes is 0)".

Also, again, we need special handling of this in PyTorch for unclear reasons.  Why can't I pass any addressable memory here, it shouldn't be used?

**Comment by leofang** [comment]
> @leofang seems to suggest above, and in the PyTorch PR ([pytorch/pytorch#24947](https://github.com/pytorch/pytorch/pull/24947)) that passing the strides for a C-contiguous array is non-conforming with the standard.

Yes. For C-contiguous arrays, the v2 protocol requires you either don't set `strides`, or set `strides` to `None`.

> The current wording is not clear:
> 
> > If strides is not given, or it is None, the array is in C-contiguous layout. Otherwise, a tuple of int (or long) is explicitly given for representing the number of bytes to skip to access the next element at each dimension.
> 
> It depends on how you interpret the word "Otherwise" (otherwise the strides are given or otherwise the array is not C-contiguous).

"Otherwise the array is not C-contiguous."

I'm sorry that you see a room for alternative interpretations. To me this wording was a compromise that we made, see the long discussions in the PR #4609.

> I'm also confused about the discussion around C-vs-Fortran contiguous on this thread. Can't you tell if strides are C-vs-F (or not) contiguous just by looking at them and the itemsize? 

Two reasons:
1. This is what NumPy does in `__array_interface__`, and we intend to follow NumPy as closely as possible.
2. You need a lengthier code just to loop over twice in order to tell it's C or F. Why don't you keep this info in the exchange format so as to save some trouble for every downstream consumers? 

> Related to that, I don't understand why you would enforce this as part of the standard vs just treating it as an optimization. It's strange to me that PyTorch needs to be careful to check that the strides are contiguous and branch rather than just always pass the strides.

You must already have a flag somewhere to indicate the contiguity, why don't you just use it? And if there's no such a flag, it's a design flaw in PyTorch I am afraid, as most of the time we want to use C-contiguous arrays in CUDA, and likewise F arrays are exceptions.

> The term "zero-size arrays" is never defined. I assume it means something like "for arrays with no elements (i.e. product of shapes is 0)".

What's the ambiguity here? I don't get it.

> Also, again, we need special handling of this in PyTorch for unclear reasons. Why can't I pass any addressable memory here, it shouldn't be used?

This is to comply with C/C++ practice. Typically a pointer is either explicitly or implicitly `NULL`-initialized prior to being passed to `malloc` or `cudaMalloc`. If it's a zero-size (or zero-length if you like) memory, then most likely you get a `NULL` back (at least in CUDA it's true). Thus, a common practice is to check whether a pointer is `NULL` or not before using it. For consumers parsing this info in C/C++/Cython, having this safeguard in place helps you ensure it won't be used.

**Comment by dhirschfeld** [comment]
> It depends on how you interpret the word "Otherwise" (otherwise the strides are given or otherwise the array is not C-contiguous).
>> "Otherwise the array is not C-contiguous."

That's absolutely not how I interpret it. I actually don't think it's a question of interpetation at all - it says *"otherwise, a tuple of int is given"* it ***does not*** say anything about whether the tuple of ints in C-continguous, F-contiguous or non-contiguous. In the absence of explicitly disallowing contiguous strides they are therefore allowed.

i.e. the wording as written allows the `strides` parameter, if given, to be C-, F- or non-contiguous. It only specifies that if absent or None then it is assumed to be C-contiguous.

Assuming that if present the strides are ***not*** C-contiguous is reading into it an interpretation not explicitly supported by the wording.

**Comment by gchanan** [comment]
> I'm sorry that you see a room for alternative interpretations.

my reading was similar to @dhirschfeld above.  But of course it's easy to resolve in either case, either explicitly say:
> It is a violation of the specification to give explicit strides in the C-contiguous case.
or
> As an optimization, None strides implies a C-contiguous array.

> This is what NumPy does in __array_interface__, and we intend to follow NumPy as closely as possible.

I think there's some conflation here between the specification and an implementation of the specification.  Yes, the implementation of the specification may do this (that's fine!).  The specification seems reasonably clear to me:

> The default is None which implies a C-style contiguous memory buffer

That is, None implies a C-style contiguous memory buffer but it's not disallowed to pass strides that are contiguous.

> You need a lengthier code just to loop over twice in order to tell it's C or F or neither. Why don't you just keep this info in the exchange format so as to save some trouble for every downstream consumers?
> You must already have a flag somewhere to indicate the contiguity, why don't you just use it? And if there's no such a flag, it's a design flaw in PyTorch I am afraid, as most of the time we want to use C-contiguous arrays in CUDA, and likewise F arrays are exceptions that must be tested somewhere.

You would only need to loop once.  I don't believe it saves trouble for the downstream consumers -- they need to handle arbitrary strides anyway because it's part of the format.  Maybe you are concerned with applying some optimization/flag in the case where explicit strides are provided but they are C-contiguous?  I don't really see another case for this and I think forcing implementors to apply optimizations as part of the specification isn't a good idea (it makes the specification more complicated).

> What's the ambiguity here? I don't get it.

I didn't say it was ambiguous, I said the term wasn't defined.  But not all systems support N-dimensional empty tensors (PyTorch didn't always), so being explicit is good.

> This is to comply with C/C++ practice. Typically a pointer is either explicitly or implicitly NULL-initialized prior to being passed to malloc or cudaMalloc. If it's a zero-size (or zero-length if you like) memory, then most likely you get a NULL back (at least in CUDA it's true). Thus, a common practice is to check whether a pointer is NULL or not before dereferencing it. For consumers parsing this info in C/C++/Cython, having this safeguard in place helps you ensure it won't be used.

But this is (essentially) copy, not malloc.  I think it's actually the opposite of C++ practice -- it's a violation of the standard to pass in nullptr as a source pointer to memcpy, even if the length is 0.  I don't think this is a huge deal, only noting that:
1) This isn't what NumPy does
2) This causes PyTorch to have to add extra code for checking this case for no benefit (it's easy to get a non-null data_ptr, just index a normal tensor to generate a 0-sized one.  It would be slower and more painful to always null the storage pointer).

**Comment by leofang** [comment]
Hi @dhirschfeld @gchanan, sorry for being silent. Got distracted. I'll try to address your challenges, but in separate posts. (I might get distracted again during replying...😞)   

Let me start from the 0-size array, as it seems only @gchanan is concerned.

> > What's the ambiguity here? I don't get it.
> 
> I didn't say it was ambiguous, 

Wait, your origin word in https://github.com/numba/numba/issues/4175#issuecomment-548599137 was "another ambiguity" 🙁 

> I said the term wasn't defined. But not all systems support N-dimensional empty tensors (PyTorch didn't always), so being explicit is good.

Could you elaborate how explicit you are expecting?

> But this is (essentially) copy, not malloc. I think it's actually the opposite of C++ practice -- it's a violation of the standard to pass in nullptr as a source pointer to memcpy, even if the length is 0. 

You got me on this 😅 I was babysitting while typing all that crap. Yes and no -- I had `cudaMalloc` in mind in my reply:
```C
size_t s = ...;
float* x = NULL;
cudaMalloc(&x, s);  // x would still be NULL if s = 0
```
but the way I phrased it was indeed mixed up with memcpy. As a Cython programer, it's easier to stick to the C practice instead of the C++ practice.

> I think a stronger argument is actually that it makes the interface "non-invertible"

I am confused. Do you mean having a pointer = 0 good or bad? Regardless of whether setting it to 0 or not, you can never get the same tensor back in such a scenario.  

> 1 . This isn't what NumPy does

This is an unfortunate but deliberately chosen deviation. The reason is that more than often a device pointer will be passed to `cudaPointerGetAttributes()` to look up its properties. We need a flag here to prevent from calling that lookup, as likely all you have is a null pointer returned from `cudaMalloc()` (see above), and`cudaPointerGetAttributes()` would throw `CUDA_ERROR_INVALID_VALUE`. #4140 is a manifestation of this symptom. In NumPy we don't have all these nuisances.

> 2. This causes PyTorch to have to add extra code for checking this case for no benefit (it's easy to get a non-null data_ptr, just index a normal tensor to generate a 0-sized one. It would be slower and more painful to always null the storage pointer).

From your reply in that PR I don't think this extra code is lengthy 🙂 

I'll try to expand on this in my next post, but the idea here is that there's an implicit distinction between an interface producer and a consumer (see the discussion started around https://github.com/numba/numba/pull/4609#discussion_r328986919), and we don't want the interface consumers to validate the input; we want the burden to be on the producers. 

Consider the following situation: passing a CuPy array to a Numba kernel that gets invoked more than 1 million times in a production-level pipeline. You can't expect Numba to repeat all those validations over and over. It should quickly be recognized as a valid device array and get the computation started asap. So, we need all the shortcut flags we can have. 
 
I'll address the strides issue in my next post, but I still wanna refer you folks to the description and discussion in #4609.

**Comment by dhirschfeld** [comment]
AFAICS there's nothing in #4609 that says the if present `strides` ***can not*** be C-contiguous.

**Comment by leofang** [comment]
For the strides issue --- 

OK, I understand now why this could be confusing. For my defense, #4609 got agreed upon by a few folks coming from different projects, and no one raised this concern. Also, I opened this issue back in June, and also made my best and timely efforts to propagate the changes to downstream (PyTorch was informed a month ago), so it is really frustrating to hear complaints now...Please forgive me if I seem impatient in any of my replies.

Indeed, an explicit strides might be allowed even if the array is C contiguous based on the text, but it's not the original intention. 

The context was that mpi4py and Dask needed a flag for fast-handling C-contiguous arrays -- this is the majority case (>99% in my experience) that one would encounter, so it's not overstepping to ask for a special treatment. Therefore,

> Maybe you are concerned with applying some optimization/flag in the case where explicit strides are provided but they are C-contiguous? I don't really see another case for this and I think forcing implementors to apply optimizations as part of the specification isn't a good idea (it makes the specification more complicated).

We actually thought this is a good idea.

Anyway, as mentioned above it's expected to have an implicit distinction between a producer and a customer. On the producer side, this pseudo code will always comply with the v2 protocol: 
```python
if is_c_contiguous():
    desc['strides'] = None
else:
    desc['strides'] = strides()
```
and on the consumer side: 
```python
strides = desc.get('strides')
if strides is None:  # C contiguous
    # use shape and itemsize, skip any test
else:
    # use strides, perhaps test for F-contiguity?
```
Now both cupy and numba are handling in this way. I see that the PyTorch PR pytorch/pytorch#24947 can achieve the same thing. 

If you are really, really unhappy with the description, please open a new issue/PR to bring to the attention of the Numba folks. Keeping the semantics of the above pseudo code intact is strongly preferred.

**Comment by dhirschfeld** [comment]
For the producer it's always correct to substitute `None` for a C-contiguous array so that's fine. You don't *have* to, but it's allowed for you to do so as an optimization.

For the consumer though it's incorrect to assume the array is *not* C-contiguous just because the `strides` were provided - the way the spec is currently worded this is allowed. In this case though I can't see that it could cause a problem except that potentially an optimized path might not be taken.

> *got agreed upon by a few folks coming from different projects, and no one raised this concern*

Yeah, sorry - I'm a bit late to the party here. I only just became aware of this discussion so thought I'd at least mention my reading of the spec. If it really is intended that strides must not be provided if the array is C-contiguous then I would strongly recommend updating the wording of the spec to *explicitly* state this restriction.

If the spec is intended to follow the numpy spec then I'd also recommend soliciting opinions on the intention from the experts on the numpy mailing list.

**Comment by leofang** [comment]
> If it really is intended that strides must not be provided if the array is C-contiguous then I would strongly recommend updating the wording of the spec to _explicitly_ state this restriction.

As I said, please contribute 🙂 Also, please keep downstream informed with any changes. I've done that once based on the list in #4448 (although with hindsight here apparently I did a shitty job), and it's better to have someone else taking turns.

On a different note: @dhirschfeld, which project(s) are you working on that would use `__cuda_array_interface__`? Could you leave a note in #4448 so that I can keep it documented and tracked? Thanks.

> If the spec is intended to follow the numpy spec then I'd also recommend soliciting opinions on the intention from the experts on the numpy mailing list.

Correct me if I am wrong, but I don't think this is ever done since the advent of `__cuda_array_interface__`. Most projects in the SciPy ecosystem cannot access GPU arrays anyway, and those that can should already follow the Numba mailing list. In addition, the nature of CUDA memory space requires some care not needed for CPU-only projects (like `cudaPointerGetAttributes` mentioned earlier). So, I don't see why this is necessary.

**Comment by dhirschfeld** [comment]
In the docs it states that the idea is borrowed from the numpy array interface:

https://github.com/numba/numba/blob/bdd8e312a24c5b76ee4fe480abe553cff349aa51/docs/source/cuda/cuda_array_interface.rst#L6-L9

That doesn't mean that it is exactly the same as it, but someone familiar with the numpy array interface should, in large part, be able to apply that understanding to the operation for the cuda array interface. Having the same concept but with different semantics would hinder that goal therefore it would be worthwhile IMHO to ask the numpy devs directly the intended operation of the `strides` argument. That doesn't mean you can't deviate from the numpy standard where it makes sense, but those deviations should be done consciously and clearly called out.

I'm just a user with an interest in the scientific programming ecosystem working smoothly together so I don't have too much skin in this game. I've pointed out what I think is either a misunderstanding or a poor wording of the spec but since the only effect would be a performance issue I'll let those who it does actually affect decide what to do about it...

**Comment by gchanan** [comment]
> Wait, your origin word in #4175 (comment) was "another ambiguity" 🙁

You are correct; I said this was an ambiguity in the heading but the description only say it's not defined.

> Could you elaborate how explicit you are expecting?

"for arrays with no elements (i.e. for which the product of shapes is 0)."  Or say something like 

> I am confused. Do you mean having a pointer = 0 good or bad? Regardless of whether setting it to 0 or not, you can never get the same tensor back in such a scenario.

I think forcing pointer = 0 is bad.  I think we'll discuss that below.

> This is an unfortunate but deliberately chosen deviation. The reason is that more than often a device pointer will be passed to cudaPointerGetAttributes() to look up its properties. We need a flag here to prevent from calling that lookup, as likely all you have is a null pointer returned from cudaMalloc() (see above), andcudaPointerGetAttributes() would throw CUDA_ERROR_INVALID_VALUE. #4140 is a manifestation of this symptom. In NumPy we don't have all these nuisances.

I'm confused.  Isn't https://github.com/numba/numba/issues/4140 a case where pointer = 0 was passed and that breaks `cuPointerGetAttribute`?  I'm asking to be allowed to pass a non-0 pointer in the case there are no elements, which seems like the opposite case.

> From your reply in that PR I don't think this extra code is lengthy 🙂

That's not what I meant -- I meant _enforcing_ in PyTorch that if `tensor.numel() == 0`, then `tensor.data_ptr() == 0` would be annoying.

> I'll try to expand on this in my next post, but the idea here is that there's an implicit distinction between an interface producer and a consumer (see the discussion started around #4609 (comment)), and we don't want the interface consumers to validate the input; we want the burden to be on the producers.

But neither of these cases is about validating the input.  The case of forcing `None` strides seems to be very clearly forcing the producer to do some optimization because the consumer might want to use it.

**Comment by gchanan** [comment]
> The context was that mpi4py and Dask needed a flag for fast-handling C-contiguous arrays -- this is the majority case (>99% in my experience) that one would encounter, so it's not overstepping to ask for a special treatment. Therefore,

This is definitely not the case for PyTorch.  Most of our implementations are not specialized for contiguous tensors (and our Tensor implementation doesn't support the ellide-the-strides optimization), so we'd end up just computing the strides if they are left off anyway.

> We actually thought this is a good idea.

Maybe it was for your use case, I'm not sure it's generally useful.  But note that the consumer code works whether or not the producer applies the optimization (so it's not a question of "validation"), and checking whether a large tensor is contiguous (even in the absence of a flag) is very fast, assuming there aren't that many dimensions (which I believe is the common case across most libraries).

By the way, I think it's totally fine to call it an optimization and suggest people use it in the documentation of the standard.  But having the wording be ambiguous and forcing optimizations isn't generally a great idea for a standard (it seems like this was designed for certain specialized use cases, not to be a standard).
