### ISSUE TITLE
Unsupported functionality in the code Numba

### ISSUE THREAD

**Issue by nici92** [numba/numba#4269]
Hi all,

I got this error message  using the package surfdist. 
how can it be fixed?

Thanks!! Best Nici

File "../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/surfdist/utils.py", line 75:
def find_node_match(simple_vertices, complex_vertices):
    <source elided>

    import scipy.spatial
    ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new

**Comment by esc** [comment]
@nici92 hi and thanks for reporting this error. We appreciate it! It might be the case that the `surfdist` package isn't compatible with the current version of Numba. Could you perhaps report back a few items, this would help us to further diagnose your problem:

* The current version of Surfdist and Numba that you are using.
* The output of `numba -s`.
* The exact command you entered to receive this error.
* A full log of the error message you received.

Thanks!

**Comment by stuartarchibald** [comment]
I'd anticipate that the issue here is that there is an import being made in a function that numba is being asked to compile, e.g.:
```python
from numba import jit

@jit
def foo():
    import scipy.spatial

foo()
```
Gives:
```
numba.errors.UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'IMPORT_NAME'

File "issue4269.py", line 5:
def foo():
    import scipy.spatial
    ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
```
Numba does not support, in any compilation mode,  the use of `import` as the `IMPORT_NAME` op code is not implemented internally.

If the `scipy.spatial` package is needed for the function perhaps try importing it at the module level, this should let the code compile.

@nici92 If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
