### ISSUE TITLE
Call Cuda device Function in a module

### ISSUE THREAD

**Issue by zhengle2008** [numba/numba#4272]
I am a Numba newbie, encounting a numba problem. I'm not sure if this's the right place to put my question, but I do need insightful  opinion.

I build a python module, and call it from notebook.
kernel function in the lya/b.py module:
```
import numpy as np
from numba import cuda

@cuda.jit
def my_native_kernel(io_array):
  pos = cuda.grid(1)
  if pos<io_array.size:
    x = a_device_function(3,2)
    io_array[pos] = x

def kernel_test(window):
    np_dmisc = cuda.to_device(np.array([window]))
    my_native_kernel[80, 64](np_dmisc)
    cuda.synchronize()
```
call it from jupyter notebook:
```
from lya import *
from numba import jit, cuda, float32
import numpy as np

@cuda.jit(device=True)
def a_device_function(a,b):
  return 2

b.kernel_test(1200)
```
and it reports error:

```
...
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'a_device_function': cannot determine Numba type of <class 'numba.ir.UndefinedType'>
```

If I put the definition of  a_device_function in lya/b.py, thing goes fine. But  a_device_function need to be redefined outside the lya module.
Is this the right way to use device function?

**Comment by seibert** [comment]
This is due to how Python handles the scope of names (like functions, global variables, etc).  When running a function like `my_native_kernel`, it will search for `a_device_function` in the scope of the module (b.py) where `my_native_kernel` was defined.  Since `a_device_function` is not defined in `b.py` and not imported into `b.py`, that name is undefined to `my_native_kernel`.  This is true even when you import `my_native_kernel` into another location, like a Jupyter notebook.  It still retains the scope of where it was originally defined.

If you want to experiment with changing `a_device_function` in a Jupyter notebook, you will need to put `my_native_kernel` also into your notebook, or use a "factory function" to create a scope where `my_native_kernel` can see `a_device_function`.

Here's an example of the factory function approach (untested, but should work):
``` python
def make_kernel(device_function):
    @cuda.jit
    def my_native_kernel(io_array):
      pos = cuda.grid(1)
      if pos<io_array.size:
        x = device_function(3,2)
       io_array[pos] = x

  return my_native_kernel
```
This is a function that makes a new kernel function specifically for your device function (which is now defined in local scope, and so visible to `my_native_kernel`) and returns it.  Then you could pass it to your kernel_test function as an argument:
``` python
def kernel_test(window, kernel):
    np_dmisc = cuda.to_device(np.array([window]))
    kernel[80, 64](np_dmisc)
    cuda.synchronize()
```

Then you could use this in your notebook this way:
```
from lya import *

@cuda.jit(device=True)
def a_device_function(a,b):
  return 2

my_kernel = b.make_kernel(a_device_function)
b.test_kernel(1200, my_kernel)
```

**Comment by zhengle2008** [comment]
@seibert  Many thanks, your reply do address my problem. I have read the faq part of [numba doc](https://numba.pydata.org/numba-doc/dev/user/faq.html) mention about factory function, but did not realize it's the way to go.
