### ISSUE TITLE
armv7 automatic parallelization

### ISSUE THREAD

**Issue by fejat** [numba/numba#4279]
Do you have any plan for automatic parallelization with @jit to support 32-bit architecture like arm v7?

**Comment by stuartarchibald** [comment]
Thanks for the question. I think it's the 32bit here that is the issue, opposed to ARM. The core dev team will discuss how hard removing the 64bit constraint will be at the next meeting.

**Comment by esc** [comment]
I labeled this as a feature request.

**Comment by seibert** [comment]
Fast forward a year, and now we're seeing Raspberry Pi with a beta OS for 64-bit on the Raspberry Pi 3 and 4 released earlier this year.  Ubuntu 20.04 64-bit is also available (which I've used), and there is probably a Fedora/CentOS option as well now.  Note that this does leave behind the Pi Zero and Pi 1, which are ARMv6 hardware and the Pi 2, which started out with ARMv7 hardware.  Everything since that in the Raspberry Pi lineup has been 64-bit capable.  The Pi Zero and 1 are single core anyway, so the biggest guaranteed loss I see with not supporting 32-bit parallel compute is the quad-core Pi 2.

Obviously, there are lots of 64-bit capable multi-core Raspberry Pi's that aren't going to be upgraded to a 64-bit OS for a while, so I appreciate the need.  However, I suspect that by the time we have bandwidth to address this request, the ARM ecosystem will be mostly focused on 64-bit and the demand for this will continue to drop over time.  These sort of word-size issues are often tricky to fix across all architectures, with Windows being a huge source of unintentional problems.  Anyone who wants to tackle this should be prepared to spend a lot of time watching CI fail...

**Comment by stuartarchibald** [comment]
I'm going to close this as I think 64bit ARM will proliferate faster than Numba could implement support for the parallel target on 32bit systems. If anyone feels strongly otherwise please feel free to leave comments and this ticket can be reopened.
