### ISSUE TITLE
I cannot install it on Conda using Python 3.6

### ISSUE THREAD

**Issue by gellban** [numba/numba#4320]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Is it possible to use it in Conda with Python 3.6?**

I user the following command:
sudo conda install numba

As I got the following error:
  - defaults/osx-64::wrapt==1.10.11=py36hc29e774_0
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - pip -> python[version='>=3.7,<3.8.0a0']
  - pkgs/main/osx-64::libopenblas==0.3.3=hdc02c5d_3
  - tensorflow-base

**Comment by stuartarchibald** [comment]
Thanks for the report. A few things:

1. > Is it possible to use it in Conda with Python 3.6?

    Yes. `conda create -n numba_py36 numba python=3.6`

2. I expect the problem you have is due to a number of other constraints in your current conda environment, this probably is not a Numba problem.

3. IIRC using `sudo conda` is may lead to issues with permissions etc.

4. If you are encountering a problem with `conda` environments that you are sure is down to an issue in the Anaconda distribution then perhaps open a ticket on the Anaconda issue tracker https://github.com/ContinuumIO/anaconda-issues/issues.

**Comment by gellban** [comment]
Yes, you are right. I created a new environment without issue using the command you have suggested.
Thank you for your prompt reply! I really appreciate it!

**Comment by stuartarchibald** [comment]
No problem, glad to be of help!
