### ISSUE TITLE
Global locks cause semaphore leaks.

### ISSUE THREAD

**Issue by PetrochukM** [numba/numba#4348]
#### Description

Importing `numba` causes semaphores to leak.

#### Steps/Code to Reproduce

```python
import multiprocessing as mp

import numba


def w():
    pass


def main():
    ps = [mp.Process(target=w) for _ in range(4)]
    [p.start() for p in ps]
    [p.join() for p in ps]


if __name__ == '__main__':
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()
```

#### Actual Results

```bash
$ python3 blah.py
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
$
```

#### Expected Results

```bash
$ python3 blah.py
$
```

**Comment by PetrochukM** [comment]
This issue is causing a number of downstream issues:
- https://github.com/pytorch/pytorch/issues/23117
- https://github.com/librosa/librosa/issues/924

Also, this issue came up with `tqdm`: https://github.com/tqdm/tqdm/issues/611

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce.

The reason for the lock here:
https://github.com/numba/numba/blob/37ab1420fa87d02b635991b32f0faf5c65e8fc4d/numba/npyufunc/parallel.py#L265
is that it's predominantly protecting `fork(2)` across the threading layer backend load sequence as some upstream libraries like GNU OpenMP are not fork safe. It's been like this in production for about a year now and this is the first issue we've had reported, so it's positive that the impact is low! I think what's happening is as follows:

1. `numba` is imported as part of the load sequence from `if __name__ == "__main__"`
2. `1.` sets a module level `RLock` in `numba.npyufunc.parallel` using the default "fork" context.
3. A process is started in the `__main__` scope with the "spawn" context, so `fork(2), exec*(2)`, the replacement image will target the function `main`.
4. The replacement image imports `numba` as part of the load sequence when starting the function `main` and sets the `RLock` as before, this is done under a "fork" context.
5. The `main` function running in the replacement image has a default context of "spawn" once the process is fully initialized (by virtue of context start method inheritance), so the grandchildren of the original process that are created in this function are created via the `spawn` context. 
6. The grandchildren processes will start and create `RLock`s during import, these `RLock`s also have the `spawn` context.
7. The semaphores used by the `RLock`s in 6. leak because they are now genuinely new semaphores and as the reference is module level they are not garbage collected.

Given the purpose of this lock was to deal with known fork safety issues in the threading backend initialisation sequences (and general nervousness about init sequences in 3rd party libraries), I think it would be ok to make this global lock purely lock when the multiprocess context is either set to "fork" or it is implemented as "fork" by virtue of defaults on certain Python/Platform combinations.


To the other comments:
> This issue is causing a number of downstream issues:
> 
>     * [pytorch/pytorch#23117](https://github.com/pytorch/pytorch/issues/23117)

Seems like there's more than one instance of this same problematic pattern involved here. Numba needs fixing but equally other things may need to be too.
 
>     * [librosa/librosa#924](https://github.com/librosa/librosa/issues/924)

This isn't `librosa`s bug so think that ticket being closed is correct.

> Also, this issue came up with `tqdm`: [tqdm/tqdm#611](https://github.com/tqdm/tqdm/issues/611)

Seems to be the same pattern.

--------------------------
As an aside, I wonder if it makes sense for the new process to inherit the start method from the context in which it was started. This:

```python
import multiprocessing as mp

def main():
    print("def main():", mp.get_context())

if __name__ == '__main__':
    print("in __main__:", mp.get_context())
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()
```
currently reports
```
in __main__: <multiprocessing.context.ForkContext object at 0x7f13c6598eb8>
def main(): <multiprocessing.context.SpawnContext object at 0x7f620f10ffd0>
```
but I'd have hoped a spawned process would use defaults for the platform, i.e. fork on linux.

**Comment by stuartarchibald** [comment]
Ping @pitrou... any ideas about why it seems like new processes generated from a specified context are are inheriting the specified context as their start method, i.e. use spawn context to generate a new process, new process has default context of spawn? Thanks.

**Comment by stuartarchibald** [comment]
^ that's probably not the right question to ask, because I know why it does that, the code says to do that, it's more, what's the reasoning, is this known, etc etc.

**Comment by pitrou** [comment]
I'm not sure a lock really makes it safe to invoke non-fork-safe routines. If you fork later, the child may inherit inconsistent state (for example ancillary threads won't exist anymore, or some locks wiil be acquired, etc.). The only reasonable solution seems to tell people not to fork if using a non-fork-safe routine or library.

**Comment by pitrou** [comment]
As for a module-global multiprocessing lock, indeed that doesn't sound like a good idea.

**Comment by pitrou** [comment]
Last note: [os.register_at_fork](https://docs.python.org/3/library/os.html#os.register_at_fork) in Python 3.7+ might help you as well.

**Comment by stuartarchibald** [comment]
Thanks for commenting @pitrou 

> I'm not sure a lock really makes it safe to invoke non-fork-safe routines. If you fork later, the child may inherit inconsistent state (for example ancillary threads won't exist anymore, or some locks wiil be acquired, etc.). The only reasonable solution seems to tell people not to fork if using a non-fork-safe routine or library.

Indeed, this is picked up in the C libraries doing the work and caught so at least the parallel backends are "safe" to some level. The above locking is about protecting an initialization sequence.

> As for a module-global multiprocessing lock, indeed that doesn't sound like a good idea.

Yeah, I'm just getting to the point of working out what is actually ok, and what is not.

> Last note: os.register_at_fork in Python 3.7+ might help you as well.

Yes, definitely, very good point, it's a shame about needing to handle 2.7, and 3+ :)

TBH, the most interesting thing was finding the processes inheriting the contexts, which I was not expecting. I was anticipating e.g. spawning a new process would lead to a new process with a default context of fork (at least on linux).
