### ISSUE TITLE
numba.errors.InternalError

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4443]
```
@jit(nopython=True)
def plog_mat(m):

	size = m.size
	if size == 1:
		return np.log(np.abs(m))
			
	m_ = np.copy(m)
	rowNum = m.shape[0]
	colNum = m.shape[1]

	for i in np.arange(rowNum):
		for j in np.arange(colNum):
			if m[i,j] == 0:
				m_[i,j] = 0.001 

	m_abs = np.abs(m_)
	return np.log(m_abs)

```

```
plog_mat(np.array([10.5]))

numba.errors.InternalError: tuple index out of range
[1] During: typing of static-get-item at <ipython-input-70-89a44dff5b28> (10)
--%<----------------------------------------------------------------------------


File "<ipython-input-70-89a44dff5b28>", line 10:
def plog_mat(m):
    <source elided>
	rowNum = m.shape[0]
	colNum = m.shape[1]
 ^
```

when I input a scalar, function will give the error . But it have already return when size == 1,  so why the function still execute the 'colNum = m.shape[1]'  after the return

**Comment by isaac-you** [comment]
```
plog_mat.py_func(np.array([10.5]))

```
this can give the right answer , so without jit it can execute  the right order code ???

**Comment by stuartarchibald** [comment]
Thanks for the report. What you are experiencing is due to Numba having to statically analyse the source code which means it has to consider *all* the source, this mixed with a known issue about `StaticGetItem` (the internal representation of `m.shape[some index]`). Even if this were fixed the return types would not be able to be unified.

Once https://github.com/numba/numba/pull/4113 lands in the next (0.46) release of Numba this will work:

```python
from numba import jit
import numpy as np

@jit(nopython=True)
def plog_mat(m):
        size = m.size
        if size == 1:
            return np.log(np.abs(m))

        if m.ndim == 2:
            m_ = np.copy(m)
            rowNum = m.shape[0]
            colNum = m.shape[1]

            for i in np.arange(rowNum):
                for j in np.arange(colNum):
                    if m[i,j] == 0:
                        m_[i,j] = 0.001

            m_abs = np.abs(m_)
            return np.log(m_abs)

plog_mat(np.array([10.5]))
```
because code was added to Numba to do special detection for compile time constants, in particular `ndim`.

**Comment by isaac-you** [comment]
thank you so much

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
