### ISSUE TITLE
Default Compilation mode for CUDA Kernels

### ISSUE THREAD

**Issue by Nischay-Pro** [numba/numba#4574]
By default does Numba compile in separate compilation mode.

**Comment by stuartarchibald** [comment]
Thanks for the query. Please could you expand on what it is you mean by this?!


> By default does Numba compile in separate compilation mode.

**Comment by Nischay-Pro** [comment]
I would like to know the behavior of Numba when an application has multiple device kernels.

Does each kernel when compiled have it's own separate ptx code? Does it generate Relocatable Device Code?

This article might explain what I'm trying to say.
https://devblogs.nvidia.com/separate-compilation-linking-cuda-device-code/

**Comment by malays** [comment]
@stuartarchibald ,
Specifically, does numba set the "-dc" flag of NVCC when compiling?

**Comment by seibert** [comment]
Numba uses libNVVM to compile NVVM IR directly from a string in memory.  It never invokes NVCC (in fact, NVCC doesn't need to be present on the system), so I'm not quite sure what the equivalent to `-rdc` is.

Looking at the compile function: https://docs.nvidia.com/cuda/libnvvm-api/group__compilation.html#group__compilation_1g76ac1e23f5d0e2240e78be0e63450346
I'm not sure if the option we need is there.

**Comment by malays** [comment]
Thanks @seibert !
I dug some more. It seems it indeed is not possible to perform separate compilation with libnvvm.
I also verified that the code me and @Nischay-Pro were looking at was not separate-compiled. I'm very new to numba, so took some time to figure out the flow.

Thanks for the help and information!

**Comment by leofang** [comment]
Hi guys,

Look at the following lines from #4551 
https://github.com/numba/numba/blob/9a6921365e11a3442944c4daff8a7bb0d174fae0/numba/cuda/tests/cudapy/test_cooperative_groups.py#L22-L26
and scroll a few lines down to see how `LINK` is passed to `cuda.jit` to link to the CUDA device runtime library. The only task left is to find a way to pass in `-rdc`. I know nothing about how libNVVM works though...

This issue is directly related to my comment on dynamical parallelism: https://github.com/numba/numba/pull/4551#issuecomment-530187364.

**Comment by leofang** [comment]
I have a naive question: is LLVM also used as part of the kernel compilation in Numba, or only libNVVM? I noticed that there are some effort on the LLVM side to support relocatable device code/separate compilation with the option `-fcuda-rdc`, see, e.g., https://reviews.llvm.org/D42921 and the subsequent PRs.

**Comment by seibert** [comment]
We only use NVVM.  We generate the IR as string using the same code path we use for LLVM, but then patch it up to match the syntax expected for NVVM IR (which is based on LLVM 3.4 for text IR).

**Comment by leofang** [comment]
I see, thanks for the explanation @seibert. I suppose `-rdc` isn't possible then, based on NVVM's docs.

**Comment by sklam** [comment]
For the `cuda.jit`, all numba compiled CUDA kernels are in PTX format. The PTX has no concept of relocation because it is purely textual/symbolic. Numba uses the [cuLink API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MODULE.html#group__CUDA__MODULE) to link the PTX and any external libraries.  One can link many PTX together with the API, so one can treat the PTX as relocatable.  It is unknown whether the linked *cubin* in memory is relocatable or not. There are internal options like [`CU_JIT_GLOBAL_SYMBOL_NAMES`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1g5527fa8030d5cabedc781a04dbd1997d) that refers to relocation but the docs is not clear on how.

**Comment by leofang** [comment]
> The PTX has no concept of relocation because it is purely textual/symbolic.

This is not true I think. You can try compiling a simple code using NVRTC, which generates a PTX code, without and with `-rdc=true`. The results are different. I can paste a comparison here if you like.

**Comment by malays** [comment]
@leofang , @sklam , thanks for your inputs.
You are both right in a sense. 

rdc is an nvcc option and the decision that code needs to be "relocatable" is taken at a higher level. Each unit can be compiled separately and linked together. Hence, ptx itself does not need to be aware if code is relocatable. 

Generating relocatable code is restrictive in terms of compilation. Since a function does not know it's caller, it follows abi. Since we are not linking on the fly, linker optimizations are disabled. This means that the ptx generated is different in both cases. The simplest way to test would be to compile a cuda program without an entry function. Separate compilation would create a ptx with device kernels but the regular compilation will create an empty ptx.

>It is unknown whether the linked cubin in memory is relocatable or not. 
What exactly do you mean by this? If the cubin was generated with "-c" ptxas option, it is relocatable

>There are internal options like CU_JIT_GLOBAL_SYMBOL_NAMES that refers to relocation but the docs is not clear on how.
Where did you see this option?

**Comment by leofang** [comment]
> > It is unknown whether the linked cubin in memory is relocatable or not.
> 
> What exactly do you mean by this? If the cubin was generated with "-c" ptxas option, it is relocatable

If I understand @sklam correctly, Numba takes the PTX string (presumably generated from NVVM?) and pass it to the LinkState via `cuLinkAddData`. Then, once `cuLinkComplete` is called, you get an in-memory cubin image. (`cuLink*` are all driver APIs.)

> > There are internal options like CU_JIT_GLOBAL_SYMBOL_NAMES that refers to relocation but the docs is not clear on how.
> 
> Where did you see this option?

It's one of the options in `CUjit_option`: https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1g5527fa8030d5cabedc781a04dbd1997d

**Comment by malays** [comment]
AFAIK, there is no jit option to enable "compile-only" (it wouldn't make sense top jit if you wanted to compile only). This implies that the cubin is not relocatable

The JIT option sounds like any regular relocation unless I'm missing something..
>Array of device symbol names that will be relocated to the corresponing host addresses stored in CU_JIT_GLOBAL_SYMBOL_ADDRESSES. Must contain CU_JIT_GLOBAL_SYMBOL_COUNT entries. When loding a device module, driver will relocate all encountered unresolved symbols to the host addresses. It is only allowed to register symbols that correspond to unresolved global variables. It is illegal to register the same device symbol at multiple addresses.

As for the cuJIT option, that seems to be talking about relocating between host and device. That a different relocation than what we are talking about here.. Although I agree it is badly documented

**Comment by sklam** [comment]
@leofang, yes, that's what I mean.

**Comment by sklam** [comment]
Here's how I understand the NVCC compilation steps.

When asked to produce relocatable device code (-dc), i.e.:
```bash
$ /Developer/NVIDIA/CUDA-9.2/bin/nvcc -v --keep -dc check.cu
```
nvcc expands into calls like below (with my annotation of each step):
```bash
# STEP 1: Preprocess C/C++ for Device codegen 
$ clang -D__CUDA_ARCH__=300 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__ -D__CUDACC_RDC__  "-I/Developer/NVIDIA/CUDA-9.2/bin/../include"   -D"__CUDACC_VER_BUILD__=64" -D"__CUDACC_VER_MINOR__=2" -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64 "check.cu" > "check.cpp1.ii"
# STEP 2: Generate PTX
$ cicc --clang --clang_version=40000 --unicode_source_kind=UTF-8 --allow_managed  --device-c   -arch compute_30 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "check.fatbin.c" -tused -nvvmir-library "/Developer/NVIDIA/CUDA-9.2/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "check.module_id" --orig_src_file_name "check.cu" --gen_c_file_name "check.cudafe1.c" --stub_file_name "check.cudafe1.stub.c" --gen_device_file_name "check.cudafe1.gpu"  "check.cpp1.ii" -o "check.ptx"
# STEP 3: Compile PTX into relocatable CUBIN
$ ptxas -arch=sm_30 -m64 --compile-only  "check.ptx"  -o "check.sm_30.cubin"
# STEP 4: Make FATBIN from CUBIN
$ fatbinary --create="check.fatbin" -64 --cmdline="--compile-only  " "--image=profile=sm_30,file=check.sm_30.cubin" "--image=profile=compute_30,file=check.ptx" --embedded-fatbin="check.fatbin.c" --cuda --device-c
# STEP 5: Preprocess C/C++ for Host codegen
$ clang -E -x c++ -D__CUDACC__ -D__NVCC__ -D__CUDACC_RDC__  "-I/Developer/NVIDIA/CUDA-9.2/bin/../include"   -D"__CUDACC_VER_BUILD__=64" -D"__CUDACC_VER_MINOR__=2" -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64 "check.cu" > "check.cpp4.ii"
# STEP 6: Generate Host-side C++ code that includes fatbin (check.fatbin.c)
$ cudafe++ --clang --clang_version=40000 --unicode_source_kind=UTF-8 --allow_managed  --device-c  --m64 --parse_templates --gen_c_file_name "check.cudafe1.cpp" --stub_file_name "check.cudafe1.stub.c" --module_id_file_name "check.module_id" "check.cpp4.ii"
# STEP 7: Compiles the step 6 C++ code into the actual object file
$ clang -D__CUDA_ARCH__=300 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS "-I/Developer/NVIDIA/CUDA-9.2/bin/../include"   -m64 -o "check.o" "check.cudafe1.cpp"
```

The corresponding steps for numba would be:

- STEP 1: compiles python code into LLVM IR.
- STEP 2: use NVVM to convert LLVM IR into PTX.
- STEP 3-7: use CUDA Driver API to load and link...

If one wants to take the numba emitted PTX and link it with code compiled by nvcc, I think one can follow what `nvcc` does starting at step 3 with ptxas.

**Comment by gmarkall** [comment]
> > The PTX has no concept of relocation because it is purely textual/symbolic.
> 
> I am not sure if this is true. You can try compiling a simple code using NVRTC, which generates a PTX code, without and with `-rdc=true`. The results are different. I can paste a comparison here if you like.
> 
> ref: https://docs.nvidia.com/cuda/nvrtc/index.html#separate-compilation

I've created a small example for comparing PTX with and without the `-rdc` flag - https://github.com/gmarkall/ptx-rdc-comparison - the only difference in PTX that I can see is that the `-rdc` flag ensures that PTX is emitted for all non-force-inlined `__device__` functions, whereas without it, `__device__` function code is not emitted for `__device__` functions not called within the translation unit - do you see any more significant difference?

**Comment by gmarkall** [comment]
I think this discussion ran its course, so I'll close this issue.
