### ISSUE TITLE
[FEA] Supporting LLVM 9

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#4605]
## Feature request

Recently LLVM 9 was [released]( https://releases.llvm.org/9.0.0/docs/ReleaseNotes.html ). Would be nice for Numba to support this latest version of LLVM.

**Comment by stuartarchibald** [comment]
Thanks for the request. Discussion for support is already under way :)

**Comment by jakirkham** [comment]
Thanks for the update. Thought so. Just didn’t see an issue for it.

**Comment by seibert** [comment]
Things that we'll need to check:

* Does MCJIT still work? (ORCJIT v1 has already been deprecated)
* Need to make sure moving up to VS2017 doesn't cause any issues in our CI system
* Can we still actually build wheels with gcc 4.8 (which the release notes claim is possible if we disable the compiler check)?
* Has the PPC situation (where we are stuck on LLVM 7.1 due to major bug in LLVM 8) gotten better or worse?

**Comment by jakirkham** [comment]
Is there an issue or issues tracking PPC problems?

**Comment by seibert** [comment]
#4026

**Comment by stuartarchibald** [comment]
and this one https://github.com/numba/numba/issues/4563

**Comment by edelsohn** [comment]
@obilaniu What level of financial bounty would entice you to fix this bug?

**Comment by jakirkham** [comment]
This was [done in 0.50.0]( https://github.com/numba/numba/blob/852739185c191e30159fa21d52a547763377ea62/CHANGE_LOG#L827 )
