### ISSUE TITLE
Interpreting Numba's PTX output

### ISSUE THREAD

**Issue by uchytilc** [numba/numba#4666]
I have a couple questions about how Numba generates ptx. I have created a few test device functions to look through the generated ptx code and noticed that each test function seems to have an extra input argument. What is the purpose of this argument (can it just be edited out of the string?)? Also, the function names seem to be mangled. Is there a compile parameter that could prevent this?

I've been looking through the Numba code base and it seems like all the important CUDA driver API calls have python wrappers. I'm hoping that I can wrap a few of the nvrtc calls to create something like a compileFileToPTX function (there is an example of this function in the CUDA sample code repo) for CUDA functions written in C and then link Numba generated PTX code and nvrtc generated PTX code using the Driver API functions that are within Numba. Does this sound like something that can be done? My end goal is to write C kernels that take device function pointers and have user definable functions (that will be written in Python and compiled with Numba) that will be passed to the the C kernels.

**Comment by sklam** [comment]
> ... each test function seems to have an extra input argument. What is the purpose of this argument (can it just be edited out of the string?)? 

These extra arguments are due to Numba's internal C API.  To simplify things, numba flattens aggregates (i.e. structures) at function boundaries.  Things like arrays are passed as many individual words that are representing things like shapes, strides, data-pointer. As you have noticed in  https://github.com/numba/numba/issues/3983, exposing a C-API would help.  Doing so would make sure Numba uses the same ABI as CUDA-C compiler would.

> Also, the function names seem to be mangled. Is there a compile parameter that could prevent this?

Not yet. (Issue https://github.com/numba/numba/issues/4389 is also needing a way to avoid name mangling. This can be provided in `@cfunc` too.

Alternatively, the mangled name can be referenced directly in C code given a `extern "C"`.  

> Does this sound like something that can be done? My end goal is to write C kernels that take device function pointers and have user definable functions (that will be written in Python and compiled with Numba) that will be passed to the the C kernels.

Yes, very doable. Numba is just using `ctypes` to wrap the CUDA driver C-API. The NVRTC API is smaller and easier to wrap.  You can use the nvvm wrapper as a guide:

https://github.com/numba/numba/blob/5bd018fd55ab2ff0916ab2c6360334fe94e471a4/numba/cuda/cudadrv/nvvm.py#L63

**Comment by uchytilc** [comment]
> These extra arguments are due to Numba's internal C API. To simplify things, numba flattens aggregates (i.e. structures) at function boundaries. Things like arrays are passed as many individual words that are representing things like shapes, strides, data-pointer.

So this is what allows you to write data.size or data.shape within the kernel? You are internally passing these values in inside this first "hidden" parameter (is this at all related to  __ cuda_array_interface __?). That is very cool.

My understanding of PTX code is VERY limited, but after generating a compiled ptx string, editing it shouldn't be a huge deal as far as I can tell. If I do a simple search replace for the mangled name with py_func.__ name __ that should work fine no? And as for the extra argument, as long as user code doesn't contain something like "data.size", I should be able to simply remove param_0 and any PTX that references it right (which should only be like 1 line)?

The last part of the ptx I am unsure of are these lines at the top:

    .common .global .align 8 .u64 _ZN08NumbaEnv8__main__7add$241Eff;    

    .common .global .align 8 .u64 _ZN08NumbaEnv5numba7targets7numbers14int_power_impl12$3clocals$3e13int_power$242Efx;

If I have the following device function where I take a float to the power of an integer the PTX code has the int_power_impl line.

    @cuda.jit(device=True)
    def add(a, b):
	    return a**2 + b

I imagine the first ptx line loads in an global variables set (which I wont have so maybe this can be removed?) and the second is related to the fact that I am taking an integer power but I don't understand its significance and if it can be removed.

I should also clarify the user defined functions are very limited in scope. They are all simple operators like f(x): return cos(x) or f(x,y,z): return x*x + y - z so I don't need to handle a wide verity of things that Numba is capable of.

**Comment by uchytilc** [comment]
Attached is a working example of Numba executing code compiled with NVRTC from a .cu file along with an almost working example of multiple .cu files. When I try and compile the .cu file containing the device function nvrtc/nvcc spit out a ptx file that only contains the header information (version, target, and address_size). Hopefully someone can take a look and see what the issue is (the device function file has no kernel in it, is the compiler ignoring the function because of that?). After I get this figured out I will try and incorporate Numba device functions.

[c_to_numba.zip](https://github.com/numba/numba/files/3700078/c_to_numba.zip)

**Comment by uchytilc** [comment]
Turns out I needed the --device-c (-dc) compiler argument for relocatable device code.

**Comment by sklam** [comment]
The ABI situation for device functions is slightly different from kernels because the latter has no return-value.  For device functions, this code describes the ABI:

https://github.com/numba/numba/blob/9eb26b300e361911731f1f128ce6b7234491d098/numba/targets/callconv.py#L158-L170

If you only need scalar types, it is a lot simpler.  Simple scalar types (i.e. int, float, double) are passed in Numba just like it would in NVCC generated code.  The main difference would be the return value.  Device functions emitted by Numba always return an integer status code.  `0` for success.  The actual returning value is stored in the first argument via a caller allocated pointer.  

Given a Numba CUDA device function as:

```python
@numba.cuda.jit("float32(float32, float32)" device=True)
def simple_add(x, y):
    return x + y
```

the equivalent C function would be:

```C
int example_device_func(float *return_value, float x, float y);

**Comment by uchytilc** [comment]
@sklam You have been an immense help. I am going to look to Jitify to see how they parse the user input compiler arguments and header files and try and incorporate it. I am also interested in utilizing variadic templates to allow input of device functions of various argument length (might just edit the kernel string directly before passing it to nvrtc, not sure if it is worth the effort in my case as the template device functions have a very limited scope). My last question is regarding the device function arguments. Can the inputs be passed by reference or do they have to be pass by value? This is my current device function declaration

    extern "C" __device__ int op(float* return_value, float &x, float &y);

do I need to remove the ampersands for this to work with numba?

**Comment by sklam** [comment]
C++ variadic templates? I don't fully understand what you want to do but it sounded hard (high effort) already. To me, C++ complicates the ABI problem a lot.

> Can the inputs be passed by reference or do they have to be pass by value? This is my current device function declaration

Numba is always passing simple scalars by value for function arguments. I do not know what NVCC emit for pass-by-reference argument. Btw, I think this section of the PTX doc https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#abstracting-abi will help you in your adventure.
