### ISSUE TITLE
Cannot determine Numba type of <class 'phe.paillier.PaillierPublicKey'>

### ISSUE THREAD

**Issue by ivankxt** [numba/numba#4857]
We want to use numba to accelerate the paillier encrypt of data, the code as follow：

`    @jit(nopython=True)
    def my_kernel(self, data: Union[list, tuple, np.ndarray], pu_key: PaillierPublicKey):
        self.data: List[EncryptedNumber] = [pu_key.encrypt(x) for x in data]`

We got the error as:

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'faderated.encrypted.EVector'>
- argument 2: cannot determine Numba type of <class 'phe.paillier.PaillierPublicKey'>

Could you give me some advice how to solve this problem? 
Thanks!

**Comment by stuartarchibald** [comment]
Thanks for the report. The error you are seeing is because your code is using types not known to Numba (e.g. `<class 'phe.paillier.PaillierPublicKey'>`). In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.
