### ISSUE TITLE
Could numba support big integers for pow(x, y, z) or x**y mod z?

### ISSUE THREAD

**Issue by ivankxt** [numba/numba#4877]
With the rise of federal-learning, the need for homomorphic encryption is increasing, but encryption takes too much time(the calculation of x**y mod z).  We want  to accelerate homomorphic encryption through concurrent operations by numba on cuda.

Could you give me some advice?
Thanks!

**Comment by stuartarchibald** [comment]
Thanks for the question. Numba supports integer sizes that match typical hardware integer sizes, so the largest would be a 64bit integer. The reason for this in part is the relationship Numba has with NumPy and also in part because for both Numba and NumPy performance is important and arbitrarily large integers require representations that do not map well to fundamental units of execution on commodity hardware.

**Comment by seibert** [comment]
If someone wanted to implement an arbitrary precision library with Numba, that is certainly possible.  Alternatively, there are C libraries that do this, and so someone could wrap them to be usable from Numba, though that would take a little effort.

**Comment by 99991** [comment]
In order to implement a fast arbitrary precision library in numba, an `adc` instruction for addition and some way to get the high bits of a multiplication instruction would be necessary, at least for the platforms where those are available. Would such a thing be possible with numba, for example by using something like [intrinsic functions](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html)?

**Comment by stuartarchibald** [comment]
Numba permits most things that LLVM can support, but with varying degrees of effort to achieve this.

Were Numba to generate LLVM `i128`'s then its possible for LLVM to compile an `add` to a `adc`.
Example: https://godbolt.org/z/cdGnsg

**Comment by gmarkall** [comment]
Closing this as it seems like the original question is answered and no further response has been received. If there are further discussions to have or questions to resolve, the Discourse group https://numba.discourse.group will be a better place for items of this nature.
