### ISSUE TITLE
Generator performance

### ISSUE THREAD

**Issue by ivirshup** [numba/numba#4906]
## Reporting a bug

Generators seem to be over 10x slower than the equivalent loops:

```python
from numba import njit
import numpy as np

a = np.random.randint(0, 10000000, 10000)  
b = np.random.randint(0, 10000000, 10000)

@njit
def product_binary(A, B):
    for a in A:
        for b in B:
            yield a, b

@njit
def sum_pairs_loop(A, B):
    out = np.empty(len(A) * len(B), dtype=A.dtype)
    i = 0
    for a in A:
        for b in B:
            out[i] = a + b
            i += 1
    return out

@njit
def sum_pairs_gen(A, B):
    out = np.empty(len(A) * len(B), dtype=A.dtype)
    for i, (a, b) in enumerate(product_binary(A, B)):
        out[i] = a + b
    return out

%timeit sum_pairs_loop(a, b) 
# 435 ms ± 5.91 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

 %timeit sum_pairs_gen(a, b) 
# 6.02 s ± 200 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Is this expected?

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm not hugely surprised by this. Underneath Numba is LLVM which does the bulk of the optimisation when it compiles the LLVM IR that Numba is generating. The "loop" version is going to be very quick because of two things 1) that there's been decades of research into optimising loops and Numba knows how to present loops in a way that LLVM really likes 2) that Numba is managing to eliminate any reference counting in the loop as it's a case it "understands". The "generator" version is not so lucky, it's quite hard to optimise as there's multiple function calls underneath to make the generator "work" and included in this is a load of reference counting that cannot be eliminated by the current passes that do this.

**Comment by ivirshup** [comment]
That's interesting to hear. I was thinking about this in the context of `itertools` and was hoping they could be easily expressed with generator functions. Is there currently any way of defining iterables that can be optimized well?

A possibly naive question: do immutable values get reference counted in the same way as mutable ones? I would have thought values like numbers or tuples would be stored inline, which could make this a little easier to optimize.

**Comment by stuartarchibald** [comment]
> That's interesting to hear. I was thinking about this in the context of `itertools` and was hoping they could be easily expressed with generator functions. Is there currently any way of defining iterables that can be optimized well?

This is a huge "it depends", which is probably not the answer you wanted. If iterables can be inlined as compile time constants ~= live on the stack, and the function doing the work can also be inlined, then "may be". A lot of this comes down to whether there's reference counting involved (objects on the heap), whether we can spot that and eliminate it, and then also what the function being called is like.

> 
> A possibly naive question: do immutable values get reference counted in the same way as mutable ones? I would have thought values like numbers or tuples would be stored inline, which could make this a little easier to optimize.

It's more about where the object's data is stored, if it's a heap allocation then it's reference counted. e.g. tuples are inlined and stack allocated, NumPy arrays are heap.

**Comment by gmarkall** [comment]
Closing this as it seems like the original question is answered and no further response has been received. If there are further discussions to have or questions to resolve, the Discourse group https://numba.discourse.group will be a better place for items of this nature.
