### ISSUE TITLE
Can't unbox heterogeneous list

### ISSUE THREAD

**Issue by k128** [numba/numba#5165]
Code:
```
@njit
def test(nums):
	return

test([sum(2**i for i in range(64) if i%2==j) for j in range(2)])
```

Output:
```
C:\Users\e017200\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\ir_utils.py:2030: NumbaPendingDeprecationWarning:
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'nums' of function 'test'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "<stdin>", line 1:
<source missing, REPL/exec in use?>

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't unbox heterogeneous list: uint64 != int64
```

**Comment by esc** [comment]
@k128 thanks for reporting this on the Numba issue tracker. I looked into this today and I think it has something to do with overflow and your integers being too big.

If I modify the code as such:

```python
from numba import njit, int64


#@njit
def test(nums):
    return nums


print(test([sum(2**i for i in range(64) if i % 2 == j) for j in range(2)]))
```

And run it, I get:

```python
[6148914691236517205, 12297829382473034410]
```

So my next attempt at a workaround was:

```python
from numba import njit, uint64


@njit
def test(nums):
    return nums


print(test([uint64(sum(2**i for i in range(64) if i % 2 == j)) for j in range(2)]))
```

And that worked fine. The problem is, that the first number seems to fit into a `int64` and second one needs a `uint64`. So what Numba does in this case is look at the first element, refine the list to be `int64`, then it will try to convert it and encounter something that needs a `uint64` --- and then it bails as you can see. The problem with these type of lists is that they must be type homogeneous for Numba to compile them. As a workaround you can force the type as I have shown above.

**Comment by esc** [comment]
@k128 after some more deliberation, I came to the conclusion, that this is expected behavior and it is unlikely that we will be able to fix it. Basically, it is the same as attempting to pass a list containing integers and characters to Numba, which will be rejected. If you encounter such an issue in your production code, please use explicit casting, thanks!

**Comment by k128** [comment]
Thanks for looking into this.  Your explanation makes sense.   The error message could be better, since in a vacuum I wouldn't consider this to be a heterogenous list.  Ideally, I'd want Numba to start over and recast it as a uint64 if this occurs (or any other type combination like this ie. try again if a float is found when it thought the list was int but not if a str was found).  This would add minimal time and only in the cases where it was going to fail anyway.

**Comment by esc** [comment]
@k128 thank you for your suggestions, we will consider them.

**Comment by k128** [comment]
Thanks @esc,
Is there currently a way that I can use explicit casting on the function (instead of the passed parameter) to fix this?  My real list comes from another program (and is part of a larger object) and I'd like to avoid looping through and creating a copy of uint64 versions of it if possible.

**Comment by esc** [comment]
@k128 thanks for asking about this, we appreciate your input.

I don't this this is possible right now, since the so-called 'unboxing' of the Python list into a Numba (reflected) list happens when the Python object is passed into a Numba JIT compiled function, so you don't have much influence over how the values are converted. What I can suggest however, is to use the newish Numba typed-list instead of a regular Python list. Here is an example:

```
from numba import njit, typed, types

@njit
def foo(x):
    # x is still a typed-list
    return x[1] - x[0]


# create the Numba typed list with a type specifier
mylist = typed.List.empty_list(types.uint64)
for j in range(2):
    # cast the generated values and add them to the list
    mylist.append(types.uint64(sum(2**i for i in range(64) if i%2==j)))
print(repr(mylist))
print(foo(mylist))
```

In general, this means you will be using a list variant that doesn't store it's values as Python objects and so nothing must be unboxed when passing the list in as an argument to a Numba JIT compiled functions. Instead the unboxing happens when you add the integer to the list in the first place. So, if you create the list once and pass it into many or one Numba JIT often, this may more performant.

You can read more about the typed-list here: http://numba.pydata.org/numba-doc/latest/reference/pysupported.html?highlight=list#typed-list

Hope that helps?

PS: the typed-list is still somewhat new, so if you encounter any snags, they may be genuine bugs, so please don't hesitate to report those, thanks!

**Comment by esc** [comment]
@k128 I am assuming this is now resolved, please feel free to re-open if needed.

**Comment by said-ml** [comment]
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'choices' of type Module(<module 'random' from '/opt/conda/lib/python3.10/random.py'>)

**Comment by esc** [comment]
> TypingError: Failed in nopython mode pipeline (step: nopython frontend) Unknown attribute 'choices' of type Module(<module 'random' from '/opt/conda/lib/python3.10/random.py'>)

@said-ml  the problem you post has nothing to do with othis issue. Please be more mindful when posting in future and make sure you submit comments to the correct issue.

None the less to answer your question: `choices` doesn't appear to be implemented: https://numba.readthedocs.io/en/stable/reference/pysupported.html#random

**Comment by said-ml** [comment]
@esc you're right ,  i will take advice in acount.
