### ISSUE TITLE
Ideas for a new Rewrite pass

### ISSUE THREAD

**Issue by noahstier** [numba/numba#5205]
As part of a graduate course on optimizing compilers, my 3-person group is interested in improving some aspect of numba's performance. Performance can be interpreted loosely, and implementing our improvement as a `numba.rewrites.Rewrite` would be convenient but not necessary. We have about five weeks. Are there any planned projects in this area, or known optimization opportunities?

Because typical optimization passes for e.g. redundancy elimination are already handled downstream by LLVM, it's not obvious what optimizations in typed/untyped numba IR would actually be beneficial.

A few ideas we've had are:

- source-based automatic differentiation of numba IR (similar to [Zygote.jl](https://arxiv.org/pdf/1810.07951.pdf) )
- implementation of some Python language feature that currently causes failure in `nopython` mode
- implementation via `@overload` of some useful library module, such as `scipy.ndimage`

We would be grateful for any suggestions!

**Comment by esc** [comment]
@noahstier thanks for asking about this, I have added the 'discussion' label here. I hope that @stuartarchibald, @sklam,  @ehsantn and @seibert will find some spare cycles to chime in.

As for SciPy functionality: there is this nascent project here which could surely do with some more champions: https://github.com/numba/numba-scipy

**Comment by ARF1** [comment]
@noahstier As only a user of numba myself, there are many more qualified people to give their opinion. I would however like to throw some subjects into the discussion for consideration that I as a numba user would find very beneficial.

In line with your invitation to interpret "improve numba performance somehow" liberally, maybe you are interested in creating some new performance diagnostics tools for numba. Even though, they would not help improve numba performance directly they could help users and numba developers write more performant numba code.

- @stuartarchibald Seems to have the beginning of a line-profiler (see #5028) that would require significant effort. I am sure many users of numba would really welcome such an addition.
- I myself found it necessary to hack together the visualization of the generated assembly control flow graph to debug compiler SIMD vectorization failures. My code is rough brinkmanship however and not really suitable to include in numba. There are suggestions on how to do it right in #5063. This should be relatively straight-forward to do but will be of interest to a much smaller number of people.

---
If you want to stick with a new rewrite pass, maybe improving tuple support in nopython mode would be a possibility. Though it will have very limited performance benefit - if any at all.

Currently, numba nopython mode does not support tuple creation. I.e. the following will not work:
```python
my_tuple = tuple(some_iterable)
```

The fundamental problem is that the implementation of tuples in numba requires the length of tuples to be known at compile time.

That said, there are a range of subproblems where numba could in theory determine the length at compile-time because the length is predetermined e.g.:

```python
my_tuple = tuple([1, 2, 3])
my_tuple = tuple(range(3))
my_tuple = tuple([2*n for n in range(3])
```

That would require a rewrite pass that finds and treats these cases. A rewrite pass that does this for the command `np.array([1, 2, 3])` already exists to inspire you.

This issue is discussed in detail in #2771. If the new rewrite pass is general enough, maybe the same pass could also be used to solve #3993.

**Comment by ehsantn** [comment]
All three ideas seem both interesting and useful to me. However, I'd vote for the second idea (supporting more Python features in `nopython` mode) for the following reasons:

1. Automatic differentiation would be amazing, but doesn't seem practical to actually finish within 5 weeks (people get PhDs on this!). Also, Numba doesn't have SSA yet, which makes it more difficult.
2. `@overload` for library modules is definitely useful, but it may not fit into a compiler course requirements depending on the case. I assume you'd want to develop some sort of transformation ideally.
3. Supporting more Python features is tremendously helpful for new users who don't want to deal with Numba errors. Also, the features left at this point are probably not trivial, so you'd get to do some transformations. The `tuple` examples above fit this criteria for example. I'd look at some basic Python tutorials and try them with Numba to figure out what features are the most important.

BTW, I'd avoid the old `Rewrite` passes and write an actual compiler pass. That infrastructure is quite limited.

Just my 2 cents. Thanks for your interest in Numba and compilers in general!

**Comment by noahstier** [comment]
Thanks for the input!

Here's a wild idea: what if numba were able to descend the call graph into non `@numba.jit`-decorated functions and attempt type-inference?

This could be an optional extra compiler pass that would add compile time overhead but might make more functions jit-able in nopython mode, even if they call some non-user code.

**Comment by seibert** [comment]
This has been proposed and implemented (but not merged), and then pivoted to a different approach due to some concerns we have about how useful it turns out to be in practice.  You can see the discussion in this PR: https://github.com/numba/numba/pull/4331

**Comment by ARF1** [comment]
@noahstier If you are looking for some missing python feature to implement, did you see the "unsupported constructs" section in [2.6 Supported Python Features](https://numba.pydata.org/numba-doc/dev/reference/pysupported.html) in the manual?

It mentions among others: 

> set, dict and generator comprehensions

No idea what that would entail though.

**Comment by stuartarchibald** [comment]
If you are looking for something that is actually in the route of optimisation, will have demonstrable performance impact and will also require writing a compiler pass, then I'd suggest fixing this CUDA target "bug": https://github.com/numba/numba/issues/4647. It will approximately involve:
 * Writing a compiler pass to:
   * identify `for x in range(a, b, c)` style loops
   * switch this loop form to `x = a; while (x < b) {loop body; x += c}`
   * Fix up loop bodies etc
 * Work out how to apply this to loop nests
 * Work out how to test the transform worked
 * Work out what the resulting PTX should look like and check it is valid.

I think even completing the first and last points would make for an interesting project that has a meaningful performance impact.

Whilst this does help CUDA performance the actual transform can be tested on the CPU.

**Comment by noahstier** [comment]
Ok we are going to start with @stuartarchibald 's suggestion about rewriting `for x in range(a, b, c)` loops and see where that takes us. Thanks everyone for the ideas!

**Comment by stuartarchibald** [comment]
@noahstier great, you might find this notebook useful as a place to start: https://nbviewer.jupyter.org/github/numba/numba-examples/blob/master/notebooks/Numba_046_developers_release_demo.ipynb as it demonstrates custom passes, pipelines and compilers. If you get stuck, feel free to open issues and/or ask on https://gitter.im/numba/numba.

**Comment by stuartarchibald** [comment]
@noahstier just as a FYI, Numba 0.49 RC 1 is scheduled for tagging on 19th March. If you want to submit patches with view for their inclusion in 0.49, early next week would be ideal, even if it's just a draft, thanks! If they miss 0.49, 0.50 will be about 6-8 weeks after.

**Comment by noahstier** [comment]
Ok thanks for the heads up! We have a working prototype so we should at least be able to submit a draft by then.

**Comment by esc** [comment]
@noahstier just checking in here, how did it turn out?

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
