### ISSUE TITLE
Calling np.dot with integer arrays

### ISSUE THREAD

**Issue by kunamneni117** [numba/numba#5331]
When I used data of all float typed, its working fine.
But in the case of a dataset of all integer data typed, the below error pops.

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function dot at 0x7f5a87be81e0>) with argument(s) of type(s): (array(float64, 2d, C), array(int64, 2d, C))
 * parameterized
In definition 0:
    TypingError: np.dot() arguments must all have the same dtype
    raised from /usr/local/lib/python3.6/dist-packages/numba/typing/npydecl.py:961
In definition 1:
    TypingError: np.dot() arguments must all have the same dtype
    raised from /usr/local/lib/python3.6/dist-packages/numba/typing/npydecl.py:961
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function dot at 0x7f5a87be81e0>)
[2] During: typing of call at /usr/local/lib/python3.6/dist-packages/elpigraph/src/distutils.py (179)

File "../usr/local/lib/python3.6/dist-packages/elpigraph/src/distutils.py", line 179:
def euclidean_distance_square_numba(x1, x2):
    distances =  np.sqrt(-2 * np.dot(x1, x2.T) + np.expand_dims(sum_squares_2d_array_along_axis1(x1), axis=1) + sum_squares_2d_array_along_axis1(x2))
    ^

**Comment by stuartarchibald** [comment]
Thanks for the report. Numba only supports floating point arrays (float32, float64, complex64, complex128 dtypes) in its `np.dot` implementation. This is for a couple of reasons 1) Numba hands off the work in `np.dot` to BLAS routines, these are only available for floating point types 2) due to 1) it's not clear whether to convert integer arrays to `float32` or `float64`, this depends on the use case. The work around is to simple call `.astype()` on the arrays in the `np.dot` call to convert them to a floating point type of your choice.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
