### ISSUE TITLE
Create a parallel.jit interface to make way for OpenCL support

### ISSUE THREAD

**Issue by teoliphant** [numba/numba#545]
Currently, we have CUDA Python in Numba and a cuda.jit decorator along with cuda specific constructs like cuda.synchronize, cuda.local.array and cuda.shared.array.    

Numba should allow people to write code in a way that is independent of the compute context that it will be executed in. 

As a result, I propose that we create another jit function (parallel.jit) which allows for parallel.synchronize, parallel.local.array, and parallel.cache.array primitives.    This function returns an unfinalized function object which has to be further specialized to a compute context in order to be called.    CUDAContext, OpenCLContext, ThreadContext, ProcessContext, would all be possible.   

The parallel.jit decorator returns a new callable object which is further specialized either by using its `__getitem__` method.   `my_func[specialization](...)`  or chaining a decorator `specialization(my_func)(...)`

**Comment by ml31415** [comment]
Is this already outdated and obsolete now, even before it got implemented? Other related projects (pytorch, tensorflow, caffe) seem to move towards ROCM / HIP instead of OpenCL, which promises a rather painless transition from CUDA. How about implementing this instead of OpenCL-support?

https://github.com/pytorch/pytorch/issues/488
https://github.com/tensorflow/tensorflow/issues/22
https://github.com/ROCmSoftwarePlatform/hipCaffe

**Comment by seibert** [comment]
Closing this as we have a ROCm target (PR, to be merged in future).  We would love to make a generic GPU target, but that's not a short or medium term goal.
