### ISSUE TITLE
problem typing a global tuple of specific integer types as literal

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5518]
## Reporting a bug

- [x] I am using the ~latest released~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Since: https://github.com/numba/numba/pull/5182

This:
```python
from numba import njit, types
import numpy as np

x = (types.uint64(10),)

@njit
def foo():
    return x[0]

foo()
```
does this
```
    raise LiteralTypingError("{} cannot be used as a literal".format(ty))
numba.core.errors.LiteralTypingError: Failed in nopython mode pipeline (step: nopython frontend)
<class 'numpy.uint64'> cannot be used as a literal
```
it's because `x` is typed as a `UniTuple(uint64 x 1)`, but the actual value of the global is a tuple size 1 containing a `np.uint64` of value 10. This in turn is because `type.uint64(value)` when evaluated by the interpreter instantiates a `np.uint64(value)`.

As original author, any thoughts on fixing this @luk-f-a ? Should `np.?int??` be special cased in the conversion global value typing so that they can be used as literals? Would such a change of a knock-on effect of erasing e.g. the signedness which may be a valuable property?

This bit of code needs looking at I think:
https://github.com/numba/numba/pull/5182/files#diff-30d845b63b04ca21d10c7f123ade6e57R1482-R1485

CC @gmarkall for CUDA RNG problem that hit this.

**Comment by luk-f-a** [comment]
quite a milestone for me, the first bug found on something I contributed to Numba. :-)
I'll have a look later and let you know.

**Comment by luk-f-a** [comment]
@stuartarchibald , as you already realized, the problem comes from assuming that any subtype of `Integer` can be converted to Literal. So there are three ways forward:
- correct that assumption, refine the testing of the types such that only types in `Literal.ctor_map` get to pass to the next line `typ = ...`. This will remove the regression, keeping the PR improvement for Integer, but not for np.uint
- expand the definition of IntegerLiteral to include uint64, that means adding `Literal.ctor_map[np.uint64] = IntegerLiteral` in `scalars.py`.
- cast np.uint64 to int before attempting to retrieve the literal value.

I am favour in option 2, although we should be aware that it could have unwanted side effects. Option 3 is also good, since we get to cover this use case, but with lower risk of side effects. Option 1 would be the most conservative, maybe more appropriate for a release candidate.

It depends on your risk-tolerance at this point of the release cycle.

**Comment by stuartarchibald** [comment]
@luk-f-a thoughts on https://github.com/stuartarchibald/numba/commit/d39d49cf0e69ff4efbfff6f97f01176627f63ce1 ? I think this is like your option 1 above. It preserves the 0.48 behaviour and also I hope permits the new behaviour.

**Comment by luk-f-a** [comment]
@stuartarchibald , definitely more elegant than mine, I like it!
