### ISSUE TITLE
Implement math.modf for CUDA target

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5545]
## Feature request

As title. Request reference:  https://gitter.im/numba/numba?at=5e8f92d83a85536c431d086f

I've put together a starter patch that does the basic implementation here: https://github.com/stuartarchibald/numba/commit/e17796e04ca5d7e207ffe5532ab3f1f60ae31727
needs some tests adding, generally checking over and a doc update, but hopefully the patch is enough to help someone get a PR going.

CC @gabri94

@gmarkall am marking as a "good second issue" for the CUDA target, pinging you so you can mentor :) thanks!

**Comment by gmarkall** [comment]
Thanks for CCing - I'd be keen / happy to mentor! 

@Gabri94 - if you're interested in working on this, I can provide some pointers if you're not sure where to get started - let me know, either here or on gitter.

**Comment by gabri94** [comment]
Sure, i'll ping you on gitter

**Comment by gmarkall** [comment]
@gabri94 Thanks for having a look into this! It looks like @stuartarchibald's commit already adds the implementation, so to complete it ready for a PR, the following would need adding:

- Tests: These should be added to [test_math.py](https://github.com/numba/numba/blob/master/numba/cuda/tests/cudapy/test_math.py) - there are some templates for adding tests for new functions quickly there, but since `modf` is not quite the same as all the other functions (instead of being a unary or binary function that returns a single value, it is a unary function that returns two values), you will have to do something not using those templates. For some appropriate values to test with, you could check out the test of `modf` in CPython: https://github.com/python/cpython/blob/master/Lib/test/test_math.py#L1114 - you should test with both `float32` and `float64` types to ensure the implementation works with both underlying functions. The CUDA programming guide for these functions suggests that the maximum ULP error for these functions is 0, so the output of the CUDA function should probably match the output from CPython (see https://docs.nvidia.com/cuda/libdevice-users-guide/__nv_modf.html#__nv_modf and https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#mathematical-functions-appendix).
- Documentation: there is a list of supported functions in the CUDA target - `modf` should be added to the list here: http://numba.pydata.org/numba-doc/dev/cuda/cudapysupported.html#math - the source for this document is https://github.com/numba/numba/blob/master/docs/source/cuda/cudapysupported.rst

With @stuartarchibald's commit, these two additions (assuming the tests you add pass!) should make the implementation ready for a PR.

I hope this is helpful for getting started - please let me know if any of the above needs a bit more expansion on / further explanation, or if you have any other questions.

**Comment by stuartarchibald** [comment]
Implemented in #5578, closing. Thanks for the contributions @gabri94 @gmarkall .
