### ISSUE TITLE
Error when install numba by pip

### ISSUE THREAD

**Issue by vietanhle0101** [numba/numba#5855]
I have the following error when trying to install by `pip install numba` on Ubuntu 16.04. Could you show me how to fix it.

``` 
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-U3yvuq
       cwd: /tmp/pip-install-eulNd9/llvmlite/
  Complete output (7 lines):
  running bdist_wheel
  /usr/bin/python /tmp/pip-install-eulNd9/llvmlite/ffi/build.py
    File "/tmp/pip-install-eulNd9/llvmlite/ffi/build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
  error: command '/usr/bin/python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rUBf7g/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/lva/.local/include/python2.7/llvmlite
         cwd: /tmp/pip-install-eulNd9/llvmlite/
    Complete output (10 lines):
    running install
    running build
    got version from file /tmp/pip-install-eulNd9/llvmlite/llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
    running build_ext
    /usr/bin/python /tmp/pip-install-eulNd9/llvmlite/ffi/build.py
      File "/tmp/pip-install-eulNd9/llvmlite/ffi/build.py", line 122
        raise ValueError(msg.format(_ver_check_skip)) from e
                                                         ^
    SyntaxError: invalid syntax
    error: command '/usr/bin/python' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eulNd9/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rUBf7g/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/lva/.local/include/python2.7/llvmlite Check the logs for full command output.
```

**Comment by stuartarchibald** [comment]
Thanks for the report. The latest Numba requires Python >= 3.6. I would guess that your system Python is 2.7 as it doesn't support the `raise <Exception> from <Exception>` syntax (Introduced in PEP 3134, here https://www.python.org/dev/peps/pep-3134/#explicit-exception-chaining). I'd suggest getting newer version of Python, which is >= 3.6, would solve your problems. If this isn't possible, the last version of Numba that supports Python 2.7 is Numba version 0.48, explicitly installing this could also work but you'd miss new features.

**Comment by alexkreimer** [comment]
@stuartarchibald Wouldn't it be better if the error message would say exactly what you said instead of failing with a syntax error?

**Comment by stuartarchibald** [comment]
@alexkreimer yes, definitely, @eric-wieser also suggested similar (but can't find a xref) as IIRC NumPy did something along these lines and then switched to explicit rejection of unsupported pythons. Pull requests are welcomed.

Thanks.

**Comment by eric-wieser** [comment]
The relevant numpy commit is https://github.com/numpy/numpy/commit/dabf31c74f6f3153ef4e7c72ad969c37f8652c8a#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by arjunskumar** [comment]
unable to uninstall numba on ubuntu 18.04

**Comment by esc** [comment]
@arjunskumar thank you for adding to this issue. Since this issue has been closed and resolved, please do open a new issue with the details of your problem:

a) What did you do?
b) What did you expect to happen?
c) What happened instead?

And please include relevant commands and any tool output of error messages that you encounter, thanks.

**Comment by arjunskumar** [comment]
@esc I was trying to run [Voxelnet ROS](https://github.com/AbangLZU/VoxelNetRos) package. Numba was one of the package dependencies.

My python version is 3.6.9 so run 

``` pip3 install numba ```

add encountered with this error  "Failed building wheel for numba"

As per my understanding numba depends on **llvmlite**, I was able to install llvmlite 0.32.0 version separately but when installing numba it creates problem.

**Comment by esc** [comment]
@arjunskumar as I wrote above: *please open a new issue*.

**Comment by Aldurine** [comment]
Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
Requirement already satisfied: numpy>=1.15 in c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages (from numba) (1.19.4)
Requirement already satisfied: setuptools in c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages (from numba) (51.0.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Building wheels for collected packages: numba, llvmlite
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-wheel-3ecop48g'        
       cwd: C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\setup.py", line 354, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\setup.py", line 87, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('c:\\users\\abhiram shetty\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\setup.py", line 354, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\numba_0261f68d3cdd4dddaf6b2c592c3e42b0\setup.py", line 87, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('c:\\users\\abhiram shetty\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-wheel-k7jqb0y5'  
       cwd: C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\
  Complete output (24 lines):
  running bdist_wheel
  c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py
  Trying generator 'Visual Studio 15 2017 Win64'
  Traceback (most recent call last):
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 191, in <module>
      main()
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 179, in main
      main_win32()
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 88, in main_win32
      generator = find_win32_generator()
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 76, in find_win32_generator  
      try_cmake(cmake_dir, build_dir, generator)
    File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 28, in try_cmake
      subprocess.check_call(['cmake', '-G', generator, cmake_dir])
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 368, in check_call
      retcode = call(*popenargs, **kwargs)
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 349, in call
      with Popen(*popenargs, **kwargs) as p:
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  error: command 'c:\\users\\abhiram shetty\\appdata\\local\\programs\\python\\python39\\python.exe' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-record-384f6zsx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\abhiram shetty\appdata\local\programs\python\python39\Include\llvmlite'
         cwd: C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\llvmlite/_version.py {'version': 
'0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py
    Trying generator 'Visual Studio 15 2017 Win64'
    Traceback (most recent call last):
      File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 191, in <module>
        main()
      File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 179, in main
        main_win32()
      File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 76, in find_win32_generator        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-install-npqmg67r\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 368, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 349, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\users\abhiram shetty\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'c:\\users\\abhiram shetty\\appdata\\local\\programs\\python\\python39\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\abhiram shetty\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Abhiram Shetty\\AppData\\Local\\Temp\\pip-install-npqmg67r\\llvmlite_8a3a37d3d0dd4fe2a83f6f0abd50c1a6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Abhiram Shetty\AppData\Local\Temp\pip-record-384f6zsx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\abhiram shetty\appdata\local\programs\python\python39\Include\llvmlite' Check the logs for full command output.

**Comment by esc** [comment]
@Aldurine thank you for submitting this. I can see from the log that you are trying to install Numba on Python 3.9 -- however, this Python version is currently not supported. Please try to use 3.6/3.7/3.8. Thank you for using Numba.

**Comment by JWR126519** [comment]
I have tried this to solve this issue.
$pip install wheel (or pip3 install wheel)

This made some more progress.  But the final solution I found was below.
$sudo apt install python3-numba
