### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by waffletower** [numba/numba#5974]
Thousands of python users, researchers and developers should not have to clean up after poorly conceived and timed module name changes.  I can't believe the python ecosystem tolerates this random breakage.  Sure, in every new virtual environment that has code that consumes numba, one can make a *simple* edit to repair the module reference:

`from numba.decorators import jit as optional_jit`
->
`from numba.core.decorators import jit as optional_jit`

But I have done this 10 times now in the last two weeks.  Please consider being more considerate to those downstream.  Such hubris.  And *please* don't flame me for consumers failing to lock dependency versions -- that is an entirely different, and equally maddening shortcoming of the python ecosystem.

**Comment by stuartarchibald** [comment]
Thanks for the report. Sorry that you've had to make duplicate changes to some environments. The Numba core developers considered this large scale change for quite some time and indeed put it off repeatedly so as to minimise the impact.

From the above I'm guessing your toolchain involved `librosa`? This issue has been raised previously and there's some discussion on the length of deprecation cycles for internal changes here #5865, the outcome being, should we need to do this again, make it more in line with the length of our external API deprecation cycles. The Numba core developers also went and fixed `librosa` as soon as we realised that it was being adversely impacted, we didn't think it'd be using Numba internals but it turns out that this was the case and this is/was scheduled for deprecation (the API location it should have been importing from is the top level i.e. `from numba import jit as optional_jit` see https://github.com/librosa/librosa/pull/1164).

Whilst this unfortunately cannot fix the in-production issues you are having I hope it reassures you that the Numba team is listening.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks for the feedback.
