### ISSUE TITLE
Invalid use of getiter in tuple of arrays

### ISSUE THREAD

**Issue by gauthe** [numba/numba#6239]
Hello!

I get an error when I try to run the following code:
```
import numpy as np
from numba import jit

default = np.array([],dtype=np.int8)
c1 = np.zeros(2,dtype=np.int8)

@jit(nopython=True)
def generate(c1=default, c2=default):
  if not c1.size or not c2.size:
    return default
  nc = np.zeros(min(c1.size,c2.size),dtype=np.int8)
  return nc

@jit(nopython=True)
def combine(*values):
  combined = values[0]
  for v in values[1:]:
    combined = (combined.reshape(combined.size,1)+v).ravel()
  return combined

c2 = generate(c1, c1)
print("try")
c3 = combine(c1, c2, c1)
print('OK')
```

output:
```
try
Traceback (most recent call last):
  File "numba_crash.py", line 23, in <module>
    c3 = combine(c1, c2, c1)
  File "~/miniconda3/envs/idp/lib/python3.7/site-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "~/miniconda3/envs/idp/lib/python3.7/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File ~/miniconda3/envs/idp/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of getiter with parameters (Tuple(readonly array(int8, 1d, C), array(int8, 1d, C)))
 * parameterized
[1] During: typing of intrinsic-call at numba_crash.py (17)

File "numba_crash.py", line 17:
def combine(*values):
    <source elided>
  combined = values[0]
  for v in values[1:]:
  ^
```
Any of the following changes make the execution succeed:
- calling `combine(c1, c2.copy(), c1)`
- calling `combine(c1, c1, c1)`
- calling `combine(c1, c2, c2)`
- removing the `jit` in `generate`
- removing the test `if not c1.size or not c2.size:` in `generate`  (???)

Python 3.7.7 :: Intel(R) Corporation
numpy       1.18.5             py37h6ebd63d_5            intel
numba       0.49.1            np118py37hf484d3e_2    intel

**Comment by stuartarchibald** [comment]
Thanks for the report. What is happening is due to the use of a global as the default value for the `kwargs` `c1` and `c2` in `generate`. Explanation:

1. Numba [sees globals as compile time constants](https://numba.readthedocs.io/en/stable/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable). This means `default` (as in e.g. `return default`) is considered constant and "read only" as a result.
2. When Numba tries to work out the types of the variables in `generate` it sees the branch:
    ```python
      if not c1.size or not c2.size:
        return default
    ```
    and so decides that return type from this branch must be read only. It then see's the `return nc` and to unify this return path with the return path from branch it requires that `nc` is also read only (this is "type unification" you can read more about it [here](https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-has-a-type-unification-problem)). The result of all this being that `generate` returns a read only array such that `c2 = generate(c1, c1)` leads to `c2` being read only.
3. When `combine` is called, the `*values` is the tuple `(c1, c2, c1)` which is then sliced like `values[1:]`  for the loop iteration, this is a tuple `(c2, c1)` which is essentially a "mixed type" tuple as mutability is a type property in Numba's typing system.
4. As a result of 3. Numba cannot iterate the tuple as it is heterogeneous in type and you get the error above. This also explains why `.copy()` fixes it because it's basically making the array mutable such that all the types in the tuple are the same.

Ways to fix it...
1. Make the copy as noted.
2. Flip the `writeable` flag of `c2` in Python:
    ```python
    c2 = generate(c1, c1)
    c2.flags.writeable = True
    ```
3. Use [`literal_unroll`](https://numba.readthedocs.io/en/stable/reference/pysupported.html#heterogeneous-tuples) to version the loop body such that the "mixed type" tuple can be iterated:
    ```python
    import numpy as np
    from numba import jit, literal_unroll

    default = np.array([],dtype=np.int8)
    c1 = np.zeros(2,dtype=np.int8)

    @jit(nopython=True)
    def generate(c1=default, c2=default):
    if not c1.size or not c2.size:
        return default
    nc = np.zeros(min(c1.size, c2.size), dtype=np.int8)
    return nc

    @jit(nopython=True)
    def combine(*values):
    combined = values[0]
    for v in literal_unroll(values[1:]): # <---- UNROLL!
        combined = (combined.reshape(combined.size,1)+v).ravel()
    return combined

    c2 = generate(c1, c1)

    print("try")
    c3 = combine(c1, c2, c1)
    print('OK')
   ```

**Comment by gauthe** [comment]
Thank you very much for you detailed answer. I understood it was a read-only or not problem, but since `combine` only reads the input I could not see why such a crash. Your point 4. makes it clear.

I just returned `default.copy()` in `generate` to get the mutable returned value I need, `nc` has no reason to be read-only.

I did not dig into the heterogeneous tuples section before, since this is expected behavior I think you can close.

**Comment by stuartarchibald** [comment]
> Thank you very much for you detailed answer. I understood it was a read-only or not problem, but since `combine` only reads the input I could not see why such a crash. Your point 4. makes it clear.
> 
> I just returned `default.copy()` in `generate` to get the mutable returned value I need, `nc` has no reason to be read-only.
> 
> I did not dig into the heterogeneous tuples section before, since this is expected behavior I think you can close.

Great, thanks for confirming and thanks for using Numba!
