### ISSUE TITLE
CUDA Simulator not working

### ISSUE THREAD

**Issue by nicolapivaro** [numba/numba#6330]
Hi guys! I have some issue with the simulator.
I'm trying to use the example you show in your documentation:
https://numba.pydata.org/numba-doc/dev/cuda/simulator.html

`import numpy as np

    @cuda.jit(debug=True)
    def vec_add(A, B, out):
        x = cuda.threadIdx.x
        bx = cuda.blockIdx.x
        bdx = cuda.blockDim.x
        if x == 1 and bx == 3:
            from pdb import set_trace;
            set_trace()
        i = bx * bdx + x
        out[i] = A[i] + B[i]

    os.environ["NUMBA_ENABLE_CUDASIM"] = "1"
    A = np.ones((4, 4))
    B = np.ones((4, 4))
    C = np.zeros((4, 4))
    vec_add(A,B,C)`

This the code I'm running and it tells me I can not import inside the function, like if it is still compiling.
"Use of unsupported opcode (IMPORT_NAME) found"
Am I doing something wrong or is not working?
Thank you
Nicola

**Comment by gmarkall** [comment]
You need to set the environment variable `NUMBA_ENABLE_CUDASIM` before you import Numba.

**Comment by gmarkall** [comment]
There are a couple of other issues with your code:

- The inputs `A`, `B`, and `out` are 2D, so the indexing in the last line `out[i] = A[i] + B[i]` adds entire rows - only scalar operations are supported on the CUDA target, so you need to index them like `out[i, j] = A[i, j] + B[i, j]`. To generate the `j` index, you could use a for loop or a 2D grid. Or you could pass in 1D inputs instead.
- There is no kernel launch configuration in `vec_add(A,B,C)` - you need to specify the grid and block dimensions like `vec_add[griddim, blockdim](A,B,C)`.

I've modified the example so that it runs:

```python
import numpy as np
import os
os.environ["NUMBA_ENABLE_CUDASIM"] = "1"

from numba import cuda  # noqa: E402


@cuda.jit(debug=True)
def vec_add(A, B, out):
    x = cuda.threadIdx.x
    bx = cuda.blockIdx.x
    bdx = cuda.blockDim.x
    if x == 1 and bx == 3:
        from pdb import set_trace

        set_trace()
    i = bx * bdx + x
    out[i] = A[i] + B[i]


A = np.ones((16))
B = np.ones((16))
C = np.zeros((16))
vec_add[4, 4](A, B, C)
```

Note that for a vector add, a more canonical way to implement it might be to use the [`cuda.grid()`](https://numba.readthedocs.io/en/stable/cuda/kernels.html?highlight=cuda.grid#absolute-positions) function to simplify the computation of indices:

```python
import numpy as np
import os
os.environ["NUMBA_ENABLE_CUDASIM"] = "1"

from numba import cuda  # noqa: E402


@cuda.jit(debug=True)
def vec_add(A, B, out):
    # Generate a 1D index from the thread and block indices
    i = cuda.grid(1)

    # If our ID exceeds the length of the vectors, return early to avoid
    # writing out of bounds
    if i >= len(out):
        return

    # Vector addition
    out[i] = A[i] + B[i]


A = np.ones((16))
B = np.ones((16))
C = np.zeros((16))

# Purposefully launch with more threads (20) than elements (16) to demonstrate
# that the early return in the kernel is working
vec_add[5, 4](A, B, C)
```

**Comment by nicolapivaro** [comment]
Hi @gmarkall , thank you for your answer.
Yep sorry for my bad code, I was just trying to see if the problem was still present. Now I set the env var before importing numba and it is working!
Probably it's my fault that I'm not such an expert but I think you can add this note about setting the env var before importing to the documentation because I went through several times but I was not able to find an easy solution
Thank you very much for your time! I'm using numba for doing complex stuff and it's definitely a great library!

**Comment by gmarkall** [comment]
You're welcome - glad things are working well for you!

Closing the issue as it is now resolved.

**Comment by gmarkall** [comment]
@nicolapivaro Proposed documentation update in #6331 - would that have helped?
