### ISSUE TITLE
Set maximum Python version for numba and llvmlite sdists?

### ISSUE THREAD

**Issue by seibert** [numba/numba#6482]
When a new minor release of Python comes out, we often get errors reported by users installing Numba (or more likely llvmlite) with pip when it tries to build the package from source since a wheel is not available for the new Python version.   (Example: https://github.com/numba/llvmlite/issues/621#issuecomment-727142311)

This is a problem because:

* Building llvmlite from source is not going to work for most users.
* Even if it does work, Numba is almost certainly not going to work because of bytecode changes or other CPython changes.

Now that Python has accelerated minor releases to yearly, this problem is going to become even more common.

One solution to this problem would be to set a maximum Python version in setup.py for both numba and llvmlite:

https://packaging.python.org/guides/dropping-older-python-versions/#specify-the-version-ranges-for-supported-python-distributions

Normally this option is used to set a minimum Python version, but I don't see why it couldn't define a minimum and maximum.

**Comment by stuartarchibald** [comment]
Assuming this works as expected, I think we should do this and update the docs/readme accordingly.

**Comment by esc** [comment]
I think it's important to get this right. As https://www.python.org/dev/peps/pep-0440/ states:

`As with version matching, the release segment is zero padded as necessary to ensure the release segments are compared with the same length.`

Which means that doing `<=3.8` will effectively yield `3.7.9` rather than `3.8.6`. So in order to get `3.8.6` we can probably use `<3.9` as valid expression. This will need to be double checked though, as and when we implement it.

**Comment by seibert** [comment]
Another thing to check is what sort of error message the user is given when this happens.  I have no idea how informative it is.

**Comment by esc** [comment]
probably the way to do this is to include it in the current rc3 and then produce wheels to check if the constraint works and what the error message looks like.
