### ISSUE TITLE
for loop does not stop when the index exceeds the limit of a np array

### ISSUE THREAD

**Issue by chenxiangyi10** [numba/numba#6483]
Code:
```
import numba
import numpy as np
@numba.jit
def ff():
    a = np.array([1,2])
    l = np.array([[0,0],[0,0]])
    for i in range(0,4):
        l[0,0] = l[0,0] + a[i]
        print(l)
    return l

print(ff())
print(numba.__version__, np.__version__)
```
Result:
[[1 0]
 [0 0]]
[[3 0]
 [0 0]]
[[1980806718323             0]
 [            0             0]]
[[1980806718323             0]
 [            0             0]]
[[1980806718323             0]
 [            0             0]]
0.48.0 1.16.3

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by esc** [comment]
@chenxiangyi10 thank you for reporting this on the Numba issue tracker. Since checking if an index is within bounds is a costly operation, especially in tight loops, this behavior is deactivated by default. You can enable bounds checking using the keyword argument `boundscheck` for the `@jit` decorators like so:

```
 import numpy as np
@numba.jit(boundscheck=True)
def ff():
    a = np.array([1,2])
    l = np.array([[0,0],[0,0]])
    for i in range(0,4):
        l[0,0] = l[0,0] + a[i]
        print(l)
    return l

print(ff())
print(numba.__version__, np.__version__)
```

This will result in:

```
[[1 0]
 [0 0]]
[[3 0]
 [0 0]]
Traceback (most recent call last):
  File "issue6483.py", line 12, in <module>
    print(ff())
IndexError: index is out of bounds
```

For future reference this is documented on: https://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html

I will close this issue now as I believe it has been resolved. Thank you for using Numba!
