### ISSUE TITLE
Numba fails to install on python3.6.9

### ISSUE THREAD

**Issue by arjunskumar** [numba/numba#6485]
I was trying to run [Voxelnet ROS](https://github.com/AbangLZU/VoxelNetRos) package. Numba was one of the package dependencies.
My OS: Ubuntu 18.04
My python version is 3.6.9 so I run 

``` pip3 install numba ```

add encountered with this error  "Failed building wheel for numba"

As per my understanding numba depends on **llvmlite**, I was able to install llvmlite 0.32.0 version separately but when installing numba it creates problem.

**Comment by esc** [comment]
@arjunskumar thank you for reporting this issue. Would you be able to add the error message and output of the `pip3 install numba` command? Thank you.

**Comment by arjunskumar** [comment]
@esc 
![numba_error](https://user-images.githubusercontent.com/61345951/99242488-4c10c300-2825-11eb-81a0-a14c94ab24fb.png)

**Comment by esc** [comment]
@arjunskumar for future reference, when submitting textual representations of bugs, such as reproducers and error logs it is generally advisable to copy and paste the textual output rather than making a screenshot. In this case, it is a problem because the error log is incomplete. Please copy and paste the full `pip3` output including the command you typed until the end of the output, that is, when a new terminal prompt is shown. Thank you.

Also, regarding formatting on Github: triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
The first error in the above screen shot is that a `tbb` installation is found but it's too old and missing the APIs that Numba uses. TBB 2019.5 is the minimum version.

**Comment by esc** [comment]
@stuartarchibald ah, thanks for the heads up! The other question is, of course, why this isn't picking up the pre-compiled wheels, there are two possible reasons for this that I can think of off the top of my head:

* This is on an `aarch64` machine like a Raspberry Pi
* The `pip` version is too old.

Still waiting for the full error log, I hope it will shed more light onto which one of these it could be.

**Comment by esc** [comment]
Even though I was unable to inspect the screenshot with text analysis tools such as `grep` and friends, I spotted the `x86_64` string, which would indicate it probably is not a Raspberry Pi. So everything points to an older `pip`. @arjunskumar which version of `pip` are you using?

**Comment by arjunskumar** [comment]
@esc My `pip` version is `9.0.1`

**Comment by arjunskumar** [comment]
@esc Able to install `numba` after upgrading the pip.

Thanks for your time

**Comment by esc** [comment]
@arjunskumar I am glad it worked out, thanks for reporting back.
