### ISSUE TITLE
Typed List preinitialization not working

### ISSUE THREAD

**Issue by rpopovici** [numba/numba#6540]
Trying to set a list item at index postion is not working

```
from numba import int32, int64, float32, float64, optional
from numba import jit, njit, types, typed, prange

@njit
def foo():
    items = typed.List.empty_list(int64, allocated=1000)
    print(len(items))
    items[0] = 5

foo()
```

I get and index out of range error..

**Comment by esc** [comment]
@rpopovici hi and thank you for reporting this. The `allocated` parameter is intended to pre-allocate memory under the hood for growing the list later. This may be useful for situations where you know you will add X items to list, e.g. during `extend` or `copy`, and you don't want to incur the constant growth of the allocated number of items under the hood. It doesn't work like `np.empty` in this sense that the length of the list is X and the items are heap trash. However, I deliberately said `intended` -- since this doesn't quite work properly yet, due to the reallocation strategy of the list, so it's probably best to avoid this for now.

**Comment by rpopovici** [comment]
@esc thanks for the clarification

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Thanks!
