### ISSUE TITLE
numba.core import issues

### ISSUE THREAD

**Issue by clsmith12** [numba/numba#6569]
## Reporting a bug

- [x ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment]
@clsmith12 thank you for submitting this. In order to debug this further, please supplement this issue with additional information:

* What did you do?
* What did you expect?
* What happened insteadd?

**Comment by clsmith12** [comment]
Hi, thought I had written more in my original but it doesn't seem to be there...

downloaded numba zip from github (due to permissions issues with a company device I am not able to use pip install)
The numba version is 0.45.1 (and I cannot get the latest 0.52?) according to numba.__version__ from this install. (Note, the only way I can install is using the zip file from github! )

I can successfully import numba. but I cannot import numba.core, even when making sure the folder is in sys.path.
I can, however, successfuly "import core" instead (and similar applies to the other sub modules). So by changing all numba.core to core this works. However, this means any thing I am running that uses numba.core needs changing (and same for the other sub modules)

**Comment by esc** [comment]
@clsmith12 thank you for updating this. First of all, this is a very, very unusual situation you are in and probably very few people (if any?) in the Numba community have encountered this kind of situation before. I am afraid I am going to need some additional details in order to continue debugging this:

* What operating system are you on?
* What compilers are available to you on this system?
* What link did you use to download the zip the file?
* What is the name of the zip file that you obtained?
* How did you obtain/install Python in the first place?
* What version of Python is it?
* How did you install Numba into the Python installation from the zip file? What commands did you use? How did you compile it?
* How are you setting up `sys.path`?
* What commands do you use to launch the Python interpreter?
* What error messages do you see, if any?

It's OK if you don't have all the answers here, but please try to answer as best you can so we can get to the next step of debugging. Listing exact commands, their output and any error messages verbatim is likely to help. Thanks!

**Comment by stuartarchibald** [comment]
Are you trying to run numba from the directory in which is was downloaded? That might cause this issue. Another potential problem is that 0.45.1 didn't have `numba.core`, the first version of Numba that had `numba.core` is 0.49 which was following a large refactor when Python 2.7 support was removed. As for downloads of source, you should be able to get a zip of the latest release from here: https://github.com/numba/numba/releases

**Comment by clsmith12** [comment]
Hi, Yes this could be the issue! I'll try next time I can to see if moving
it solves it.

Where should I "extract" the zip file to to make it work best? I have
usually just installed and extracted in my working folder for that project
(as it is quite rare I need to download anything separate and this is the
first time this sort of problem occurred)

I thought that was where I got the install from, but I'll double check and
redownload when I can

Thanks for all your help so far :)

**Comment by stuartarchibald** [comment]
You can extract Numba anywhere you like, it then needs building, there's some instructions [here](https://numba.readthedocs.io/en/latest/user/installing.html#installing-from-source). Am going to close this issue as resolved, if you encounter issues please do post to the Numba discourse forum https://numba.discourse.group or ask questions on IRC: https://gitter.im/numba/numba. Thanks!
