### ISSUE TITLE
Segmentation fault on ubuntu 20

### ISSUE THREAD

**Issue by zillionare** [numba/numba#6604]
## Reporting a bug

- [ X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

construct env:

docker run -it ubuntu:20.10 # 20.04 crashes too

pip install numba==0.50.1

python -c 'import numba'

this will yields:

Segmentation fault. core dumped.

the issue is caused by llvmlite. On ubuntu 20, llvmlite==0.34 will work, howerver, according to peotry's resolve process:

numba numba (0.50.1) which depends on llvmlite (>=0.33.0.dev0,<0.34)

so install numba==0.50.1 will automatically install llvmlite 0.33, which will cause core dump

**Comment by sklam** [comment]
If you need a newer llvmlite, I'd suggest upgrading numba as well. Numba 0.51 will use llvmlite 0.34. Also, the latest version of Numba is 0.52. 

I am unable to guess the cause for the segfault. The major difference between the two llvmlite versions are that 0.33 uses LLVM9 while 0.34 uses LLVM10. Also, LLVM10 requires a newer C++ compiler for C++14. Therefore, we use manylinux2010 images to build the wheels instead of manylinux1.

**Comment by esc** [comment]
Closing this issue, assuming resolved as no additional information was provided.
