### ISSUE TITLE
Retrieve The Oldest and Newest Supported CUDA Versions

### ISSUE THREAD

**Issue by seanlaw** [numba/numba#6645]
## Feature request

The STUMPY Python package depends on `numba` and, when `cuda` is available, it imports submodules that rely on cuda. It checks this by doing something like:

```
from numba import cuda

if cuda.is_available():  # Only import if CUDA is available
    from stumpy import gpu_stump
```

However, `numba` does not currently support CUDA 11.2 and if CUDA 11.2 is installed then the above `if` condition still returns `True`. It would be nice to have function that checks if the available CUDA version is compatible with `numba` like:

```
if cuda.is_available() and cuda.version_is_supported():
    from stumpy import gpu_stump
```

Or, as discussed with @stuartarchibald, maybe it makes more sense to add max/min supported versions enumerated and then make that part of the `cuda.is_available()` check.

**Comment by seibert** [comment]
I would also agree with the approach of combining the version check with the driver check in `cuda.is_available()` to keep things simple for downstream libraries.

**Comment by stuartarchibald** [comment]
Thanks for writing this up @seanlaw, original discussion is here: https://gitter.im/numba/numba?at=6001c07114cec811ec9e267a, as noted in that, CUDA `version++` has not in my memory broken Numba support before which is why sadly these support querying features don't exist. I think this needs to go into 0.53.0 to make sure there's a way to do this for the future.

**Comment by stuartarchibald** [comment]
CC @gmarkall @testhound

**Comment by gmarkall** [comment]
This is addressed in #6666 - After some discussion with @stuartarchibald, I didn't merge the supported version check into `is_available()`, because 

- One might want to proceed even if the version isn't a known-good version (or may want to just emit a warning).
- These kinds of breakages are rare - it's only happened once so far, and is partly due to Numba using a deprecated interface to NVVM for a long time after it was deprecated.

**Comment by seanlaw** [comment]
Thanks for the update and for working on this, @gmarkall! I think having a separate `numba.cuda.is_supported_version()` function is perfectly reasonable.

**Comment by gmarkall** [comment]
@seanlaw I've added a property to get the list of supported versions, from which the max and min supported versions can be derived - I thought about max / min, but just in case we end up with an unsupported version in the middle of the range for some reason, the API won't need changing  in future.

**Comment by seanlaw** [comment]
Fantastic! Thanks, @gmarkall - please feel free to close this issue
