### ISSUE TITLE
CUDA: Cooperative groups in Windows without TCC mode

### ISSUE THREAD

**Issue by emillma** [numba/numba#6765]
---

## Feature request
It is great that cooperative groups was [added in release 0.53](https://numba.readthedocs.io/en/latest/cuda/cooperative_groups.html). I'm wondering when/if it will be available in Windows, without requiring the GPU to be in [TCC mode](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#tesla-compute-cluster-mode-for-windows)?

**Comment by sklam** [comment]
ping @gmarkall

**Comment by gmarkall** [comment]
This is a limitation imposed by the driver, rather than Numba - the documentation describes the limitation mainly to save Windows users with WDDM mode some frustration / confusion if CGs don't work for them (rather than making them hunt for the issue in other docs).

If the driver supports CGs with WDDM devices in future, then that will also work in Numba, but it's something that's outside our control for now.

**Comment by emillma** [comment]
Thanks for clarification! I'll use linux for now.
Again, thanks for the amazing work you are doing!
