### ISSUE TITLE
try: if array.shape[1] -  tuple index out of range. works without numba, doesn't work with @njit(fastmath=True, nogil=True, cache=True)

### ISSUE THREAD

**Issue by segatrade** [numba/numba#6872]
## Reporting a bug
- [+] Numba 0.53.1, Python 3.7.9, Windows 10 64bit. I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [+] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This doctest works fine:
```python
import numpy as np

def example_numba_tri(yp):
    """
    >>> example_numba_tri(np.array([0.1, 0.5, 0.2, 0.3, 0.1, 0.7, 0.6, 0.4, 0.1]))
    array([[0.1, 0.3, 0.6],
           [0.5, 0.1, 0.4],
           [0.2, 0.7, 0.1]])
    """
    try:
        if yp.shape[1] == 3:
            pass
    except:
        yp = yp.reshape(int(len(yp) / 3), -1, order='F')

    return yp
```

Just add `@njit(fastmath=True, nogil=True, cache=True)`:
```python
from numba import njit
import numpy as np

@njit(fastmath=True, nogil=True, cache=True)
def example_numba_tri(yp):
    """
    >>> example_numba_tri(np.array([0.1, 0.5, 0.2, 0.3, 0.1, 0.7, 0.6, 0.4, 0.1]))
    array([[0.1, 0.3, 0.6],
           [0.5, 0.1, 0.4],
           [0.2, 0.7, 0.1]])
    """
    try:
        if yp.shape[1] == 3:
            pass
    except:
        yp = yp.reshape(int(len(yp) / 3), -1, order='F')

    return yp
```
and get an error:
```
    numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x0000020CB55A7608>.
    tuple index out of range
    During: typing of static-get-item at C:/U1/main.py (1675)
    Enable logging at debug level for details.
    
    File "main.py", line 1675:
    def example_numba_tri(yp):
        <source elided>
        try:
            if yp.shape[1] == 3:
            ^
```
I'm expecting that's this works as without numba or some additional info how to fix it. I read https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#pysupported-exception-handling , but seems I did everything as it written there.

**Comment by esc** [comment]
@segatrade thank you for submitting this issue to the Numba issue tracker. The problem you are facing is that Numba cares about the dimensionality of Numpy arrays when compiling code that operates on them. In this case you are trying to compile code that will -- at runtime -- access the element with index `1` in the `shape` tuple. Since Numba knows at compile time, that the array will only have a single dimension -- since this is being used as input during the doctest -- it will refuse to compile this code. The `try` and `catch` doesn't trigger, because the code isn't actually being executed, it is only being inspected by Numba during compilation. As a workaround in this case, I would check the dimensionality and shape outside a `@njit` compiled function and then invoke the appropriate `@njit` compiled function. Hope this helps.

**Comment by segatrade** [comment]
Thank you @esc ! Will make as you recommend. Also this was useful for me https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

**Comment by esc** [comment]
@segatrade thank you for following up and closing this. Glad we were able to resolve the issue and thank you for using Numba!
