### ISSUE TITLE
Slicing UniTuple in a loop fails

### ISSUE THREAD

**Issue by sbushmanov** [numba/numba#7032]
The following doesn't work:

```
t = (0,1,2,3,4,5,6)

@njit
def reduce(t):
    L = len(t)
    a,b,c = t[:3]
    out = a + b + c
    for i in range(3,L,2):
        a,b = t[i:i+2]
        out += a+b
    return out

reduce(t)  

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(UniTuple(int64 x 7), slice<a:b>)
 
There are 22 candidate implementations:
      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(UniTuple(int64 x 7), slice<a:b>)':
       No match.

During: typing of intrinsic-call at <ipython-input-27-85e07e95b310> (9)

File "<ipython-input-27-85e07e95b310>", line 9:
def reduce(t):
    <source elided>
    for i in range(3,L,2):
        a,b = t[i:i+2]
```

though the following does work:

```
@njit
def reduce(t):
    L = len(t)
    a,b,c = t[:3]
    out = a + b + c
    for i in range(3,L,2):
        a,b = t[i], t[i+1]
        out += a+b
    return out
reduce(t)
#21
```
```
import numba
numba.__version__
'0.53.1'
```

I am reporting this as a bug because it's [stated](https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#homogeneous-tuples):

- Tuple unpacking.
- Slicing tuples with a constant slice.

are supported for homogeneous tuples

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue here is that the slices are not constant as far as Numba can work out. Numba is needs to know the types of all the variables at compile time as it's just not possible in this case:
```python
t = (0,1,2,3,4,5,6)

@njit
def reduce(t):
    L = len(t)
    a,b,c = t[:3]
    out = a + b + c
    for i in range(3,L,2):
        a,b = t[i:i+2]
        out += a+b
    return out

reduce(t)  
```
the above loop in `i` is seen by Numba as "the variable `i` is an integer", this means the slice `i: i + 2` is an unknown size at compile time (it's just "some integer to some other integer"), and because that is an unknown size, the return type of the expression `t[i: i + 2]` is not known either.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
