### ISSUE TITLE
List contributors in documentation

### ISSUE THREAD

**Issue by pitrou** [numba/numba#705]
It may be nice to list all contributors in some part of the documentation. We currently have an AUTHORS file at the repo root that seems more or less up-to-date (would be nice to check).

**Comment by esc** [comment]
This is issue is now 6 years old, we can use `git shortlog -sn` or the github page at:

https://github.com/numba/numba/graphs/contributors

I don't think there is much value in duplicating this information into a file. Perhaps we don't even need a link to the github page since this is now "common knowledge"?

**Comment by esc** [comment]
Wow, it seems like between when this issue was reported and now, we even had an `AUTHORS` file --- but then we even removed it:

https://github.com/numba/numba/pull/5207

😎

**Comment by stuartarchibald** [comment]
Authors are highlighted in the release notes and available via git and github, decision to remove the `AUTHORS` file was because there's many ways to get this information and it was seemingly always out of date/not maintained.

**Comment by esc** [comment]
We can still elect to add a line to the docs somewhere as to how to obtain this information, for example a oneliner command or link to the github page with the contributors, but this is by no means urgent.
