### ISSUE TITLE
Initialize NUMBA_DEFAULT_NUM_THREADS with a batch scheduler aware value

### ISSUE THREAD

**Issue by t20100** [numba/numba#7086]
---

## Feature request

As it is `numba` initializes `NUMBA_DEFAULT_NUM_THREADS` with the number of cores of the machine with `multiprocessing.cpu_count()`.
When running a job through a batch scheduler (e.g., SLURM), not all cores might be useable (when the job request does not use an entire compute node).
In this case, using a scheduler aware number of cores sounds a better default, so one does not need to configure the number of threads to use when having requested only part of a machine.

[`multiprocessing.cpu_count`'s doc](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.cpu_count) suggests to use `len(os.sched_getaffinity(0))` ([os.sched_getaffinity](https://docs.python.org/3/library/os.html#os.sched_getaffinity)) when available.

**Comment by stuartarchibald** [comment]
Thanks for the suggestion. IIRC this code hasn't been updated since both Python 2 and 3 had to be supported. Binding threads to accessible cores by default seems like a good option now it's available, `os.sched_getaffinity` is Python 3.3+ https://docs.python.org/3.3/library/os.html#interface-to-the-scheduler.

**Comment by t20100** [comment]
OK, I propose a PR then.

**Comment by javierttgg** [comment]
I believe I am experiencing a related issue when executing processes via SLURM. I often encounter this error message:
```shell
OMP: Error #179: Function Can't open SHM failed:
OMP: System error #0 Sucess
```
This error message leads the process to be aborted and results in a core dump.

Based on what has been mentioned here, would it be sensible to set `NUMBA_DEFAULT_NUM_THREADS` to the number of cpus requested via SLURM? Similarly to what @t20100 said, I am not using all the available resources of the node. I am just requesting part of the cpus (via [`--cpus-per-task`](https://slurm.schedmd.com/sbatch.html#OPT_cpus-per-task)).

**Comment by t20100** [comment]
The purpose of PR #7088 which fixes this issue was to set `NUMBA_DEFAULT_NUM_THREADS` to the number of available cores to the Python process (retreived with [os.sched_getaffinity](https://docs.python.org/3.3/library/os.html#os.sched_getaffinity)), and this should take into account the resources allocated by SLURM.
Anyway having more threads than cores should not crash the process but degrades performances.

**Comment by javierttgg** [comment]
Thanks for the feedback, @t20100. If you have the time, could you suggest any best practices I should follow to address this error? Or is it possible that the error may not be related to this issue?

**Comment by stuartarchibald** [comment]
I'm not sure that this error is to do with threads, it looks like a call to `shm_open` is probably failing somewhere in the OpenMP runtime. Looking at the source code for it in e.g. LLVM's OpenMP implementation (in the LLVM project, look in `openmp/runtime/src/kmp_runtime.cpp` around the start of function `__kmp_register_library_startup`). It seems like the runtime startup tries to create a new shared memory object, and if that fails then it tries to use an existing open one, and it's when that fails the error message `Can't open SHM failed` appears. Are there perhaps two OpenMP runtimes being used in the same process?

**Comment by javierttgg** [comment]
Thank you for your help and for looking into the LLVM code, @stuartarchibald.

I am very new to OpenMP, but could this error be caused by a conflict between the OpenMP implementations used by Numba (v. 0.56.4) and Numpy (v. 1.23.5)? 

On the other hand, since I am currently using these libraries in a conda environment, I believe their implementation should be independent of how SLURM uses OpenMP. However, if this can add more context, this is how I initialize each process via SBATCH:
<details> 
<summary> sbatch script </summary>

```bash
#!/bin/bash

#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=100G
#SBATCH --gres=gpu:1

srun \
--container-mounts=/path1/:/path2 \
--container-workdir=/path2 \
--container-image=nvcr.io#nvidia/cuda:10.2-devel-ubuntu18.04 \
--output=log.out \
bash /path_to_file/file.sh
````

</details>

And this is the (simplified a bit) `file.sh` that is being called:
<details> 
<summary>`file.sh`</summary>

```bash
#!/bin/bash
set -e

# opencv.
apt-get update && apt-get install libgl1 -y

export CONDA_DIR=/path_to_conda/miniconda
export PATH=$CONDA_DIR/bin:$PATH
conda init bash
. ~/.bashrc
. $CONDA_DIR/etc/profile.d/conda.sh

conda activate myenv

bars=(1.0 2.0 3.0)
foos=(1.0 2.0 3.0)

for bar in "${bars[@]}"; do
    for foo in "${foos[@]}"; do

        python module1.py  --bar "$bar"  --foo "$foo"
        python module2.py
        python module3.py --bar "$bar"  --foo "$foo"

    done
done
```

</details>

The current behavior is that, it does one inner-loop iteration, but at the second inner-loop iteration, the error mentioned above is raised:
```
OMP: Error #179: Function Can't open SHM failed:
OMP: System error #0 Sucess
```

**Comment by javierttgg** [comment]
After thinking more about @stuartarchibald's feedback, I think the error may be caused by the use of `set -e` command at the top of the script. This command causes the script to immediately exit  if a command exits with a non-zero status. 

Therefore even though the second part of the error message indicates `OMP: System error #0 Sucess` (which I believe means that the previous error was resolved), the script still results in a core dump because of the non-zero status from the previous error (`OMP: Error #179: Function Can't open SHM failed:`). 

While I need to confirm this by testing the script with set -e removed, I believe this could be a plausible solution. 

Thank you again for your help @stuartarchibald @t20100. I apologize that my issue ultimately does not appear to be directly related to Numba.

**Comment by stuartarchibald** [comment]
@javierttgg no problem, am glad you have some things to test out to try and find the cause of the problem. If the problem persists, perhaps open a new issue, if possible with a minimal working reproducer (SLURM is just running bash scripts so it should be possible to mock this by running multiple processes from a shell?), many thanks.
