### ISSUE TITLE
Silent crash for parallel typed list appending

### ISSUE THREAD

**Issue by RichieHakim** [numba/numba#7126]
I think I found a sharp edge in numba's typed list class. It may be erroneously allowing the `.append()` method when it should be throwing an error? If so, any thoughts on how I should restructure this code to make it work? The following block of code crashes in a standard jupyter notebook, as well as a google colab notebook.
It does not crash if:
- I use `@jit` or `@njit` without `(parallel=True)`
- I use a smaller number of rows for x (ie 2): np.array(np.random.randint(0,100, (2, 10000000)), dtype='float64')

It sometimes crashes if:
- I use a medium number of rows for x, roughly 10-50. Any more than 50 and it almost always crashes: `np.array(np.random.randint(0,100, (20, 1000000)), dtype='float64')`

It continues to crash even if:
- I ensure x is a contiguous array: `np.ascontiguousarray(np.random.randint(0,100, (10, 10000000)), dtype='float64')`
- I use other `dtype`s: `float32`, `int64`, `int8`

```
pip install --upgrade numba
import numpy as np
from numba import njit, jit, prange
from numba.typed import List as tList

x = np.array(np.random.randint(0,100, (10000, 10000)), dtype='float64')

@jit(parallel=True)
# @njit
def mat2nestedTList(x):
    x_list = tList()
    for ii in prange(x.shape[0]):
        x_list.append(x[ii,:])
    return x_list

y = mat2nestedTList(x)
```

The following also fails with similar characteristics. In this I first convert the numpy arrays to a typed list `tList`:

```
@jit(parallel=True)
def mat2nestedTList(x):
    x_list = tList([tList(x[0,:])])
    for ii in prange(1, x.shape[0]):
        x_list.append(tList(x[ii,:]))
    return x_list
```

**Comment by stuartarchibald** [comment]
Thanks for the report. The "crash" is because mutating the structure of a container e.g. a list, in a parallel region is not thread safe, corruption will likely occur and a variety of problems can appear as a result. Docs were added in https://github.com/numba/numba/pull/6918 and the next version of Numba will render these, the doc build from the "latest" commit has them: https://numba.readthedocs.io/en/latest/user/parallel.html#unsupported-operations.
