### ISSUE TITLE
ValueError: unable to broadcast argument 1 to output array

### ISSUE THREAD

**Issue by mkurop** [numba/numba#7199]
I wrote a jitclass which runs without flaws when used without @jitclass(spec) decorator. However if I turn on the compilation with @jitclass the class runs fine for the first call and at the second call it crashes with the error given in the subject line of the issue. The exact error message is:

```
Traceback (most recent call last):
  File "/home/marcin/src/stpltpdecoder/viterbi_pitch_search_on_short_term_residual.py", line 387, in <module>
    ltp_taps, ltp_lags, ltp_variances, costs = ltp_viterbi.frame(params.current_frame_short_term_res)
  File "/home/marcin/miniconda3/envs/ltpstpdecoder/lib/python3.9/site-packages/numba/experimental/jitclass/boxing.py", line 63, in wrapper
    return method(*args, **kwargs)
ValueError: unable to broadcast argument 1 to output array
File "/home/marcin/src/stpltpdecoder/viterbi_pitch_search_on_short_term_residual.py", line 1, 
```

How can I get more info about specific line in the code causing the error?

**Comment by esc** [comment]
@mkurop thank you for posting this to the Numba issue tracker. If you can post a reproducer, i.e. a simple, self-contained, runnable example we will be able to diagnose this further. Note: the statement "that it runs fine on the first execution but not after that" would indicate that it may have something to do with caching of compilation results and loading those, potentially, so that will be something to look into.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
