### ISSUE TITLE
Suppress `fprintf(stderr, ...)` from tbb

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#7436]
Currently, when something goes wrong when executing `tbb::prepare_fork`, the implementation writes to `stderr` using `fprintf` function (see snippet below). However, it does not seem possible to capture `stderr` from Python when using `tbb` as the threading layer. If possible, I'd like to suppress this message by returning the error to the python land.

https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/tbbpool.cpp#L237-L241

Also, I checked what is the current behavior the other two threading layer implementations (workqueue, OpenMP) do when they write to `stderr`. And both raise ~an error~ a signal after the `fprintf` statement — `SIGABRT` on workqueue and `SIGTERM` on OpenMP. Hence, I wonder if the same shouldn't be applied to `tbb` as well?

https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/omppool.cpp#L116-L122

https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/workqueue.c#L337-L344

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this should be raised for discussion at today's public meeting:
https://numba.discourse.group/t/weekly-public-meeting-every-tuesday-for-2021/658/2

> Currently, when something goes wrong when executing `tbb::prepare_fork`, the implementation writes to `stderr` using `fprintf` function (see snippet below). However, it does not seem possible to capture `stderr` from Python when using `tbb` as the threading layer. If possible, I'd like to suppress this message by returning the error to the python land.

I'm not sure how feasible this is, multiple threads could all hit that block and then "raise". Also, currently, there's no mechanism for unwinding in the threading layers, though I suppose with quite a bit of work all this might be possible. Further, the use of `raise(3)` is to prevent these issues being caught and ignored. If the issue does occur, the safest thing to do is stop, the consequence of ignoring it will likely be one of segfault/deadlock/corruption.

I'm wondering what the underlying issue is here? Is it that the message occurs and your application can guarantee it is not a problem (i.e. the TBB library is definitely still in a valid state) and you wish for it to be suppressed?

-------------------------------------

> https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/tbbpool.cpp#L237-L241
> 
> Also, I checked what is the current behavior the other two threading layer implementations (workqueue, OpenMP) do when they write to `stderr`. And both raise an error after the `fprintf` statement — `SIGABRT` on workqueue and `SIGTERM` on OpenMP. Hence, I wonder if the same shouldn't be applied to `tbb` as well?

I'm not sure it's applicable to TBB. At present TBB informs the user over `stderr` that the TBB library _may_ be in an invalid state, I'm not sure that it is a guarantee that it _is_ in an invalid state (the threads could have been parked ok etc).  @Hardcode84 do you have a view on this?

> https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/omppool.cpp#L116-L122

The GNU OpenMP implementation (check the `_NOT_FORKSAFE` definition) is not fork safe, calling fork is invalid and often leads to hung processes, this is why it `SIGTERM`s. The LLVM-OpenMP derived OpenMP implementations are seemingly fork safe and so this restriction does not apply.

> https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/np/ufunc/workqueue.c#L337-L344

Workqueue is fork safe, but not threadsafe, this code is designed to catch the case where a thread from the workqueue thread pool attempts to launch a parallel region (which would create nested parallelism and require thread safety given the current implementation's use of a global `queues` structure). The consequence of not catching this is hang/segfault/corruption in the order of most to least likely.
