### ISSUE TITLE
Numba CUDA Matrix Multiplication Example

### ISSUE THREAD

**Issue by susuter** [numba/numba#7679]
## Reporting a bug

- [] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [y] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When executing the example https://numba.pydata.org/numba-doc/dev/cuda/examples.html, the resulting matrix is not filled entirely - only first column. The grid index j is always 0. I was trying it on different computing clusters with jupyter notebooks, e.g., Colab, where numba is of version: 0.54.1. I was not able to run it with the latest numba 0.55.0rc1, but the example seems the same for varying versions. On another cluster, I had the same problems with numba 0.53.1. Input were np arrays of float32 - varying shapes.

See Colab Notebook: https://colab.research.google.com/drive/1uewkzBaGEcrr9CCPeyR0YtJus9I3Nvwf

Would you check that? Do you have any idea on that?

Thanks in advance!

**Comment by gmarkall** [comment]
The documentation linked is for an old version (unfortunately Google tends to prioritise it in search results) - the current documentation, which has undergone some fixes to the matrix multiplication example, is at: https://numba.readthedocs.io/en/latest/cuda/examples.html

Could you try the example from the current version of the docs with and let me know if you have any further issues with it please?

**Comment by susuter** [comment]
Thank you for your fast reply. I checked the example on the link. The code is actually the same and I experience the same problem. I saw there is a sample program call on this page. Hence, I tried it with that sample program call. I get the same problem. It really surprises me that the second grid-index is always 0. Would you look into that?

**Comment by gmarkall** [comment]
Many thanks for following up!

> I checked the example on the link. The code is actually the same and I experience the same problem.

I'm seeing different code on https://numba.pydata.org/numba-doc/dev/cuda/examples.html (the outdated version) and https://numba.readthedocs.io/en/latest/cuda/examples.html (the latest version) - the `matmul` kernel looks the same but otherwise the examples are different and there are no examples of launching the kernel on the old documentation. 

> I saw there is a sample program call on this page. Hence, I tried it with that sample program call.

Can you indicate where the sample program call is please (if it's somewhere in the latest docs)? Maybe we have something else in the docs that needs fixing.

> See Colab Notebook: https://colab.research.google.com/drive/1uewkzBaGEcrr9CCPeyR0YtJus9I3Nvwf

The issue in the Colab notebook is that the kernel expects a 2D grid to be launched:

```python
    i, j = cuda.grid(2)
```

but it is only launched with a 1D grid:

```python
matmul[100, 10](x_d, y_d, z_d, j_d)
```

and

```python
matmul[100,100](Ax, Bx, Cx, Dx)
```

The launch configuration is `[100, 10]` in the first case - this specifies 100 blocks with 10 threads each. Because the block and thread counts are both integers, this gives a 1D grid. For a 2D grid, a tuple of two integers is needed - for example `[(16, 16), (16, 16)]` would launch a grid of 256 blocks (indexed 0-15 in the `x` and `y` directions) with 256 threads each (indexed similarly) - when you call `cuda.grid(2)`, with this grid, threads will get linear indices in the `i` and `j` directions from 0 to 256.

If I modify the example to:

```python
import numba.cuda as cuda
import numpy as np

from scipy.spatial.distance import cdist
def sample_random_matrices(shape=(10000, 12)):
    A = np.random.uniform(low=0, high=10, size=shape).astype('float32')
    B = np.random.uniform(low=0, high=10, size=shape).astype('float32')
    return (A, B)

A, B = sample_random_matrices((10, 10))

@cuda.jit
def matmul(A, B, C, D):
    """Perform square matrix multiplication of C = A * B
    """
    i, j = cuda.grid(2)
    if i < C.shape[0] and j < C.shape[1]:
        tmp = 0.
        for k in range(A.shape[1]):
            tmp += A[i, k] * B[k, j]
        C[i, j] = tmp
        D[i,j] = j # I added this for debugging

x_h = np.arange(16).reshape([4, 4])
y_h = np.ones([4, 4])
z_h = np.zeros([4, 4])
j_h = np.zeros([4, 4])

x_d = cuda.to_device(x_h)
y_d = cuda.to_device(y_h)
z_d = cuda.to_device(z_h)
j_d = cuda.to_device(j_h)
matmul[(16, 16), (16, 16)](x_d, y_d, z_d, j_d)

z_h = z_d.copy_to_host()
print(z_h)
print(x_h @ y_h)
print(j_h)

Ax = cuda.to_device(A)
Bx = cuda.to_device(B)
Cx = cuda.to_device(np.zeros((A.shape[0], B.shape[0])))
Dx = cuda.to_device(np.zeros((A.shape[0], B.shape[0])))
matmul[(16, 16), (16, 16)](Ax, Bx, Cx, Dx)
print(Cx.copy_to_host())
print(Dx.copy_to_host())
```

(changing only the launch configurations) then I see something more like the expected output:

```
[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]
[[ 6.  6.  6.  6.]
 [22. 22. 22. 22.]
 [38. 38. 38. 38.]
 [54. 54. 54. 54.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[249.87261713 313.07865143 209.58553076 244.1478464  217.38066101
  318.74053323 309.76656651 291.96589042 249.94237232 147.35430205]
 [260.6976195  357.10091817 330.71861242 259.75077581 251.72307724
  284.95743108 307.94959664 269.22208583 385.58931137 195.42942913]
 [180.12683988 271.98820102 236.52935559 253.6248225  233.6863488
  266.50044078 297.90274349 307.20661497 320.31302911 167.13173914]
 [228.13237385 332.30381697 330.16674238 298.00583589 297.13931757
  331.49501956 349.9528023  236.99694943 317.58276355 122.79185259]
 [139.92408329 149.71064186 175.63796236 162.51503634 151.26873815
  154.01246405 157.17066383 113.24720639 155.41767436  85.52878535]
 [200.28756336 225.48515393 193.96134476 239.54317093 182.5774959
  236.75509304 227.54154447 285.0426965  245.85817757 166.58735791]
 [249.29658222 308.7960968  304.28998369 303.3711338  272.64448404
  279.08416557 321.99890471 287.06416237 333.2822969  179.70512021]
 [171.18225312 256.26159596 225.62362854 177.57702494 146.21885681
  221.27058744 231.78220868 223.25419042 244.2670165  120.40871036]
 [254.54236126 321.86655855 318.65384376 298.75729644 234.83665276
  300.92816544 305.88058949 333.78230983 343.4093008  203.49224466]
 [111.72266674 222.87717675 198.06035076 183.56449734 163.17205437
  260.02304285 174.65724741 209.11999405 255.10041247 145.17321874]]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
```

If you make a similar modification, do you get the output you expect?

Note that if you use the code above with larger matrices (more than 256 elements in either direction) then you will need a bigger grid. The example from the new documentation includes a section on launching the kernel, which computes an appropriate launch configuration based on the size of the matrix: https://numba.readthedocs.io/en/latest/cuda/examples.html#id4:

```python
# Controls threads per block and shared memory usage.
# The computation will be done on blocks of TPBxTPB elements.
# TPB should not be larger than 32 in this example
TPB = 16

# ...

threadsperblock = (TPB, TPB)
blockspergrid_x = math.ceil(z_h.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(z_h.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

fast_matmul[blockspergrid, threadsperblock](x_d, y_d, z_d)
```

[Chapter 2 of the CUDA C++ Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#programming-model) provides some further background information on launch configurations - although the example code there is in C++, the general principles of execution outlined there also apply in Python.

I hope this is helpful - if anything above needs clarification, please do let me know. If you have additional questions / issues in future, the [Numba Discourse](https://numba.discourse.group) can also be a good place to ask - it has more active users answering questions than the Issue tracker.

**Comment by susuter** [comment]
Thanks a lot for all the details and links. That helped a lot and solved the problem. Now I get the correct results. I see that I overlooked that the 2D grid requires tuples for each value. On the latest documentation page, for the fast_matmul() kernel the launch sample it is correctly stated. From a user experience perspective, it would be nice to have this sample call to launch the matmul() kernel in an analogous ways. All in all the latest documentation with the sample calls to launch the kernel is definitely a very helpful.

**Comment by gmarkall** [comment]
> That helped a lot and solved the problem. Now I get the correct results.

Many thanks for confirming!

> On the latest documentation page, for the fast_matmul() kernel the launch sample it is correctly stated. From a user experience perspective, it would be nice to have this sample call to launch the matmul() kernel in an analogous ways.

This is a good point - will look at updating the docs.

> All in all the latest documentation with the sample calls to launch the kernel is definitely a very helpful.

Many thanks for your kind words! I've created a PR that adds a sample call to the `matmul` kernel: https://github.com/numba/numba/pull/7680

If you could have a look at the updated page (hosted at https://numba--7680.org.readthedocs.build/en/7680/cuda/examples.html) and provide and feedback / further comments on the PR https://github.com/numba/numba/pull/7680, that would be much appreciated!

**Comment by gmarkall** [comment]
Closing as it appears that the original issue is resolved and no further follow-up has been received.
