### ISSUE TITLE
`np.nanmean` doesn't ignore nans in fastmath mode

### ISSUE THREAD

**Issue by githubpsyche** [numba/numba#7701]
```python
from numba import njit
import numpy as np

@njit(fastmath=True)
def nanmean(x):
    return np.nanmean(x)

nanmean(np.array([2.0, np.nan, 4.0]))
```

Returns nan. Setting fastmath to False of course returns the appropriate value. 

I'm sure it has something to do with how fastmath shaves off runtime, but but this deficiency more or less defeats the point of using `np.nanmean` in the first place (and was tough to debug for!), so I figured I'd report it and let developers decide if this outcome is a problem or not.

**Comment by stuartarchibald** [comment]
Thanks for the report. This happens almost certainly because of the `np.nanmean` implementation using `np.isnan` to detect `NaN`:
https://github.com/numba/numba/blob/0994f97c33a19d7684471cc98b8c36573762204b/numba/np/arraymath.py#L1092-L1109
when `fastmath` is enabled, it tells the compiler to assume there are no `NaN`s present, and so it optimises out the check (docs: https://numba.readthedocs.io/en/stable/user/performance-tips.html#fastmath, the Numba `fastmath` kwarg follows the LLVM fast-math flag behaviours).

I'm wondering if Numba ought to raise a warning if `isnan` is in use with `fastmath`, will raise this at the next public development meeting.

**Comment by gmarkall** [comment]
Note: the plan is to eventually present a warning if isnan is used with fastmath.

**Comment by kalvdans** [comment]
I think it is is a bug, since the only reason to use `nanmean` instead of `mean` is that you have marked missing elements with NaN:s on purpose.

**Comment by stuartarchibald** [comment]
#8708 tracks providing the warning mentioned above.
