### ISSUE TITLE
Fix documentation with dependency package versions

### ISSUE THREAD

**Issue by b5y** [numba/numba#7795]
---
In the [README.md](https://github.com/numba/numba#dependencies) documentation you have the following dependency packages with their versions:

```
Python versions: 3.7-3.10
llvmlite 0.39.*
NumPy >=1.18 (can build with 1.11 for ABI compatibility).
```

But if you run `conda install -c numba numba` (the [provided command](https://github.com/numba/numba#installing) `conda install numba` doesn't show `Numba`'s recent version)

```bash
(numba) ubuntu@<instance_node>:~$ python --version
Python 3.8.12
(numba) ubuntu@<instance_node>:~$ conda install -c numba numba
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/anaconda3/envs/numba

  added / updated specs:
    - numba


The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  llvmlite           numba/linux-64::llvmlite-0.38.0-py38he1b5a44_0
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py38h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py38hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py38h51133e4_0
  numba              numba/linux-64::numba-0.55.0-np1.11py3.8hc13618b_gd44b8f446_0
  numpy              pkgs/main/linux-64::numpy-1.21.2-py38h20f2e39_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.21.2-py38h79a1101_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0


Proceed ([y]/n)?
```

You get different version for `llvmlite`. The conda version is `conda 4.11.0`.

## Feature request

Update the documentation or dependency version in deployment.

**Comment by esc** [comment]
@b5y thank you for bringing this to our attention. Maybe you can suggest a good course of action:

0.55.* (released) needs llvmlite 0.38 (released)
0.56.* (not released yet) will required llvmlite 0.39 (also not released yet)

Maybe we need different sections for the dependencies of the latest stable release and whatever the main branch will be called (currently still `master`)?

Also, since we do have additional documentation at:

https://numba.readthedocs.io/en/stable/user/installing.html

Maybe now is the time to shorten the README and instead defer to the Sphinx based documentation?

**Comment by esc** [comment]
I have created a suggestion here:

https://github.com/numba/numba/pull/7797

**Comment by esc** [comment]
The `README` is now pruned: https://github.com/numba/numba/pull/7797 @b5y thank you for mentioning this.
