### ISSUE TITLE
NumPy Dependency

### ISSUE THREAD

**Issue by priyashmistry** [numba/numba#7803]
---

## Feature request

Actually I'm using one python package VESPA that contains the both NumPy and Numba. 

In which NumPy wants the version 1.22.1, and currently Numba isn't supported this version. 

Can you please check for this dependency in future update?

**Comment by esc** [comment]
@priyashmistry thank you for asking about this! NumPy 1.22 is currently not supported by Numba, the ticket is here:

https://github.com/numba/numba/issues/7754

Please subscribe to that one for updates about Numba with NumPy 1.22, thank you.

**Comment by priyashmistry** [comment]
@esc Thank you for the reply. 

If you don't mind, may I ask you how much time it will take to do this update? Because I am doing one project and due to this issue it causes some problem.

**Comment by esc** [comment]
> @esc Thank you for the reply.
> 
> If you don't mind, may I ask you how much time it will take to do this update? Because I am doing one project and due to this issue it causes some problem.

Thank you for asking about this. We do not have a concrete estimated time or arrival. Judging from experience however, it is likely that the NumPy 1.22 support will arrive with Numba 0.56 -- probably around 3-4 months from now. You'll be able to use nightly builds with NumPy 1.22 support earlier than that (basically when the PR is merged), so I would recommend subscribing to #7754 to be notified when that issue is resolved.
