### ISSUE TITLE
llvmlite version issue while running tests 

### ISSUE THREAD

**Issue by odidev** [numba/numba#7932]
Hi Team, 

I tried testing **numba** package on both architectures but it is generating below error for the `python -m numba.tests.test_runtests` command locally: 

```
(numbaenv) root@b5e3309d8d22:/numba# python -m numba.tests.test_runtests 

Traceback (most recent call last): 

  File "/root/miniconda3/envs/numbaenv/lib/python3.8/runpy.py", line 185, in _run_module_as_main 

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 

  File "/root/miniconda3/envs/numbaenv/lib/python3.8/runpy.py", line 111, in _get_module_details 

    __import__(pkg_name) 

  File "/numba/numba/__init__.py", line 197, in <module> 

    _ensure_llvm() 

  File "/numba/numba/__init__.py", line 111, in _ensure_llvm 

    raise ImportError(msg) 

ImportError: Numba requires at least version 0.39.0 of llvmlite. 

Installed version is 0.38.0rc1. 

Please update llvmlite. 

```

I checked for **llvmlite** version in pypi and found that till this point version 0.38.0 is the latest version present, refer [this](https://pypi.org/project/llvmlite/#history). 
So I modified these two files named **setup.py** and **/numba/numba/__init__.py** with minimum version of `llvmlite as 0.38.0` as given in [pypi link](https://pypi.org/project/llvmlite/#history). 

After the above modification, I am getting successfully result as follows: 

**Result at Aarch64:**  `Ran 545 tests (68 skipped )`
**logs at Aarch64:** [test_numba_arm64_with_py38(ran 545 (68 skipped)).txt](https://github.com/numba/numba/files/8325591/test_numba_arm64_with_py38.ran.545.68.skipped.txt)

**Result at x86_64:** `Ran 545 tests (66 skipped and 1 failed) with Assertion error `
**logs at x86_64:**  [test_numba_x86_with_py38(ran 545 (66 skipped and 1 failed with assertion error)).txt](https://github.com/numba/numba/files/8325593/test_numba_x86_with_py38.ran.545.66.skipped.and.1.failed.with.assertion.error.txt)

@esc Could you please share your feedback regarding this? Also would you like us to raise a PR for the same?  
Thanks in advance.

**Comment by esc** [comment]
@odidev thank you for asking about this!

> @esc Could you please share your feedback regarding this? Also would you like us to raise a PR for the same? Thanks in advance.

This looks like you installed `numba` maybe from a source checkout? If so, you will need a development version of llvmlite. We do not ship compatible PyPi packages for these and instead recommend the use of `conda`.

You can install the development version with:

```
conda install -c numba/label/dev llvmlite
```

You can also check the version support information here: https://numba.readthedocs.io/en/latest/user/installing.html#version-support-information

There is also developer information at: https://numba.readthedocs.io/en/latest/developer/contributing.html#build-environment -- but after a first glance this appears outdated.

If you really do need llvmlite development versions from PyPi, please do open a new feature-request.

You do not need to supply a pull-request for the changes to the files, the way they are setup is intentional and correct.

**Comment by esc** [comment]
@odidevI hope that my explanation was clear and since no followup question was posted I am assuming this issue is resolved for now. If this is not the case, please don't hesitate to re-open the issue with additional discussion!

**Comment by odidev** [comment]
@esc Could you please share your feedback regarding this?
