### ISSUE TITLE
how to call guvectorize cuda 

### ISSUE THREAD

**Issue by FUNCTOR99** [numba/numba#8261]
I am just getting started working with numba.  I need to create a function that will run on my 1060 gpu.  I have a Basic scalar function working with vectorize, but I need to use guvectorize for the inputs required.  Here is my attempt so far...

```
  @guvectorize(['void(int32[:], int32[:], float32[:], float32[:], float32[:], float32[:], float32[:])'], '(i),(i),(i),(j),(j),(j)->(i)', nopython=True, target='cuda')
  
    def analyze(input_a, input_b, input_c, read_only_data_x, read_only_data_y, read_only_data_z, output):
  
	  for i in range(input_a, input_b):
  
		  output = output + ((read_only_data_x[i] + read_only_data_y[i]) / read_only_data_z[i]) + input_c
```

I have a few read only arrays that I will eventually transfer to the device.  For any iteration, I only want a section of these arrays used, provided by the input_a and input_b fields.  These input arrays are the combinations that I want parallelized.  I am getting an error though, 

"There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Type Restricted Function in function 'range': File: unknown: Line unknown.
    With argument(s): '(array(int32, 1d, A), array(int32, 1d, A))':
   No match for registered cases:"

I get it that this error points to the range function and that its seeing input_a and input_b as arrays and not the intended int32.  

I'm been trying to find some examples to go from but can't seem to find much.  If anyone can @ the very least point me to some resources or has any advice, I'd really appreciate it!

Thanks!

**Comment by stuartarchibald** [comment]
Thanks for the report, this looks like a general question, for the future there's a couple of places to get help with this sort of thing, if you try opening a new issue on the issue tracker there are instructions in there offering guidance about discussion forums and IRC channels.

To the above, the issue is that `input_a` and `input_b` have been declared as array types in the signature and `range()` doesn't know what to do with arrays. `int32[:]` is Numba's short hand for "1d array of int32". You can find out what a type specified in the signature string will evaluate as by running the same against the members of `numba.types`. For example:
```pycon
In [1]: from numba import types

In [2]: types.int32[:]
Out[2]: array(int32, 1d, A)
```

Regarding the description of your problem. `guvectorize` is used to create a minimally dimensioned "kernel" that can be broadcast over higher dimensional data. It seems like the data you have needs to be masked opposed to broadcast? To make use of `guvectorize` the data may need reshaping.

CC @gmarkall who might be able to provide some advice with regards to the CUDA target.

**Comment by gmarkall** [comment]
I think there's no particular CUDA-specific issues here - if you can get the gufunc to work with nopython mode, then I would expect switching to `target='cuda'` to just work (based on the code example and what you're trying to do).

For general questions about Numba, it may be better to post on the [Discourse Group](https://numba.discourse.group/), as there are more users there who might be able to provide guidance.

**Comment by FUNCTOR99** [comment]
Thank you very much for these resources!  I'll take a closer look.
