### ISSUE TITLE
Allow multiple outputs for `guvectorize` on CUDA target

### ISSUE THREAD

**Issue by s-m-e** [numba/numba#8303]
## Feature request

The following works just fine for targets `cpu` and `parallel` ...

```python
from numba import guvectorize
import numpy as np

@guvectorize(
   'void(f8[:],f8[:],f8[:],f8[:],f8[:],f8[:])',
    '(n),(n),(n)->(n),(n),(n)',
    target = 'cpu',
    nopython = True,
)
def foo(a, b, c, x, y, z):
    for idx in range(a.shape[0]):
        x[idx], y[idx], z[idx] = a[idx] * b[idx], b[idx] * c[idx], c[idx] * a[idx]

LEN = 100_000_000

data = np.arange(0, 3 * LEN, dtype = 'f8').reshape(3, LEN)
res = np.zeros_like(data)

foo(data[0], data[1], data[2], res[0], res[1], res[2])  # providing views on `res`

print(res)
```

... but fails to compile with `AssertionError: only support 1 output` for target `cuda`. It would be *really* useful if this would also work for CUDA.

In the meantime, the current behavior is, as far as I can tell, not documented.

---

For a longer discussion, context and examples, see [here](https://numba.discourse.group/t/returning-an-array-of-3d-or-6d-vectors-from-guvectorize-on-cuda-cross-compiling-for-cpu-cuda/1473).

**Comment by guilhermeleobas** [comment]
Hi @s-m-e, thanks for the report. I'll put this up for discussion at the next triage meeting.

**Comment by gmarkall** [comment]
@s-m-e I'm starting working on this on this branch: https://github.com/gmarkall/numba/tree/issue-8303

Presently I'm just hacking away to see what needs changing ("brute force" modifications :slightly_smiling_face:) because I'm not too familiar with the code in this area. Hopefully it will just need a bunch of small fixes to turn the assumption of a single output into iterations over multiple outputs in various locations.
