### ISSUE TITLE
[-1] call to cuInit results in UNKNOWN_CUDA_ERROR

### ISSUE THREAD

**Issue by leeyegy** [numba/numba#8395]
## Reporting a bug

My enviroments:
Numba: 0.48.0
CUDA: 10.2
CUDnn: 8.2
I am using 2080 Ti right now.

When I run `numba -s`, the bug comes to me:

Error: CUDA device intialisation problem. Message: Error at driver init:
[-1 ]call to cuInit results in UNKNOWN_CUDA_ERROR:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

Any suggestions would be greatly appreciated!

**Comment by gmarkall** [comment]
Do any other CUDA programs work on your system?

**Comment by gmarkall** [comment]
Also, note that Numba 0.48 and CUDA 10.2 are quite old - I'd suggest upgrading to Numba 0.56, CUDA 11.7, and the latest CUDA driver.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Comment by lifan67** [comment]
Reporting a bug 
When I run numba -s, the bug comes to me:
__Warning log__
Warning (cuda): CUDA device initialisation problem. Message:Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (-1)
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
__When you run the program,the bug comes to me:__
raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (-1)
__Can you help me?__

**Comment by lifan67** [comment]
When I run numba -s, the bug comes to me:
Warning log
Warning (cuda): CUDA device initialisation problem. Message:Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (-1)
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
When you run the program,the bug comes to me:
raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (-1)
Can you help me?
