### ISSUE TITLE
CUDA ignores casts

### ISSUE THREAD

**Issue by academe-01** [numba/numba#8447]
Using following simple example I can't understand why int32 casts to int64.
Any suggestions, guys ?

```!python
import numba as nb
import numpy as np
from numba import cuda, int16, int32
from numba.cuda import libdevice

@cuda.jit(device=True)
def test_func():
    a = nb.int32(1)
    b = nb.int32(1)

    a += b

    return a

@cuda.jit()
def test():
    if cuda.grid(1) > 0:
        return

    a = test_func()

test[16, 1]()
cuda.synchronize()
```

```numba --annotate-html m.html numba_test.py```

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/95714796/191049446-8becc30d-5a89-425f-a76e-887ca981f6a2.png">

**Comment by stuartarchibald** [comment]
Thanks for the report. This is due to Numba's type inference behaviour and is invariant of the CUDA target. This would also reproduce on the CPU target:
```python
from numba import njit, int32
import numpy as np

@njit(())
def foo():
    a = int32(1)
    b = int32(1)

    a += b

foo.inspect_types()
```
which yields:
```
    #   a.1 = inplace_binop(fn=<built-in function iadd>, immutable_fn=<built-in function add>, lhs=a, rhs=b, static_lhs=Undefined, static_rhs=Undefined)  :: int64
```
i.e. the `+=` results in an `int64` type for `a`. The reason this happens at present is that there's no typing rule for `int32` under `operator.iadd` so it will match on the closest thing, which is an `operator.iadd(int64, int64) -> int64` rule which matches at the "machine" integer size. The reason it is implemented like this is explained in the Numba Enhancement Proposal 1 (NBEP 1): https://numba.readthedocs.io/en/stable/proposals/integer-typing.html.

I think if you want to use `a` as an `int32` after the `+=`, a cast of `a` would work.

**Comment by academe-01** [comment]
@stuartarchibald 
if I cast final result GPU won’t utilize full performance of operations. There is a huge penalty of INT64 vs INT32/INT16/…

how can I overcome it ?
