### ISSUE TITLE
TypingError for numpy.empty and numpy.zeros

### ISSUE THREAD

**Issue by jfmoulin** [numba/numba#858]
Under numba 0.15.1 and python 2.7.7 (Linux Mint 17 64 bit)

I get a TypingError upon compilation of functions using numpy.empty or numpy.zeros as locals:
```
@jit(nopython=True)
def foo():
    temp = numpy.empty(10,10)

# I also tried to use a locals argument to jit
@jit(locals={'temp':numba.types.float64[:,:]}, nopython=True)
def foo():
    temp = numpy.empty(10,10)

```
on calling foo(), the traceback is:
```
numba.typeinfer.TypingError: Failed at nopython frontend
Untyped global name 'empty'
File "test_numba.py", line 31
File "/home/jfmoulin/My_Git/sandbox/test_numba.py", line 46, in <module>
  print foo()
File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 145, in _compile_for_args
  return self.jit(sig)
File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 136, in jit
  return self.compile(sig, **kws)
File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 271, in compile
  flags=flags, locals=locs)
File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 551, in compile_extra
  return pipeline.compile_extra(func)
File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 261, in compile_extra
  return self.compile_bytecode(res.result, func_attr=self.func_attr)
File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 275, in compile_bytecode
  return self._compile_bytecode()
File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 501, in _compile_bytecode
  return self._run_pipeline(pipelines)
File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 526, in _run_pipeline
  raise _raise_error(msg, res.exception)
```

**Comment by DavidPowell** [comment]
I am writing code where most of my variables are Cartesian vectors, so they are implemented as fixed-size arrays, which need to be created inside the function. Due to this issue, I am finding that `numba.jit` does not give any speedup at all, and fails with `nopython=True`.

**Comment by pitrou** [comment]
If your variables are fixed-size arrays, you can use tuples, which should work.

**Comment by DavidPowell** [comment]
@pitrou It's good to know that this work around exists. The down side is that I can't do vectorised operations like adding two tuples together like I could with arrays. The appeal of numba for me is to be able to write clear and simple python code and get near-compiled performance. I currently have my critical routines in fortran, and would be willing to sacrifice some performance for maintainability and ease of debugging by moving to python and numba. But if I have to convoluted python (e.g. nested list comprehension) to get performance, then the benefit is lost. So I'd be very keen to see this issue addressed.

**Comment by rossant** [comment]
You can use vectorized operations on arrays, but you need to allocate the output arrays outside the jited function, and use `np.add(x, y, out)` instead of `x+y`. Alternatively, if your vectors are small, I imagine you could use structs or tuples and reimplement these operations yourself.

**Comment by David-OConnor** [comment]
Am I missing something here? It seems like being able to use, including creating, numpy.arrays is a fundamental part of writing fast code.

**Comment by seibert** [comment]
Array operations that use broadcasting are already pretty fast in Numpy because they go through a compiled code path.  A Numba-compiled version of such an operation could be somewhat faster (i.e., we might be able to emit SIMD instructions where the C compiler for Numpy could not), but there will not be as much benefit for it as compared to code that needs to do element-wise array access to perform operations that have no Numpy equivalent.

Numba's loop-lifting support mitigates the inability to compile array creation in nopython mode by automatically identifying and extracting loops in functions to compile in nopython mode.  These nopython loops can be bracketed by array allocation, and give you most of the benefit of compilation.  We also encourage users to take a look at the `@vectorize` decorator to create compiled ufuncs which can also do all the things that array expressions can handle.

Obviously, there are plenty of situations where allocating a new array inside a nopython function is necessary, which is why we are working on adding this ability, along with the ability to synthesize loops that implement the Numpy broadcast rules.  These features are not ready yet, however.

**Comment by pitrou** [comment]
np.empty() and np.zeros() are now supported in nopython mode, closing.
