### ISSUE TITLE
No definition for lowering <built-in method twoD_impl of _dynfunc._Closure object at 0x2b60ce355458>(array(float32, 2d, A), omitted(default=None)) -> float64

### ISSUE THREAD

**Issue by bowensu123** [numba/numba#8687]
## I try my code as below:
```
@jit
def compute(points):
    return linalg.norm(points)
compute_gpu = cuda.jit(float32(float32[:,:]),device = True)(compute)
```
However it keep throws an error:
 ```No definition for lowering <built-in method twoD_impl of _dynfunc._Closure object at 0x2b60ce355458>(array(float32, 2d, A), omitted(default=None)) -> float64
```
After I upgrade the version to 0.56.4, it throws an error:
```
Unknown attribute 'norm' of type Module(<module 'numpy.linalg' from '/mnt/home/subowen/.local/lib/python3.9/site-packages/numpy/linalg/__init__.py'>)
```

**Comment by gmarkall** [comment]
Unfortunately `linalg.norm` is not supported on the CUDA target - the list of supported features in CUDA is at https://numba.readthedocs.io/en/latest/cuda/cudapysupported.html.

I would suggest using [CuPy](https://cupy.dev/) in conjunction with Numba to be able to do linear algebra operations on the GPU  - Numba kernels can be called on CuPy arrays with no copy overhead because they interoperate through the [CUDA Array Interface](https://numba.readthedocs.io/en/latest/cuda/cuda_array_interface.html).

**Comment by gmarkall** [comment]
Closing as the original question appears to have been answered and no follow-up has been received.
