### ISSUE TITLE
np.digitize behaves differently with np.nan when jitted

### ISSUE THREAD

**Issue by fspinna** [numba/numba#8768]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.

```
import numpy as np
import numba

def foo():
    return np.digitize(np.array([np.nan, 1]), np.array([1.5, np.nan])) 

@numba.njit
def jitfoo():
    return np.digitize(np.array([np.nan, 1]), np.array([1.5, np.nan]))

foo()
# Out: array([0, 2])

jitfoo()
# Out: array([2, 0])

```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I think the problem is caused by an issue in the code that decides whether the bins are monotonically increasing or decreasing (or neither). It doesn't match the logic in NumPy closely enough and so the treatment of `NaN` will be different:
https://github.com/numba/numba/blob/566336cb20a05a50435342b3e73fd0e49b89a803/numba/np/arraymath.py#L3728-L3743

Another problematic input might be:
```python
from numba import njit
import numpy as np

@njit
def foo(x, y):
    return np.digitize(x, y)

x = np.array([np.nan, 1])
y = np.array([np.nan, 1.5, 2.3, np.nan])

print(foo(x, y))
print(foo.py_func(x, y))
```
whereby Numba returns an array of `[4, 0]` and NumPy raises a `ValueError`. I think NumPy is correct.
