### ISSUE TITLE
Explain what "lifted loops" are in the docs

### ISSUE THREAD

**Issue by dstansby** [numba/numba#8828]
## Feature request
I'm currently getting lots of warnings that look like:
```python
 Function "get_non_zero_ull_min" was compiled in object mode without forceobj=True, but has lifted loops.
```

I'm not sure what "lifted loops" means in this context though, and the docs don't seem to have anything on them. Searching for "lifted" just gives a couple of changelog entries: https://numba.readthedocs.io/en/stable/search.html?q=lifted&check_keywords=yes&area=default#

It would be great if someone who knows what's going on here could either improve the error message, or add some explanation about "lifted loops" to the docs

**Comment by stuartarchibald** [comment]
Thanks for the report. There's an entry in the glossary but the term is "spelled" slightly differently as it refers to the technique of "loop-lifting".
https://github.com/numba/numba/blob/07f824e49e5e2f158b79e7ba787674272baf1da0/docs/source/glossary.rst?plain=1#L36-L42

It would probably be a good idea to add another alias, namely "lifted loop" to this glossary entry so that it would appear in the results of searches that are similar to the above query.
