### ISSUE TITLE
0.57.0rc1 NumbaDeprecationWarning: `@guvectorize` even with `nopython` keyword argument

### ISSUE THREAD

**Issue by oyamad** [numba/numba#8903]
The following code (note the `nopython=True` argument)

```py
from numba import guvectorize, int64

@guvectorize([(int64[:], int64, int64[:])], '(n),()->(n)', nopython=True)
def g(x, y, res):
    for i in range(x.shape[0]):
        res[i] = x[i] + y
```

raises `NumbaDeprecationWarning`:

`/Applications/anaconda3/envs/py311/lib/python3.11/site-packages/numba/np/ufunc/ufuncbuilder.py:328: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  self.nb_func = jit(_target='npyufunc', cache=cache)(py_func)`

This does not occur with `@vectorize`:

```py
from numba import vectorize, float64

@vectorize([float64(float64, float64)], nopython=True)
def f(x, y):
    return x + y
```

```
>>> numba.__version__
'0.57.0rc1'
```

**Comment by guilhermeleobas** [comment]
Hi @oyamad, thanks for the report. I can confirm this "bug" in Numba. 

In the snippet of code below, the call to `jit` is missing `**targetoptions` expansion.

https://github.com/numba/numba/blob/be990a818c377408a1f41c37c7720bc2ba0fb89a/numba/np/ufunc/ufuncbuilder.py#L328

Numba doesn't report the warning on vectorize because of the `**targetoptions` expansion, which contains `nopython=True`

https://github.com/numba/numba/blob/be990a818c377408a1f41c37c7720bc2ba0fb89a/numba/np/ufunc/ufuncbuilder.py#L263-L265

Let me know if you'd like to send a patch fixing this issue.

**Comment by guilhermeleobas** [comment]
Hi @oyamad, really appreciate you putting some effort towards fixing this issue. 

We discuss this topic at today's Numba meeting and we have decided that it would be best to suppress the `NumbaDeprecationWarning`. Altering the call to `jit` could potentially result in unexpected behavior, especially if different flags are passed to the (gu)vectorize decorator.

**Comment by oyamad** [comment]
@guilhermeleobas Sure, so, in the description in https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.guvectorize, the keyword arguments `nopython`, `forceobj`, and `locals` for `guvectorize` (have been and) continue to be kept ignored? I guess that should be documented?
