### ISSUE TITLE
Different results with Numba 0.56 and 0.57

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#8993]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

It seems that Numba 0.56 is more consistent in what would happen without JIT than Numba 0.57. At PyData/Sparse, we have a CI job that disables JIT and runs the tests, that runs fine. However, we just received a bug report (pydata/sparse#594) which I highly suspect comes from improper code generation in Numba.

**Comment by esc** [comment]
@hameerabbasi thank you for reporting this!  A few things to consider:

* We are about to push out a 0.57.1 -- but the window for including fixes is closing very quickly. If this does turn out to be a regression for 0.57.0 -- it is worth considering adding a fix for this issue.
* I glanced at the report, but nothing immediate came to mind. Would it be possible to make a small, self-contained reproducer that uses only Numba w/o sparse?

**Comment by hameerabbasi** [comment]
Thanks @esc, I'll do my best to come up with a reproducer.

**Comment by esc** [comment]
> Thanks @esc, I'll do my best to come up with a reproducer.

Any luck on this? FYI: I'd like to push a 0.57.1 out this week.

**Comment by hameerabbasi** [comment]
Hey, unfortunately not yet. I haven't had time as my main PC needed repairs.

**Comment by esc** [comment]
@kc611 and @stuartarchibald debugged this for some time. The conclusions were as follows:

There are two separate issues:

One is where the failing tests complain about lists being negative(integer overflow) or memory buffer error. These are numerical test failures, the underlying cause is an incorrect initialization of an array with garbage memory instead of zeros.

fixed by:

```diff
diff --git a/sparse/_common.py b/sparse/_common.py
 index 96f43c7..2f7a67e 100644
 --- a/sparse/_common.py
 +++ b/sparse/_common.py
 @@ -844,7 +844,7 @@ def _dot_csc_ndarray_type_sparse(dt1, dt2):
          a_shape, b_shape : Tuple[int]
              The shapes of the input arrays.
          """
 -        indptr = np.empty(b_shape[1] + 1, dtype=np.intp)
 +        indptr = np.zeros(b_shape[1] + 1, dtype=np.intp)
          nnz = _csc_ndarray_count_nnz(a_shape, b_shape, indptr, a_indices, a_indptr, b)
          indices = np.empty(nnz, dtype=np.intp)
          data = np.empty(nnz, dtype=dtr)
```

Another set of test failures is where the failing tests complain about the COO object not being jitted in numba, and this issue is import related and caused by the way sparse is being tested (i.e. using `PYTHONPARTH=`) We would suggest that `PYTHONPATH=` is not suitable for use in testing with extension mechanisms relying on importlib entry points, and that the package should be installed so  there's an egg file present.

**Comment by eric-wieser** [comment]
I think that diff is overkill, only `indptr[0] = 0` is necessary.

**Comment by esc** [comment]
@hameerabbasi did you ever get to the bottom of this one?

**Comment by hameerabbasi** [comment]
The fix in https://github.com/numba/numba/issues/8993#issuecomment-1584570111 worked perfectly -- just a case of uninitialised memory working differently with different Numba versions and NumPy.
