### ISSUE TITLE
Empty NumPy String Array Error

### ISSUE THREAD

**Issue by ebonat** [numba/numba#9061]
Used:

python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
numpy: 1.23.5
numba: 0.57.0

Need to create an empty string numpy array. Below is the simple Python code:

 ```
b = np.array([])
    print(b)
    for i in a_nparray:
        b = np.append(b, str(i))    
    print(b)
```
Here is the error

Type of variable 'b' cannot be determined, operation: call $50load_method.1($52build_list.2, func=$50load_method.1, args=[Var($52build_list.2, nparray_list_test_numba.py:92)], kws=(), vararg=None, varkwarg=None, target=None), location: g:\Visual WWW\Python\1000_python_workspace\genetic_diagnostics_deep_learning\genome_assembler\src\nparray_list_test_numba.py (92)

File "src\nparray_list_test_numba.py", line 92:
def test(a_nparray):   
    <source elided>

    b = np.array([])
    ^

Thank you for your help.

**Comment by stuartarchibald** [comment]
Thanks for the report. The reproducer above seems incomplete, but I'd guess the code looks a bit like:
```python
from numba import njit
import numpy as np

@njit
def foo():
    b = np.array([])
    print(b)
    a_nparray = range(10)
    for i in a_nparray:
        b = np.append(b, str(i))
    print(b)

foo()
```
The issue being reported by Numba is that it cannot work out what the type of the variable `b` is. When Numba compiles functions it first has to try and work out the types of every variable in the function so that it can generate type specific machine code to execute. In the case above, the type of `b` cannot be determined because the NumPy array constructor is being given an empty list (it has no type as it contains no values!), and as it can't work out the type of the list it can't work out the type of the variable `b`. This isn't a bug, it's just the constraints necessary for Numba to be able to compile functions.


If one of the array allocator functions is used instead then `b`'s type can be found. i.e. `b = np.empty((<size>,))`. However if this is done it still won't compile because the type of the array is actually `'<U32'` due to the use of the string and `np.empty` will assume `np.float64` type. There's numerous other follow on issues to do with `.append` requiring an array-type etc. However, if the size of the array is known before running the loop (which it potentially is), the performance of the code would be better if an appropriately sized array is allocated outside the loop and the loop just fills in the array entries. For example:
```python
from numba import njit
import numpy as np

@njit
def foo():
    a_nparray = range(10)
    b = np.empty((len(a_nparray), ), dtype='<U32')
    for i in a_nparray:
        b[i] = str(i)
    print(b)

foo()
```
Hope this helps?

**Comment by ebonat** [comment]
Hello @stuartarchibald,

Thank you very much for your help. In my case, I'll be using string arrays. The code provided works with integer well. Below is an example:

```
@njit
def foo(a_nparray):      
    b = np.empty((len(a_nparray), ), dtype='<U32')
    for i in a_nparray:     
        b = np.append(b, str(i))
    print(b)

a_nparray = ['a' 'b' 'c' 'd' 'e']
foo(a_nparray)
```
Here is the error:

No implementation of function Function(<function append at 0x0000026E90AE2680>) found for signature:
 
 >>> append(array([unichr x 32], 1d, C), unicode_type)
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_append': File: numba\np\arrayobj.py: Line 2081.
    With argument(s): '(array([unichr x 32], 1d, C), unicode_type)':
   Rejected as the implementation raised a specific error:
     TypingError: The second argument "values" must be array-like
  raised from C:\Users\portland\anaconda3\envs\python3.10.9\lib\site-packages\numba\np\arrayobj.py:2088

During: resolving callee type: Function(<function append at 0x0000026E90AE2680>)
During: typing of call at g:\Visual WWW\Python\1000_python_workspace\genetic_diagnostics_deep_learning\genome_assembler\src\nparray_list_test_numba.py (164)

File "src\nparray_list_test_numba.py", line 164:
def foo(a_nparray):      
    <source elided>
    for i in a_nparray:
        b = np.append(b, str(i))
        ^

Thank you for your help again.

**Comment by stuartarchibald** [comment]
@ebonat no problem. In the above, the error message has:
```
TypingError: The second argument "values" must be array-like`
```
being raised from Numba trying to compile the `.append`, i.e. the `.append` implementation in Numba expects an array, it's being passed a `str()`. Whilst it's potentially possible to work around this, e.g.:
```python
from numba import njit
import numpy as np

@njit
def foo(a_nparray):
    b = np.empty((0, ), dtype='<U32')
    tmp = np.empty((1,), dtype='<U32')
    for i in a_nparray:
        tmp[0] = str(i)
        b = np.append(b, tmp)
    print(b)

a_nparray = ["a", "b", "c", "d", "e"]
foo(a_nparray)
```
the use of `np.append` in a loop like that is basically re-allocating the array `b` in every iteration. It would create much faster code if `b` were allocated outside of the loop and the loop used to fill in the entries (as per the second code sample in https://github.com/numba/numba/issues/9061#issuecomment-1623868217).

**Comment by ebonat** [comment]
hello @stuartarchibald

thank you for this code. two questions for you:

1. i don't have an append method of the "b" array and i for all items appended already. how? is this from numba?

```
@njit
def foo(nparray):   
    b = np.empty((1,), dtype='<U32')
    for i in nparray:
        b[0] = str(i)       
    print(b)
  
nparray = ['a' 'b' 'c' 'd' 'e']
foo(nparray)
```

`results: ['abcde']`

2. getting this "warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))" warning message. is this from numba? if yes, i don't want to see this warning message?

Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'nparray' of 
function 'foo'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "src\nparray_list_test_numba.py", line 185:
@njit
def foo(nparray):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
['abcde']

thank you!

**Comment by stuartarchibald** [comment]
@ebonat no problem.

1. Unfortunately, from the above, it's unclear to me what the intent of the code is, which makes it harder to offer specific advice. Also, this issue tracker is for tracking issues with Numba itself, perhaps it would be better to move this discussion/request for assistance to Numba's discourse forum, there's a community there that often provide general assistance with implementing things in Numba?
2. Perhaps visit the link that is in the error message, it suggests an alternative (`numba.typed.List` in this case)?

Hope this helps.
