### ISSUE TITLE
0.58.0rc1 old-style error capturing warning issues

### ISSUE THREAD

**Issue by sklam** [numba/numba#9151]
Issues:
- [x] Warnings about old-style error are raised regardless of whether the error is a `NumbaError`. (ref: https://matrix.to/#/!gFwSEpcuaweltInwDW:gitter.im/$5Mc1guc4peAryXvx3WjSWhD3TDxC_Nzb-mCQsl-s17k?via=gitter.im&via=matrix.org&via=matrix.kraut.space)
- [x] Reason of the warning is unclear (ref: https://numba.discourse.group/t/ann-numba-0-58-0rc1-and-llvmlite-0-41-0rc1/2078/2)

**Comment by jpivarski** [comment]
I'm watching this now.

**Comment by sklam** [comment]
@jpivarski, if it's convenient for you, can you try the patch from #9152 to see if the issue is resolved?

**Comment by jpivarski** [comment]
Would I need to compile Numba from scratch? (Last time, I tested it by checking out an rc version from the `numba` channel in conda.)

**Comment by sklam** [comment]
That's odd. No patches merged to main since the release would change the deprecation warning behavior. 

@jpivarski can you tell me which commit of awkward I should use to test? I want to check it locally.

**Comment by jpivarski** [comment]
Awkward was updated to use new-style exceptions in scikit-hep/awkward#2659, so it's in `main`, but it isn't in any releases yet.

This is the procedure for installing and testing from git: https://github.com/scikit-hep/awkward#installation-for-developers

The part that is sensitive to `NUMBA_CAPTURED_ERRORS` is the pure Python part, so if you are making changes in Numba and want to iteratively test them in Awkward, you only need to repeat the `.` installation, not the `./awkward-cpp` (and not even that, since the `.` installation is `-e`).

**Comment by sklam** [comment]
@jpivarski 

I confirmed with `pytest awkward/tests -k numba` that [numba main](https://github.com/numba/numba/commit/bd7ebcfd4b850208b627a3f75d4706000be36275) produces 11 failures and with https://github.com/numba/numba/pull/9152 produces no failures. I am using https://github.com/scikit-hep/awkward/commit/a42e44c2.

**Comment by jpivarski** [comment]
Okay, good: that makes more sense. (I don't know what I got wrong.) Thanks!
