### ISSUE TITLE
Cannot un`pickle` `ListTypeIteratorType`s

### ISSUE THREAD

**Issue by brandonwillard** [numba/numba#9177]
When attempting to use `njit(cache=True)` on a generator function on 0aa1a4abb, I received a `pickle` error that can be reproduced by the following:
```python
import pickle

import numba
from numba.core.types.containers import ListTypeIteratorType, ListTypeIterableType


iterable = ListTypeIterableType(numba.types.ListType(numba.int64))
iterator = ListTypeIteratorType(iterable)

assert iterator.name == "iter[ListType[int64]->int64]"

iterator_pkl = pickle.dumps(iterator)

pickle.loads(iterator_pkl)
# AttributeError: 'ListTypeIteratorType' object has no attribute 'name'
```
The error appears to arise from the `ListTypeIterableType` alone, as well.
 
It seems like it should be related to https://github.com/numba/numba/issues/8679, but I didn't see any mention of the `pickle`ing process in that issue.  Some element of https://github.com/numba/numba/issues/5997 might also be related.

**Comment by stuartarchibald** [comment]
I debugged this a bit, I think the issue is that the `ListTypeIterableType` instantiates a `ListTypeIteratorType` in its `__init__` that is based on a partially instantiated `self`. The `ListTypeIteratorType` then holds a references to this partially instantiated type and also queries it as part of it's `__init__`. Essentially, there's a cycle which resolves in the interpreter but is probably too much for `pickle`.

**Comment by brandonwillard** [comment]
This probably shouldn't be closed, right?
