### ISSUE TITLE
Surveying explicit uses of `nopython=False`

### ISSUE THREAD

**Issue by sklam** [numba/numba#9247]
Numba plans to [remove objectmode fallback](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit) in the 0.59 release. With the change, `nopython=False` will have no effect. We are surveying user code that uses `nopython=False` instead of using `forceobj=True`. Perhaps it is due to bugs in Numba that prevent users from using `nopython=True` or a miscommunication from our deprecation notices. Either way, we need to understand why.

Related issues:
- https://github.com/numba/numba/issues/8920

**Comment by crhea93** [comment]
Thank you for doing this! I opted to use the `nopython=False` argument because it seemed like this was the best (if not only) option from the documentation.

**Comment by sklam** [comment]
@crhea93
Ok, so our documentation has made this confusing.  The choices should be:
- use `nopython=True` for maximum performance. If that causes any error, let us know. 
- use `forceobj=True` if the function contains non-support feature, but has loops that are can potentially benefit from Numba.

**Comment by lmcinnes** [comment]
My use acse was old code that should probably be refactored to use the python object mode contexts, or simply ``forceobj=True``. Is there any reason to have preferences either way?

**Comment by sklam** [comment]
@lmcinnes, 

`forceobj=True` means object-mode by default but try to lift loops for nopython compilation.

_objectmode context_ will mean nopython by default but manually opt into object mode in particular area (only inside the with-context)

**Comment by sgbaird** [comment]
I think [my use of `nopython=False`](https://github.com/sparks-baird/dist-matrix/commit/6aae1ef63e4d771ecd9749c8dc913350bcce625e#r130215862) was to try to shore against backwards incompatibility. Unfortunately, I'm not much help because it's been long enough I don't remember why I chose to use it 😅 I don't think it will be problematic for me either way. The main reason for using that repository is to speed up distance calculations, including enabling distance matrix calculations on a GPU; otherwise someone should probably just use `scipy` or similar for computing distances.

**Comment by sklam** [comment]
https://github.com/numba/numba/pull/9352 has removed object mode fallback
