### ISSUE TITLE
Drop support for python 3.8 

### ISSUE THREAD

**Issue by sklam** [numba/numba#9272]
As per NEP-29 and SPEC 0.

**Comment by mbargull** [comment]
(@conda-forge/numba ( @henryiii @jakirkham @marcelotrevisani @mbargull @souravsingh @step21 ) for awareness.)

**Comment by gmarkall** [comment]
We should also note in the docs somewhere that we aim to support the versions following [SPEC 0](https://scientific-python.org/specs/spec-0000/) as a minimum, so that we can avoid deliberations similar to the one we just had for dropping 3.8 in 0.59 (along the lines of "did we provide sufficient notice that we're dropping 3.8?", etc.).

**Comment by jamesobutler** [comment]
@gmarkall per [SPEC 0](https://scientific-python.org/specs/spec-0000/) it states that Python 3.9 should be dropped in Q4 2023. Does that mean numba 0.59 should then only have support for the 3 latest Python versions (3.12, 3.11, 3.10)? I assume so since it appears a recent numba developer goal is to publicly state which drop schedule is being followed to avoid having to give the community notice as well.

**Comment by gmarkall** [comment]
I take it that it _could_ be dropped, not that it _should_. As far as I am aware there are no plans to drop 3.9 support for 0.59.

**Comment by jamesobutler** [comment]
Ok so numba isn’t following SPEC 0 as it recommends dropping Python 3.9 support in Q4 2023. Therefore numba is doing some custom drop schedule which is a bit difficult to guess when certain support will be dropped if there is no warning to the community.

**Comment by esc** [comment]
> Ok so numba isn’t following SPEC 0 as that guideline recommends dropping Python 3.9 support in Q4 2023. Therefore numba is doing some custom drop schedule which is a bit difficult to guess when certain support will be dropped if there is no warning to the community.

I think that, perhaps we should decide if Numba should adopt SPEC 0. I don't think that was ever discussed. I think that we loosely followed Numpy's Python support until now: https://numpy.org/neps/nep-0029-deprecation_policy.html -- which states that:

```
On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)
```

So, we are a bit behind on this one. But, the NEP also says:

```
On Apr 05, 2024 drop support for Python 3.9 (initially released on Oct 05, 2020)
```

So, that does conflict with SPEC 0.?

So, we probably out to decide if we should switch from NEP-29 to SPEC 0. That decision though needs to account for available resources and if it realistic for Numba to adhere to that. If we decided that we can, we need declare that we aim to support this and then try to catch up to the proposed schedule of SPEC 0 over a given timeframe.

For the time being, we will aim to drop 3.8 for 0.59 (next Numba version). I am open to discuss dropping 3.9 for 0.60 -- which would put us back on target to then drop 3.10 support in Q4 2024.

**Comment by henryiii** [comment]
> So, that does conflict with SPEC 0.?

Yes, SPEC 0 is here: https://scientific-python.org/specs/spec-0000/

It used to be a bit more clear, but it's clearly past the window in the plot, and dropping Python 3.9 is listed in "2023 - Quarter 4". And, of course, it states the 36 month window, while NEP 29 lists 42 months, which is why they differ.

If you do decide to follow SPEC 0, there's a list of endorsing projects that you might be able to be listed on, if you wanted to be.

**Comment by jamesobutler** [comment]
The creators of NEP29 have replaced it with SPEC0 as seen on the NEP29 page (https://numpy.org/neps/nep-0029-deprecation_policy.html).
![image](https://github.com/numba/numba/assets/15837524/81eb1298-c85f-4dc4-8445-04c52a8c706f)

The numpy maintainer has commented that they are waiting until numpy 2.0 is released to drop Python 3.9 support (see https://github.com/numpy/numpy/issues/24932), but per https://scientific-python.org/specs/spec-0000/#drop-schedule python 3.9 would be dropped in Q4 2023.

> Below is an auto generated schedule with recommended dates for dropping support. We suggest that the next release in a given quarter is considered as the one removing support for a given item.

**Comment by gmarkall** [comment]
> Ok so numba isn’t following SPEC 0 as that guideline recommends dropping Python 3.9 support in Q4 2023

As far as I can tell from reading it: it recommends versions to drop - I don't see that dropping versions outside its suggested windows is mandatory. It also says:

> You may want to delay the removal of support of an older Python version until your package fully works on the newly released Python, thus keeping the number of supported minor versions of Python the same for your package.

Numba usually supports 4 Python versions (historically, IIRC) so keeping 3.9, 3.10, 3.11 and 3.12 seems like it would be consistent for the time being.

If I'm failing to interpret SPEC 0 correctly I'd be keen to be shown the correct interpretation.

> Therefore numba is doing some custom drop schedule which is a bit difficult to guess when certain support will be dropped if there is no warning to the community.

If Numba were to drop versions more aggressively than SPEC 0 I could understand this point of view - since we're talking about supporting Python 3.9 longer than recommended, I find it hard to see how dropping Python 3.8 later than suggested can be thought of as dropping it with no warning.

**Comment by jamesobutler** [comment]
Since the spirit of SPEC 0 is about limiting the number of python versions supported to those released in the last 3 years, supporting python versions beyond that is going against that. SPEC 0 aims to limit the number of support Python versions rather than trying to support as many Python versions as possible. Numba could choose to continue support Python 3.9, but you get back to each Python package making their own call of when to drop certain support. So it is no longer following a standard. The Scientific Python community is aiming to coalesce on a common expected drop schedule.

**Comment by esc** [comment]
#9310 is merged, so this can be 🥁 closed!

**Comment by esc** [comment]
Followup: needs a ticket to request adopting SPEC 0

**Comment by esc** [comment]
> Followup: needs a ticket to request adopting SPEC 0

https://github.com/numba/numba/issues/9320
