### ISSUE TITLE
Numba with TBB warning, disabled

### ISSUE THREAD

**Issue by dpineiden** [numba/numba#9555]
## Reporting a bug

- [x ] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

/home/david/.cache/pypoetry/virtualenvs/gnssml-FCwMErw_-py3.10/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)

**Comment by kh-abd-kh** [comment]
I had the same problem and it turned out because i installed tbb with pip which is non-standard location.
you should look for the correct location 
in my case 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/:/usr/lib/:/usr/lib64/:/home/mabd/.local/lib/

solved the problem ; of course change mabd to your username

you can check by  
numba -s|grep True

CUDA Device Initialized                       : True
CUDA NVIDIA Bindings Available                : True
CUDA Minor Version Compatibility Available    : True
llvmlite Using SVML Patched LLVM              : True
TBB Threading Layer Available                 : True
OpenMP Threading Layer Available              : True
Workqueue Threading Layer Available           : True

**Comment by kc611** [comment]
Hi @dpineiden, Thanks for the report. Could you please give some more context as to how the error was encountered so that we can provide a proper solution.

(And also confirm if @kh-abd-kh 's solution works in your case.)
