### ISSUE TITLE
config.OPT is not overridden with override_config('OPT', 0)

### ISSUE THREAD

**Issue by yashssh** [numba/numba#9646]
Hi, 

I'm trying to migrate Numba to LLVM's new pass manager APIs introduced in [1046](https://github.com/numba/llvmlite/pull/1046) and I think I might have encountered a bug.
Some of the tests (eg test_debuginfo.py) make use of this snippet to override default config flags
```
with override_config('OPT', 0):
    fn.compile(sig)
    return fn.inspect_llvm(sig)
```
For example, when we execute the test `test_debuginfo.py:test_DILocation` `core/codegen.py:_optimize_final_module` makes a call to `_mpm_cheap.run()` and `_mpm_full.run()` with `config.OPT` correctly overriden to 0 (as expected).

However these pass manager objects are already created and exist even before `_optimize_final_module` was called (core/codegen.py:line 1211) with default `config.OPT` levels, meaning `override_config` snippet didn't have any effect.

I might be missing something here and this might not actually be a bug but nonetheless I would like to propose a solution/code-change  to shift creating of these pass manager objects inside `_optimize_final_module` function where they are used. It would also solve the problem of using same pass manager object and calling run() on it multiple times.

**Comment by yashssh** [comment]
Attaching a python reproducer

```
from numba import jit, njit
from numba.core import types
from numba.tests.support import override_config
import llvmlite.binding as llvm

@njit(debug=True, error_model='numpy')
def foo(a):
    b = a + 1.23
    c = b * 2.34
    d = b / c
    print(d)
    return d

@njit(debug=True, error_model='numpy')
def foo2(a):
    b = a + 1.23
    c = b * 2.34
    d = b / c
    print(d)
    return d


# Pass manager objects are already created when we define the above functions with @njit decorator

sig = (types.float64,)
def get_llvmir_of_function(fn, sig, opt_level=0):
    with override_config('OPT', opt_level):
        fn.compile(sig)
        full_ir = fn.inspect_llvm(sig)
        module = llvm.parse_assembly(full_ir)
        name = fn.overloads[fn.signatures[0]].fndesc.mangled_name
        func = [x for x in module.functions if x.name == name][0]
        return str(func)

fn0 = get_llvmir_of_function(foo, sig, 0)
fn3 = get_llvmir_of_function(foo2, sig, 3)



# IRs in both these files above is same(compiled for -O3)! \
# and is compiled with same pass manager object (which is not good incase we wanted to optimize the 2 functions differently)
with open("ir0.txt", "w") as text_file:
    text_file.write(fn0)

with open("ir3.txt", "w") as text_file:
    text_file.write(fn3)
```

**Comment by yashssh** [comment]
As I'm starting to investigate further it might not be a bug, please refrain from spending time on this before I confirm. Thanks :)

**Comment by dlee992** [comment]
Same here. Take a look how I override config in this test: https://github.com/NVIDIA/numba-cuda/pull/8/files#diff-963370af45b9b3f8e7320252c8c67ea13294b954ee5014ef53f3bea5d974cd4bR140.

```python
    def test_no_warn_on_debug_and_opt_with_config(self):
        with override_config('CUDA_DEBUGINFO_DEFAULT', 1):
            with override_config('OPT', config._OptLevel(0)):
                with warnings.catch_warnings(record=True) as w:
                    cuda.jit()
```

**Comment by yashssh** [comment]
After spending more time on it..
Moving creation of pass manager objects to `_optimize_final_module` or `CPUCodegen`'s `init` would solve the problem of using the same pass manager objects for compiling multiple python functions to native code. This would allow for a better control while optimizing unrelated modules separately and possibly under different settings(degree of vectorization, optimization level, etc). 

However, for the above example it won't still be sufficient as there is another variable at play here(which was my source of confusion and forced me to write the previous comment). The snippet:
```
with override_config('OPT', 0):
    fn.compile(sig)
```
Still won't be effective even though you are populating the pass manager object in accordance to the overidden `opt_level` and that's because when we did 
```
@njit(debug=True, error_model='numpy')
def foo(a):
    b = a + 1.23
    c = b * 2.34
    d = b / c
    print(d)
    return d
```
earlier, we initialized the JIT engine (for translating llvm IR code to machine code) with a default optimization level of 3 (see CPUCodegen._init). Which means even though you are running llvm optimization pipeline at `O0`, it's effect is overridden when you executed the JIT engine (I'm not sure on why do the JIT engine runs the optimization pipeline again, but that's a separate topic I suppose).

The correct way to achieve what we wanted to would be to use this snippet instead:
```
with override_config('OPT', config._OptLevel(0)):
    @njit(error_model='numpy')
    def foo(a):
        b = a + 1.23
        c = b * 2.34
        d = b / c
        print(d)
        return d

    sig = (types.float64,)
    foo.compile(sig)
```

Which is a slightly odd way to get around. I suggest Numba can stop using `config.OPT` while initializing JIT engine and always use `optlevel=0` there. So that the complete control of optimizing the module is in the hands of pass manger objects that we create, this would make our earlier snippet to behave properly as well. 

Kindly suggest what are your thoughts on this? Is my understanding of the pipeline correct? I'm purely talking with llvm background and would really like to understand Numba's policy around these API designs. Maybe these points have been discussed before and these APIs are deliberately designed the way they are?

Thanks :) 

cc @sklam @gmarkall

**Comment by dlee992** [comment]
The current implementation of `NUMBA_OPT` has a good reason, which allows users to fine-grained control the two stages of module pass managers, i.e., cheap_mpm and full_mpm separately. Actually, fine-grained control cheap_mpm in this case.
Different value of `NUMBA_OPT` can lead to different native code. 

You can try search `NUMBA_OPT` in the issue/PR list, more details in some threads.

**Comment by stuartarchibald** [comment]
Thanks for looking at this @yashssh. What you observe in your investigation correlates with my memory of the implementation. I noticed that the module pass manager was created really early and "fixed" against the `config.OPT`, and then discovered the knock-on effect of this, first in #6455 and then again when overhauling the generation of `DebugInfo` in #7116. Essentially, it was making the LLVM IR generated by llvmlite `builder` code slightly different than expected as there was an element of optimisation running unexpectedly even under an apparent `config.OPT=0`. I guess the impact of this detail is more prevalent now as so much has changed since this code was first written.

I think your understanding of the pipeline is correct, and the issue you are seeing with configuration variables etc is not unique to optimisation, Numba has historically never really defined the expected scope of use of such variables. Some variables are read every time they are encountered during a compilation, others are "frozen" on first encounter. As to why `opt` is run twice, first pass is to try and inline as much code as possible and simplify the CFG, the second pass then introduces Numba's "reference count pruning" pass which benefits from the having the most IR "visible" to it as possible, and it then does a standard `-O3` like behaviour (by default) on the reference pruned IR.

With regards to fixes, this will be discussed at the maintainer triage meeting tomorrow and discussion can spill into the Numba office hours as needed. I think that having a module pass manager per python function (i.e. put it in `_optimize_final_module` as suggested) would be a good change in that it removes captured state and will ultimately make it easier to handle the move to OrcJIT. As to the use of `config.OPT` and its scope, that's definitely something for wider discussion.

Hope this helps?

**Comment by yashssh** [comment]
Thanks for answering my questions @stuartarchibald! Sorry for the late reply I certainly didn't forget about it and I intend to submit a pull request for the change when I start making changes to Numba to shift to the new pass manager(currently getting things ready in llvmlite). 

The mpm_cheap and mpm_full runs do make sense to me now, but I still have 1 more question. Numba also runs optimization pipeline on each function of the module using function pass manager before running the mpm_cheap and mpm_full pipeline. What's the reason for that?

**Comment by yashssh** [comment]
> Numba also runs optimization pipeline on each function of the module using function pass manager before running the mpm_cheap and mpm_full pipeline. What's the reason for that?

This is also closely related to debugging another issue I'm facing.

**Comment by stuartarchibald** [comment]
> > Numba also runs optimization pipeline on each function of the module using function pass manager before running the mpm_cheap and mpm_full pipeline. What's the reason for that?
> 
> This is also closely related to debugging another issue I'm facing.

A lot of this is from Numba's evolution/history. Numba has been around for a very long time and has upgraded across many LLVM versions.

I suspect the specific piece of history in relation to the function pass manager (other maintainers please correct if this is wrong) is because historically Numba implementations of fundamental operations, Python functions and NumPy functions were implemented using `@lower_builtin`. What this decorator does is a bit like what closure of the `numba.extensions.intrinsic` decorator does now, it essentially emits whatever is written (using llvmlite builder code) directly into the current module at its call site. At the furthest point back in history, Numba was pretty much entirely implemented like this, everything was written in llvmlite builder code and as a result a `@jit` compiled function would likely just be one LLVM function. The result of this was that the LLVM level compiler pipeline just needed to be incredible basic as it was often operating on just few large functions in one module.

Fast forward a few years and two things happened, 1) enough of Python and NumPy had been implemented in low level builder code that more complex functions could now be written using this functionality, this is/was Numba's "bootstrapping" point. 2)  As a result of 1) `@numba.extensions.overload` appeared, which made it a lot easier to implement functions as they could essentially be written in pure python and the JIT compiler would handle the lowering, this created a massive increase in the amount of functions Numba could support and made it an order of magnitude easier for people to contribute (i.e. you don't have to write in LLVM builder code any more)! However... the low level pipeline for compiling functions did not change even though a lot more distinct functions would be declared in potentially a more modules.

More forward again and the compiler itself is refactored into having an actual pipeline and the LLVM code generation is now part of a compiler pass, it's now isolated and is part of what is called on each `@jit` function and by extension what's in the closure of an `@overload` function.

Move to right now... what you see is the legacy of this evolution. There's been numerous discussions about redesigning the LLVM optimisation pipeline and it's something I'm going to be looking at in the near future as the compiler is going to need considerably better performance at compile time (and potentially at run time) to deal with the necessary type split that NumPy 2.0 and NEP-050 brings. Input, ideas and help with this is most welcomed. There's already some thoughts in #9566 with regards to restructuring the linking and optimisation ordering of the modules. Further there's a long running set of thoughts about splitting up type inference and lowering so that lowering and optimisation are treated as a "final stage" of the pipeline associated with compiling a given entry point (this also helps with OrcJIT migration as the current API in llvmlite requires a more "everything is defined upfront" approach than is currently present with Numba's MCJIT linkage).

Apologies for the length of this, but I thought a full history might help and provide context for questions/answers. Sometimes there will be a technical answer, sometimes the answer is history/evolution of the code base.

Please do feel free to suggest changes/open discussions, many thanks for your help with this!

**Comment by yashssh** [comment]
Thanks for the detailed reply @stuartarchibald!

The history behind this code and why the pipeline is how is it right now do make sense to me. Although, I must admit I don't fully grasp what each of these extensions exactly do but I do get the high level idea. 

I think if we get rid of the phase in which we optimize each of the llvm functions separately before optimizing the whole module, Numba might have a lot to gain. 

1. There is no explicit need to do things this way(right now, after all the code evolution). If there was any performance to be gained llvm would have done something like that internally.
2. Reduced compilation times(won't be running optimizations on same code twice).
3. Better optimized codegen, the `FunctionPassManager` optimizer is not that great and does not perform many optimization([just basic rearrangements and simplifications](https://github.com/llvm/llvm-project/blob/release/14.x/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp#L312)). Which I believe can do more harm than good and prevent certain optimizations from kicking in when we do `MPM.run()`. (It's a long shot but I guess this also may be reason for missed vectorization opprtunities highlighted in discource thread you linked).
4. All tests pass without it :) I commented the line `self._optimize_functions(ll_module)` in `numba/codegen.py:add_llvm_module` and other than 2 refprune related tests everything passed, which may be a good indication as this step is redundant. 

If I think/stumble on more points or concrete examples I'll add to the thread.
