### ISSUE TITLE
Inconsistent behavior when handling empty iterator with jit

### ISSUE THREAD

**Issue by Mskxn** [numba/numba#9647]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello, this code snippet behavior differently when enable jit.
I guess cpython  and pypy do not create `i` when the iter is empty, but numba with jit does.
However, I'm not sure if this is an undefined behavior that can vary across implementations.
```python
from numba import jit

@jit
def f():
    j = [0]
    it = iter(j)
    next(it)
    for i in it:
        pass
    return i

r = f()
print(r) # expect UnboundLocalError (cpython 3.10.12) but 0 (numba 0.60.0)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is known and expected behaviour and is due to the current implementation details of Numba. Essentially, when Numba compiles a function, all variables are allocated a slot in the preamble of the compiled version of the code (regardless of whether they would actually exist during execution) and these slots are all zero-initialized. Numba also largely assumes during analysis that all code _could_ execute regardless of whether it will execute at runtime, it therefore assumes that `i` could exist. Doing the runtime semantic analysis at compile time for these sorts of use cases is currently beyond its capability. Hopefully this explains what you are observing?
