### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by EarlMilktea** [numba/numba#9790]
## Feature request

I would like to use type annotations with `numba` (no advanced features intended, such as reading annotations runtime: just plain annotations for `mypy`).

Are there any plans for working on that? If not, is it OK to submit PRs for this feature?

**Comment by sklam** [comment]
To clarify, are you wanting to add type annotations to numba's code base for mypy to work?

**Comment by EarlMilktea** [comment]
For exported items such as `@numba.njit` or `TypedDict` for now (while annotating internal members may help `numba` developer...)

**Comment by sklam** [comment]
Yes, it makes sense to add type annotations to the public facing APIs. But be warned, I think the Numba decorators are a bit complicated to add annotations just because they can be used in multiple ways. 

If you would like to contribute, it is best to keep the PR small so it is easier for maintainers to review.
