### ISSUE TITLE
numba fail

### ISSUE THREAD

**Issue by rishilohia** [numba/numba#9808]
File "C:\Users\trader\AppData\Roaming\Python\Python36\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

**Comment by esc** [comment]
@rishilohia since we have not heard back from you, I am assuming issue is resolved now and will close. If you continue to experience these issues please don't hesitate to add a comment to this issue and request to re-open it. In that case, please also provide more detailed information:

* What did you do, exactly?
* What were you expecting, exactly?
* What happened instead, exactly?
